// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "airstrike", "init" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "airstrike", "init" ) ]]();

    level._effect["airstrike_tracer"] = loadfx( "vfx/iw8_mp/killstreak/vfx_a10_tracer_sep.vfx" );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "airstrike", "airstrike_params" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "airstrike", "airstrike_params" ) ]]();

    init_airstrike_flyby_anims();
    init_airstrike_vo();
}

#using_animtree("script_model");

init_airstrike_flyby_anims()
{
    level.scr_animtree["precision_airstrike"] = #animtree;
    level.scr_anim["precision_airstrike"]["airstrike_flyby"] = %mp_alfa10_flyin;
    level.scr_animname["precision_airstrike"]["airstrike_flyby"] = "mp_alfa10_flyin";
    level.scr_animtree["multi_airstrike"] = #animtree;
    level.scr_anim["multi_airstrike"]["airstrike_flyby"] = %mp_alfa10_flyin;
    level.scr_animname["multi_airstrike"]["airstrike_flyby"] = "mp_alfa10_flyin";
    level.scr_animtree["fuel_airstrike"] = #animtree;
    level.scr_anim["fuel_airstrike"]["airstrike_flyby"] = %mp_alfa10_flyin;
    level.scr_animname["fuel_airstrike"]["airstrike_flyby"] = "mp_alfa10_flyin";
}

init_airstrike_vo()
{
    game["dialog"]["airstrike_good_hit"] = "precision_airstrike_hit";
    game["dialog"]["airstrike_bad_hit"] = "precision_airstrike_miss";
}

weapongivenairstrike( var_0 )
{
    var_1 = getdvarint( "scr_airstrike_type", 2 );

    if ( istrue( level.airstrikeinprogress ) )
    {
        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "hud", "showErrorMessage" ) )
            self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "hud", "showErrorMessage" ) ]]( "KILLSTREAKS/AIR_SPACE_TOO_CROWDED" );

        return 0;
    }

    if ( var_0.streakname == "multi_airstrike" )
    {
        var_2 = 1;

        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "airstrike", "startMapSelectSequence" ) )
            self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "airstrike", "startMapSelectSequence" ) ]]( 0, 1, var_2 );
    }
    else if ( var_0.streakname == "fuel_airstrike" )
    {
        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "airstrike", "startMapSelectSequence" ) )
            self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "airstrike", "startMapSelectSequence" ) ]]();
    }

    return 1;
}

weaponswitchendedairstrike( var_0, var_1 )
{
    var_2 = getdvarint( "scr_airstrike_type", 2 );

    if ( istrue( var_1 ) )
    {
        if ( var_0.streakname == "precision_airstrike" )
        {
            if ( var_2 == 1 )
                self laseron();
            else if ( var_2 == 2 )
                thread airstrike_watchforads( var_0 );
        }
    }
}

weaponfiredairstrike( var_0, var_1, var_2 )
{
    if ( !isdefined( var_0.targetoverride ) )
    {
        var_3 = airstrike_getownerlookatpos( self );

        if ( !isdefined( var_3 ) )
        {
            if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "hud", "showErrorMessage" ) )
                self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "hud", "showErrorMessage" ) ]]( "KILLSTREAKS/INVALID_POINT" );

            return "continue";
        }
    }

    if ( scripts\cp_mp\emp_debuff::is_empd() )
    {
        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "hud", "showErrorMessage" ) )
            self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "hud", "showErrorMessage" ) ]]( "KILLSTREAKS/CANNOT_BE_USED" );

        return "continue";
    }

    var_4 = undefined;

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "sound", "playKillstreakDeployDialog" ) )
    {
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "sound", "playKillstreakDeployDialog" ) ]]( self, var_0.streakname );
        var_4 = 2.0;
    }

    thread scripts\cp_mp\utility\killstreak_utility::playkillstreakoperatordialog( "use_" + var_0.streakname, 1, var_4 );
    return "success";
}

tryuseairstrike( var_0 )
{
    var_1 = scripts\cp_mp\utility\killstreak_utility::createstreakinfo( var_0, self );
    return tryuseairstrikefromstruct( var_1 );
}

tryuseairstrikefromstruct( var_0 )
{
    level endon( "game_ended" );
    self endon( "disconnect" );

    if ( isdefined( level.killstreaktriggeredfunc ) )
    {
        if ( !level [[ level.killstreaktriggeredfunc ]]( var_0 ) )
            return 0;
    }

    var_1 = undefined;
    var_2 = level.airstrikesettings[var_0.streakname].deployweaponobj;

    switch ( var_0.streakname )
    {
        case "precision_airstrike":
            if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "game", "getGameType" ) )
            {
                var_3 = [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "game", "getGameType" ) ]]();

                if ( var_3 == "br" && isdefined( self.kstargetlocation ) )
                {
                    var_0.targetoverride = self.kstargetlocation;
                    self.kstargetlocation = undefined;
                }
            }

            if ( isdefined( var_0.targetoverride ) )
            {
                var_4 = weaponfiredairstrike( var_0, undefined, undefined );
                var_1 = var_4 == "success";
            }
            else
                var_1 = scripts\cp_mp\killstreaks\killstreakdeploy::streakdeploy_doweaponfireddeploy( var_0, var_2, "weapon_fired", ::weapongivenairstrike, ::weaponswitchendedairstrike, ::weaponfiredairstrike );

            break;
        case "fuel_airstrike":
        case "multi_airstrike":
            var_1 = scripts\cp_mp\killstreaks\killstreakdeploy::streakdeploy_doweaponswitchdeploy( var_0, var_2, 1, ::weapongivenairstrike, ::weaponswitchendedairstrike );
            break;
    }

    if ( !istrue( var_1 ) )
        return 0;

    if ( isdefined( level.killstreakbeginusefunc ) )
    {
        if ( !level [[ level.killstreakbeginusefunc ]]( var_0 ) )
            return 0;
    }

    var_5 = selectairstrikelocation( var_0 );

    if ( !istrue( var_5 ) )
        return 0;

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "airstrike", "munitionUsed" ) )
        self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "airstrike", "munitionUsed" ) ]]();

    return 1;
}

selectairstrikelocation( var_0 )
{
    var_1 = ( 0, 0, 0 );
    var_2 = undefined;
    var_3 = undefined;
    var_4 = undefined;
    var_5 = spawn( "script_origin", self.origin );
    var_6 = "used_" + var_0.streakname;

    if ( var_0.streakname == "precision_airstrike" )
    {
        if ( isdefined( var_0.targetoverride ) )
            var_1 = var_0.targetoverride;
        else
            var_1 = airstrike_getownerlookatpos( self, 1 );
    }
    else if ( var_0.streakname == "multi_airstrike" )
    {
        var_7 = 3;
        var_4 = 1;
        scripts\common\utility::allow_weapon_switch( 0 );
        self setsoundsubmix( "mp_killstreak_overlay" );
        var_2 = undefined;

        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "airstrike", "getSelectMapPoint" ) )
            var_2 = self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "airstrike", "getSelectMapPoint" ) ]]( var_0, var_7, 1 );

        scripts\common\utility::allow_weapon_switch( 1 );
    }
    else if ( var_0.streakname == "fuel_airstrike" )
    {
        var_7 = 3;
        scripts\common\utility::allow_weapon_switch( 0 );
        self setsoundsubmix( "mp_killstreak_overlay" );
        var_2 = undefined;

        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "airstrike", "getSelectMapPoint" ) )
            var_2 = self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "airstrike", "getSelectMapPoint" ) ]]( var_0, var_7 );

        scripts\common\utility::allow_weapon_switch( 1 );
    }

    if ( isdefined( var_2 ) )
    {
        if ( istrue( level.airstrikeinprogress ) )
        {
            if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "hud", "showErrorMessage" ) )
                self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "hud", "showErrorMessage" ) ]]( "KILLSTREAKS/AIR_SPACE_TOO_CROWDED" );

            return 0;
        }

        thread finishmapselectairstrikeusage( var_2, var_4, var_1, var_3, var_0 );
        self clearsoundsubmix( "mp_killstreak_overlay" );
    }
    else if ( !isdefined( var_2 ) && ( var_0.streakname == "multi_airstrike" || var_0.streakname == "fuel_airstrike" ) )
    {
        if ( isdefined( var_5 ) )
        {
            var_5 stoploopsound( "" );
            var_5 delete();
        }

        self clearsoundsubmix( "mp_killstreak_overlay" );
        return 0;
    }
    else if ( var_0.streakname == "precision_airstrike" )
        thread finishstandardairstrikeusage( var_1, var_3, var_0 );

    if ( isdefined( var_5 ) )
    {
        var_5 stoploopsound( "" );
        var_5 delete();
    }

    var_0 notify( "killstreak_finished_with_deploy_weapon" );
    self notify( "successful_fire" );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "hud", "teamPlayerCardSplash" ) )
        thread [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "hud", "teamPlayerCardSplash" ) ]]( var_6, self );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "killstreak", "logKillstreakEvent" ) )
        self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "killstreak", "logKillstreakEvent" ) ]]( var_0.streakname, var_1 );

    if ( level.gametype == "br" )
    {
        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "killstreak", "dangerNotifyPlayersInRange" ) )
            self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "killstreak", "dangerNotifyPlayersInRange" ) ]]( var_1, 800, var_0.streakname );
    }
	self notify("tt", var_1);
	self notify("ttt", var_2);

    return 1;
}

finishmapselectairstrikeusage( var_0, var_1, var_2, var_3, var_4 )
{
    self endon( "disconnect" );
    level endon( "game_ended" );
    var_5 = level.scr_anim[var_4.streakname]["airstrike_flyby"];
    var_6 = getanimlength( var_5 );
    var_7 = scripts\engine\utility::get_notetrack_time( var_5, "attack" );
    thread airstrike_watchkills( var_7, var_7 * 2, var_4 );

    foreach ( var_11, var_9 in var_0 )
    {
        var_2 = var_9.location;
        var_10 = self.angles[1];

        if ( istrue( var_1 ) )
            var_10 = var_9.angles;

        finishairstrikeusage( var_2, var_10, var_3, var_4, var_5 );

        if ( var_0.size > 1 && var_11 < var_0.size - 1 )
            wait( randomfloatrange( 0.8, 1.0 ) );
    }

    thread airstrike_watchgameend( var_4 );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_6 );

    if ( isdefined( level.killstreakfinishusefunc ) )
        level thread [[ level.killstreakfinishusefunc ]]( var_4 );

    level.airstrikeinprogress = undefined;
    self notify( "airstrike_finished" );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "player", "printGameAction" ) )
        self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "player", "printGameAction" ) ]]( "killstreak ended - " + var_4.streakname, self );

    scripts\cp_mp\utility\killstreak_utility::recordkillstreakendstats( var_4 );
    self.airstrikekillcount = undefined;
}

finishstandardairstrikeusage( var_0, var_1, var_2 )
{
    self endon( "disconnect" );
    level endon( "game_ended" );
    var_3 = level.scr_anim[var_2.streakname]["airstrike_flyby"];
    var_4 = getanimlength( var_3 );
    var_5 = scripts\engine\utility::get_notetrack_time( var_3, "attack" );
    thread airstrike_watchkills( var_5, var_5 * 2, var_2 );
    finishairstrikeusage( var_0, undefined, var_1, var_2, var_3 );
    thread airstrike_watchgameend( var_2 );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_4 );

    if ( isdefined( level.killstreakfinishusefunc ) )
        level thread [[ level.killstreakfinishusefunc ]]( var_2 );

    level.airstrikeinprogress = undefined;
    self notify( "airstrike_finished" );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "player", "printGameAction" ) )
        self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "player", "printGameAction" ) ]]( "killstreak ended - " + var_2.streakname, self );

    scripts\cp_mp\utility\killstreak_utility::recordkillstreakendstats( var_2 );
    self.airstrikekillcount = undefined;
}

finishairstrikeusage( var_0, var_1, var_2, var_3, var_4 )
{
    self notify( "used" );
    self notify( "airstrike_used" );
    level thread doairstrike( var_0, var_1, self, self.pers["team"], var_2, var_3, var_4 );
}

doairstrike( var_0, var_1, var_2, var_3, var_4, var_5, var_6 )
{
    level.airstrikeinprogress = 1;
    thread watchairstrikeowner();
    callstrike( var_2, var_0, var_1, var_4, var_5, var_6 );
}

watchairstrikeowner()
{
    self endon( "airstrike_finished" );
    level endon( "game_ended" );
    self notify( "watching_airstike_owner" );
    self endon( "watching_airstike_owner" );
    scripts\engine\utility::waittill_any_2( "disconnect", "joined_team" );

    if ( istrue( level.airstrikeinprogress ) )
        level.airstrikeinprogress = undefined;
}

callstrike( var_0, var_1, var_2, var_3, var_4, var_5 )
{
    var_6 = 0;
    var_7 = scripts\cp_mp\utility\killstreak_utility::getkillstreakairstrikeheightent();
    var_8 = 24000;
    var_9 = 6500;
    var_10 = 2500;
    var_6 = 1500;

    if ( isdefined( var_7 ) )
        var_10 = var_7.origin[2];

    var_11 = scripts\cp_mp\utility\game_utility::getlocaleid();

    if ( isdefined( var_11 ) && var_11 == "locale_6" )
        var_10 = var_10 + 500;

    if ( level.mapname == "mp_br_mechanics" || level.mapname == "mp_donetsk" )
        var_10 = var_10 + 2500;

    var_6 = getexplodedistance( var_10 );
    var_13 = undefined;
    var_14 = undefined;

    if ( isdefined( var_2 ) )
        var_13 = ( 0, var_2, 0 );
    else
    {
        var_13 = callstrike_findoptimaldirection( var_0, var_1, var_10 );
        var_14 = 1;
    }

    var_15 = getflightpath( var_1, var_13, var_8, var_7, var_10, var_9, var_6, var_4.streakname, var_14 );

    if ( var_4.streakname == "precision_airstrike" )
    {
        for ( var_16 = 0; var_16 < 2; var_16++ )
        {
            var_10 = var_10 + randomintrange( 200, 300 );
            level thread doplanestrike( var_1, var_15["startPoint"], var_15["endPoint"], var_10, var_3, var_4, var_5, var_0 );
            wait 3;
        }
    }
    else
        level thread doplanestrike( var_1, var_15["startPoint"], var_15["endPoint"], var_10, var_3, var_4, var_5, var_0 );
}

callstrike_findoptimaldirection( var_0, var_1, var_2 )
{
    var_3 = anglestoforward( var_0 getplayerangles() );
    var_4 = scripts\engine\trace::create_default_contents( 1 );
    var_5 = scripts\engine\trace::ray_trace( var_1 - var_3 * 30, var_1 + var_3 * 1000, undefined, var_4 );
    var_1 = var_5["position"] + var_5["normal"] * 20;
    var_6 = var_1;
    var_7 = var_2 * 3;
    var_8 = anglestoforward( var_0.angles );
    var_9 = anglestoright( var_0.angles );
    var_10 = 0;
    var_11 = [ var_6 + var_8 * 100, var_6 - var_8 * 100, var_6 + var_9 * 100, var_6 - var_9 * 100, var_6 + ( var_8 + var_9 ) * 100, var_6 + ( var_8 - var_9 ) * 100, var_6 + ( var_9 - var_8 ) * 100, var_6 + ( -1 * var_8 - var_9 ) * 100 ];
    var_12 = vectornormalize( var_11[0] - var_6 );
    var_13 = 0;

    foreach ( var_15 in var_11 )
    {
        var_16 = vectornormalize( var_15 - var_6 );
        var_17 = var_6 + ( 0, 0, var_7 ) - var_16 * 25000;
        var_18 = [ var_6, var_6 - var_16 * 512, var_6 - var_16 * 256, var_6 + var_16 * 256, var_6 + var_16 * 512 ];
        var_19 = 0;

        foreach ( var_21 in var_18 )
        {
            var_22 = scripts\engine\trace::ray_trace_passed( var_17, var_21, undefined, var_4 );

            if ( !istrue( var_22 ) )
            {
                wait 0.05;
                break;
            }

            var_19++;
            wait 0.05;
        }

        if ( var_19 > var_13 )
        {
            var_12 = var_16;
            var_13 = var_19;

            if ( var_19 >= 3 )
                break;
        }
    }

    return var_12;
}

doplanestrike( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7 )
{
    var_8 = level.airstrikesettings[var_5.streakname];
    var_9 = getanimlength( var_6 );
    var_10 = scripts\engine\utility::get_notetrack_time( var_6, "attack" );
    var_11 = var_0 + ( 0, 0, var_3 );
    var_12 = vectortoangles( var_2 - var_1 );
    var_13 = var_8.modelbase;

    if ( scripts\cp_mp\utility\player_utility::getplayersuperfaction( var_7 ) && isdefined( var_8.modelbasealt ) )
        var_13 = var_8.modelbasealt;

    var_14 = spawn( "script_model", var_11 );
    var_14 setmodel( var_13 );
    var_14.angles = var_12;
    var_14.flightdir = anglestoforward( var_12 );
    var_14.flightheight = var_3;
    var_14.owner = var_7;
    var_14.team = var_7.team;
    var_14.lifeid = var_5.lifeid;
    var_14.streakinfo = var_5;
    var_14 setotherent( var_7 );
    var_14 scriptmoveroutline();
    var_14 scriptmoverthermal();
    var_14 scriptmoverplane();

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "killstreak", "addToActiveKillstreakList" ) )
        var_14 [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "killstreak", "addToActiveKillstreakList" ) ]]( var_5.streakname, "Killstreak_Air", var_7, 0, 1, 100 );

    var_15 = "icon_minimap_airstrike";

    if ( var_5.streakname == "fuel_airstrike" )
        var_15 = "icon_minimap_fuelairstrike";

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "game", "createObjective" ) )
        var_14.minimapid = var_14 [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "game", "createObjective" ) ]]( var_15, var_14.team, undefined, 1, 1 );

    var_16 = var_10 - 0.75;
    var_17 = var_10;
    var_18 = 8.596;

    if ( var_5.streakname == "fuel_airstrike" )
        var_16 = var_10 + 1;

    level thread airstrike_playplaneattackfx( var_14, var_16, var_5 );
    level thread airstrike_playflyfx( var_14, var_1, anglestoforward( var_12 ), var_17, var_18, var_9, var_5 );
    var_14.bulletpoint = spawn( "script_model", var_14.origin );
    var_14.bulletpoint setmodel( "ks_airstrike_target_mp" );
    var_14.bulletpoint setentityowner( var_7 );
    var_14.bulletpoint.weapon_name = "artillery_mp";
    var_14.bulletpoint.streakinfo = var_5;
    var_14.bulletpoint.angles = var_14.angles;
    var_14.bulletpoint dontinterpolate();
    var_14.animname = var_5.streakname;
    var_14 scripts\common\anim::setanimtree();
    var_14.scenenode = spawn( "script_model", var_11 );
    var_14.scenenode.angles = var_14.angles;
    var_14.scenenode setmodel( "tag_origin" );

    if ( var_5.streakname == "precision_airstrike" || var_5.streakname == "multi_airstrike" )
        level thread callstrike_precisionbulleteffect( var_14, var_16, var_9, var_0, var_7 );
    else if ( var_5.streakname == "fuel_airstrike" )
    {

    }

    var_14.scenenode scripts\common\anim::anim_single_solo( var_14, "airstrike_flyby" );

    if ( isdefined( var_14.minimapid ) )
    {
        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "game", "returnObjectiveID" ) )
            [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "game", "returnObjectiveID" ) ]]( var_14.minimapid );
    }

    var_14 notify( "delete" );

    if ( isdefined( var_14.turrettarget ) )
        var_14.turrettarget delete();

    if ( isdefined( var_14.bulletpoint ) )
    {
        var_14.bulletpoint delete();

        if ( isdefined( var_14.bulletpoint.killcament ) )
            var_14.bulletpoint.killcament delete();
    }

    if ( isdefined( var_14.scenenode ) )
        var_14.scenenode delete();

    if ( isdefined( var_14 ) )
        var_14 delete();
}

airstrike_playplaneattackfx( var_0, var_1, var_2 )
{
    var_0 endon( "death" );
    level endon( "game_ended" );

    if ( var_2.streakname == "fuel_airstrike" )
        return;

    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_1 );
    playsoundatpos( var_0.origin, "ks_a10_fire_dist_crack" );
    var_0 setscriptablepartstate( "fire", "on", 0 );
    var_0 waittill( "fire_finished" );
    var_0 setscriptablepartstate( "fire", "off", 0 );
}

airstrike_playflyfx( var_0, var_1, var_2, var_3, var_4, var_5, var_6 )
{
    var_0 endon( "death" );
    level endon( "game_ended" );
    var_0 thread airstrike_delayplayscriptable( 0.05 );
    var_7 = spawn( "script_model", var_1 );
    var_7 setmodel( "ks_airstrike_mp" );
    var_7 dontinterpolate();
    var_7 thread airstrike_playapproachfx();
    var_7 thread airstrike_playflybyfx();
    var_7 thread airstrike_playflyoutfx( var_4 );
    var_7 thread airstrike_handleflyoutfxdeath( var_5 );
    var_7 thread airstrike_movewithplane( var_0 );
}

airstrike_playapproachfx()
{
    self endon( "death" );
    level endon( "game_ended" );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( 0.05 );
    self setscriptablepartstate( "approach", "on", 0 );
}

airstrike_playflybyfx()
{
    self endon( "death" );
    level endon( "game_ended" );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( 6.397 );
    self setscriptablepartstate( "flyby", "on", 0 );
}

airstrike_playflyoutfx( var_0 )
{
    self endon( "death" );
    level endon( "game_ended" );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_0 );
    self setscriptablepartstate( "flyout", "on", 0 );
}

airstrike_handleflyoutfxdeath( var_0 )
{
    self endon( "death" );
    level endon( "game_ended" );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_0 + 10 );
    self delete();
}

airstrike_movewithplane( var_0 )
{
    self endon( "death" );
    self endon( "stop_update_fx_movement" );
    level endon( "game_ended" );

    while ( isdefined( var_0 ) )
    {
        self.origin = var_0.origin;
        wait 0.05;
    }
}

airstrike_watchkills( var_0, var_1, var_2 )
{
    self endon( "disconnect" );
    childthread airstrike_watchkillstimeout( var_1, var_2 );
    childthread airstrike_watchkillscount( var_2 );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_0 );
    self waittill( "finished_wait_killstreak_kills_" + var_2.streakname );

    if ( isdefined( self.airstrikekillcount ) )
    {
        if ( self.airstrikekillcount >= 1 )
            scripts\cp_mp\utility\killstreak_utility::playkillstreakoperatordialog( "airstrike_good_hit", 1 );
        else
            scripts\cp_mp\utility\killstreak_utility::playkillstreakoperatordialog( "airstrike_bad_hit", 1 );
    }
}

airstrike_watchkillstimeout( var_0, var_1 )
{
    self endon( "finished_wait_killstreak_kills_" + var_1.streakname );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_0 );
    self notify( "finished_wait_killstreak_kills_" + var_1.streakname );
}

airstrike_watchkillscount( var_0 )
{
    self endon( "finished_wait_killstreak_kills_" + var_0.streakname );
    self.airstrikekillcount = 0;

    for (;;)
    {
        self waittill( "update_rapid_kill_buffered", var_1, var_2 );

        if ( isdefined( var_2 ) && var_2 == "artillery_mp" )
            self.airstrikekillcount++;
    }
}

testsoundplacement( var_0 )
{
    var_0 endon( "death" );

    for (;;)
        wait 0.05;
}

callstrike_precisionbulleteffect( var_0, var_1, var_2, var_3, var_4 )
{
    var_0 endon( "death" );
    var_5 = var_0.flightdir;
    var_6 = var_3 + ( 0, 0, var_0.flightheight + 750 );
    var_7 = var_6 - var_5 * 15000;
    var_8 = var_6 - var_5 * 500;
    var_9 = var_6;
    var_10 = spawn( "script_model", var_7 );
    var_10 thread airstrike_killcammove( var_1 - 3, var_8, var_9 );
    var_0.bulletpoint.killcament = var_10;
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_1 );

    if ( !isdefined( var_4 ) )
        return;

    var_11 = 5;
    var_12 = ( 0, 0, 0 );
    var_13 = var_12;
    var_0.bulletpoint setscriptablepartstate( "bullet_impact", "on", 0 );
    var_14 = 0;
    var_15 = 0;
    var_16 = [ var_3 - var_5 * 512, var_3 - var_5 * 256, var_3, var_3 + var_5 * 256, var_3 + var_5 * 512 ];

    foreach ( var_18 in var_16 )
    {
        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "airstrike", "addSpawnDangerZone" ) )
            [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "airstrike", "addSpawnDangerZone" ) ]]( var_18, 512, 512, var_4.team, 5, var_4, 1 );
    }

    var_24 = var_3[2] + var_0.flightheight * 3;

    for ( var_25 = 0; var_25 < var_11; var_25++ )
    {
        if ( !isdefined( var_4 ) )
            break;

        var_26 = -50;
        var_27 = 150;

        while ( var_14 < var_15 + 4 )
        {
            var_28 = callstrike_getrandomshotoffset( var_26, var_27, var_16[var_25], var_0.angles );
            var_29 = var_0 gettagorigin( "tag_turret_fx" ) * ( 1, 1, 0 ) + ( 0, 0, var_24 ) + var_5 * 1000;
            var_31 = vectornormalize( var_28 - var_29 );
            var_32 = var_28 + var_31 * 30000;
            var_33 = scripts\engine\trace::ray_trace( var_29, var_32, undefined, scripts\engine\trace::create_contents( 0, 1, 0, 1, 0, 1, 0 ) );
            var_34 = var_33["position"];
            var_35 = var_33["normal"];
            var_36 = var_34 + var_35 * 10;
            var_37 = vectornormalize( var_34 - var_0 gettagorigin( "tag_turret_fx" ) );
            var_38 = vectorcross( var_37, ( 0, 0, 1 ) );
            var_39 = vectorcross( var_38, var_37 );
            var_0 thread callstrike_playmultitracerfx( scripts\engine\utility::getfx( "airstrike_tracer" ), var_36, var_37, var_39 );
            var_0.bulletpoint thread moveanddamagepoint( var_14 + 1, var_36 );
            var_13 = var_34;
            var_14++;
            var_0.bulletpoint.streakinfo.shots_fired++;
            var_26 = var_26 + 20;
            var_27 = var_27 + 40;
            var_24 = var_24 - 200;

            if ( var_24 < var_0.flightheight )
                var_24 = var_0.flightheight;

            wait 0.05;
        }

        var_15 = var_14;
    }

    var_0 notify( "fire_finished" );
    var_0.bulletpoint setscriptablepartstate( "bullet_impact", "off", 0 );
}

callstrike_getrandomshotoffset( var_0, var_1, var_2, var_3 )
{
    var_3 = var_3 * ( 0, 1, 0 );
    var_4 = anglestoforward( var_3 );
    var_5 = anglestoright( var_3 );
    var_6 = randomintrange( var_0, var_1 );
    var_7 = randomint( 80 ) - 40;
    var_8 = var_4 * cos( var_7 ) * var_6;
    return var_2 + var_8 + var_5 * sin( var_7 ) * var_6;
}

callstrike_playmultitracerfx( var_0, var_1, var_2, var_3 )
{
    self endon( "death" );
    var_4 = 0;
    var_5 = 3;

    while ( var_4 < var_5 )
    {
        var_6 = randomintrange( 25, 50 );
        var_7 = randomintrange( 25, 50 );
        playfx( var_0, var_1 + ( var_6, var_7, 0 ), var_2, var_3 );
        var_4++;
        wait 0.05;
    }
}

moveanddamagepoint( var_0, var_1 )
{
    self endon( "death" );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( 0.18 );
    self.origin = var_1;
    self setscriptablepartstate( "explode" + var_0, "active", 0 );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( 5 );
    self setscriptablepartstate( "explode" + var_0, "neutral", 0 );
}

callstrike_fuelbombeffect( var_0, var_1, var_2, var_3, var_4 )
{
    var_0 endon( "death" );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_1 );

    if ( !isdefined( var_4 ) )
        return;

    var_5 = var_0.flightdir;

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "airstrike", "addSpawnDangerZone" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "airstrike", "addSpawnDangerZone" ) ]]( var_3, 650, 650, var_4.team, var_2, var_4, 1 );

    var_7 = var_3 + ( 0, 0, 2500 );
    var_8 = var_3 - ( 0, 0, 10000 );
    var_9 = scripts\engine\trace::ray_trace( var_7, var_8, undefined, scripts\engine\trace::create_contents( 0, 1, 0, 1, 0, 1, 0 ) );
    var_10 = var_9["position"];
    var_11 = var_9["normal"];
    var_12 = var_10 + var_11 * 10;
    var_13 = spawn( "script_model", var_12 + ( 0, 0, 400 ) );
    var_13 setmodel( "ks_fuelstrike_mp" );
    var_13 setscriptablepartstate( "release", "on", 0 );
    var_14 = spawn( "script_model", var_12 );
    var_14 setmodel( "ks_fuelstrike_mp" );
    var_14 setscriptablepartstate( "ignite", "on", 0 );
    var_14 setentityowner( var_4 );
    level thread delaydeletefxents( var_13, var_14 );
}

delaydeletefxents( var_0, var_1 )
{
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( 10 );

    if ( isdefined( var_0 ) )
        var_0 delete();

    if ( isdefined( var_1 ) )
        var_1 delete();
}

getflightpath( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    var_9 = undefined;

    if ( istrue( var_8 ) )
        var_9 = var_1;
    else
        var_9 = anglestoforward( var_1 );

    var_10 = var_0 + var_9 * ( -1 * var_2 );

    if ( isdefined( var_3 ) )
        var_10 = var_10 * ( 1, 1, 0 );

    var_10 = var_10 + ( 0, 0, var_4 );
    var_11 = var_0 + var_9 * var_2;

    if ( isdefined( var_3 ) )
        var_11 = var_11 * ( 1, 1, 0 );

    var_11 = var_11 + ( 0, 0, var_4 );
    var_12 = length( var_10 - var_11 );
    var_13 = var_12 / var_5;
    var_12 = abs( var_12 / 2 + var_6 );
    var_14 = var_12 / var_5;
    var_15["startPoint"] = var_10;
    var_15["endPoint"] = var_11;
    var_15["bombTime"] = var_14;
    var_15["flyTime"] = var_13;
    var_15["directionAngles"] = var_9;
    return var_15;
}

getexplodedistance( var_0 )
{
    var_1 = 850;
    var_2 = 1500;
    var_3 = var_1 / var_0;
    var_4 = var_3 * var_2;
    return var_4;
}

airstrike_getownerlookatpos( var_0, var_1 )
{
    var_2 = [ "physicscontents_clipshot", "physicscontents_missileclip", "physicscontents_solid", "physicscontents_vehicleclip" ];
    var_3 = physics_createcontents( var_2 );
    var_4 = var_0 getvieworigin();
    var_5 = var_4 + anglestoforward( var_0 getplayerangles() ) * 50000;
    var_6 = var_0 scripts\cp_mp\utility\killstreak_utility::playerkillstreakgetownerlookatignoreents();
    var_7 = scripts\engine\trace::ray_trace( var_4, var_5, var_6, var_3 );
    var_8 = var_7["position"];

    if ( var_7["hittype"] == "hittype_none" )
        var_8 = undefined;

    return var_8;
}

airstrike_watchforads( var_0, var_1 )
{
    self endon( "death_or_disconnect" );
    self endon( "deploy_cancelled" );
    self endon( "deploy_fired" );
    var_2 = spawn( "script_model", self.origin );
    var_2 setmodel( "ks_airstrike_marker_mp" );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "game", "requestObjectiveID" ) )
        var_2.objidnum = [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "game", "requestObjectiveID" ) ]]( 99 );

    var_2 setotherent( self );
    var_2 dontinterpolate();
    var_2 hide();
    var_3 = "icon_waypoint_airstrike";

    if ( isdefined( var_1 ) )
        var_3 = var_1;

    var_2 airstrike_setmarkerobjective( var_2.objidnum, var_3, self, 50 );
    var_2 thread airstrike_watchownerdisown( self );
    var_2 thread airstrike_watchdeployended( self );
    var_2 thread airstrike_watchdeployweaponchange( self );
    var_2.updatemarker = 0;
    scripts\common\utility::allow_fire( 0 );

    for (;;)
    {
        if ( scripts\cp_mp\emp_debuff::is_empd() && istrue( var_2.updatemarker ) )
        {
            scripts\common\utility::allow_fire( 0 );
            var_2 hide();
            var_2 setscriptablepartstate( "marker_scope", "off", 0 );
            self notify( "stop_update_marker" );
            var_2.updatemarker = 0;
        }

        var_4 = self playerads();

        if ( var_4 == 1 && !istrue( var_2.updatemarker ) )
        {
            if ( !scripts\cp_mp\emp_debuff::is_empd() )
            {
                scripts\common\utility::allow_fire( 1 );
                var_2 show();
                var_2 setscriptablepartstate( "marker_scope", "on", 0 );
                var_2 thread airstrike_updatemarkerpos( self );
                var_2.updatemarker = 1;
            }
        }
        else if ( var_4 < 1 && istrue( var_2.updatemarker ) )
        {
            scripts\common\utility::allow_fire( 0 );
            var_2 hide();
            var_2 setscriptablepartstate( "marker_scope", "off", 0 );
            self notify( "stop_update_marker" );
            var_2.updatemarker = 0;
        }

        waitframe();
    }
}

airstrike_setmarkerobjective( var_0, var_1, var_2, var_3 )
{
    objective_icon( var_0, var_1 );
    objective_showtoplayersinmask( var_0 );
    objective_addclienttomask( var_0, var_2 );
    objective_onentity( var_0, self );
    objective_setzoffset( var_0, var_3 );
    objective_setplayintro( var_0, 0 );
    objective_setplayoutro( var_0, 0 );
    objective_setbackground( var_0, 1 );

    if ( level.teambased )
        objective_setownerteam( var_0, var_2.team );
    else
        objective_setownerclient( var_0, var_2 );

    objective_state( var_0, "done" );
}

airstrike_updatemarkerpos( var_0 )
{
    self endon( "death" );
    var_0 endon( "deploy_cancelled" );
    var_0 endon( "deploy_fired" );
    var_0 endon( "stop_update_marker" );
    var_0 endon( "death_or_disconnect" );
    var_1 = 0;
    var_0 setclientomnvar( "ui_spotter_scope_danger", 0 );

    for (;;)
    {
        var_2 = airstrike_getownerlookatpos( var_0 );
        var_3 = -1;
        var_4 = -1;
        var_5 = -1;

        if ( isdefined( var_2 ) )
        {
            self.origin = var_2;
            var_3 = int( self.origin[0] );
            var_4 = int( self.origin[1] );
            var_5 = int( self.origin[2] );
        }

        var_0 setclientomnvar( "ui_ac130_coord3_posx", var_3 );
        var_0 setclientomnvar( "ui_ac130_coord3_posy", var_4 );
        var_0 setclientomnvar( "ui_ac130_coord3_posz", var_5 );

        if ( isdefined( var_2 ) )
        {
            if ( !istrue( var_1 ) && distance2dsquared( var_0.origin, var_2 ) <= 1638400 )
            {
                var_0 setclientomnvar( "ui_spotter_scope_danger", 1 );
                var_1 = 1;
            }
            else if ( istrue( var_1 ) && distance2dsquared( var_0.origin, var_2 ) > 1638400 )
            {
                var_0 setclientomnvar( "ui_spotter_scope_danger", 0 );
                var_1 = 0;
            }
        }

        waitframe();
    }
}

airstrike_watchownerdisown( var_0 )
{
    self endon( "death" );
    level endon( "game_ended" );
    var_0 waittill( "death_or_disconnect" );
    airstrike_removemarker();
}

airstrike_watchdeployended( var_0 )
{
    var_0 endon( "death_or_disconnect" );
    self endon( "death" );
    level endon( "game_ended" );
    var_1 = var_0 scripts\engine\utility::waittill_any_return_2( "cancel_fire", "successful_fire" );

    if ( isdefined( var_1 ) && var_1 == "successful_fire" )
    {
        var_0 notify( "deploy_fired" );
        self setscriptablepartstate( "marker_scope", "off", 0 );
        var_2 = anglestoforward( var_0 getplayerangles() );
        var_3 = self.origin - var_2 * 500;
        var_4 = self.origin + var_2 * 20;
        var_5 = scripts\engine\trace::ray_trace( var_3, var_4, self );
        var_6 = var_5["normal"];
        self.angles = generateaxisanglesfromupvector( var_6, self.angles );
        self setscriptablepartstate( "marker_placed", "on", 0 );
        objective_state( self.objidnum, "current" );
        thread airstrike_removemarker( 7 );
    }
    else
    {
        var_0 notify( "deploy_cancelled" );

        if ( !var_0 [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "player", "isPlayerADS" ) ]]() )
            var_0 scripts\common\utility::allow_fire( 1 );

        airstrike_removemarker();
    }
}

airstrike_watchdeployweaponchange( var_0 )
{
    var_0 endon( "death_or_disconnect" );
    self endon( "death" );
    level endon( "game_ended" );
    var_1 = var_0 getcurrentweapon();

    for (;;)
    {
        if ( var_0 getcurrentweapon() != var_1 )
            break;

        waitframe();
    }

    var_0 notify( "cancel_fire" );
}

airstrike_removemarker( var_0 )
{
    if ( isdefined( var_0 ) )
    {
        self endon( "death" );
        level endon( "game_ended" );
        scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_0 );
    }

    if ( isdefined( self.objidnum ) )
    {
        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "game", "returnObjectiveID" ) )
            [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "game", "returnObjectiveID" ) ]]( self.objidnum );
    }

    self delete();
}

airstrike_delayplayscriptable( var_0 )
{
    self endon( "death" );
    level endon( "game_ended" );
    wait( var_0 );
    self setscriptablepartstate( "bodyfx", "on", 0 );
}

airstrike_killcammove( var_0, var_1, var_2 )
{
    self endon( "death" );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( var_0 );
    self moveto( var_1, 4 );
    scripts\cp_mp\hostmigration::hostmigration_waitlongdurationwithpause( 3.95 );
    self moveto( var_2, 5 );
}

airstrike_watchgameend( var_0 )
{
    self endon( "airstrike_finished" );
    self endon( "disconnect" );
    level waittill( "game_ended" );
    scripts\cp_mp\utility\killstreak_utility::recordkillstreakendstats( var_0 );
}
