// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

br_armor_plate_used()
{
    var_0 = scripts\mp\equipment::getequipmentslotammo( "health" );

    if ( var_0 <= 0 )
        return;

    if ( self isparachuting() )
    {
        self notify( "br_try_armor_cancel" );
        return;
    }

    if ( isdefined( self.armorqueued ) )
        self.armorqueued--;

    var_1 = self.br_armorhealth + 5;
    var_2 = clamp( var_1, 0, self.br_maxarmorhealth );
    var_3 = max( 1, getdvarint( "scr_br_armor_heal_amount", 50 ) );
    var_2 = int( var_2 / var_3 ) * var_3 + var_3;
    self.br_armorhealth = clamp( var_2, 0, self.br_maxarmorhealth );
    var_4 = self.br_armorhealth / self.br_maxarmorhealth;
    var_5 = int( var_4 * 100 );
    scripts\mp\gametypes\br_public::updatebrscoreboardstat( "armorHealthRatio", int( self.br_armorhealth ) );
    scripts\mp\equipment::decrementequipmentslotammo( "health", 1 );
    scripts\cp_mp\challenges::onuseitem( "armor_plate" );
    self notify( "armor_plate_inserted" );
    self scripts\mp\equipment\adrenaline::useadrenaline( );
}

br_armor_plate_broken_remove()
{
    var_0 = self.br_armorhealth + 5;
    var_1 = clamp( var_0, 0, self.br_maxarmorhealth );
    var_2 = max( 1, getdvarint( "scr_br_armor_heal_amount", 50 ) );
    var_1 = int( var_1 / var_2 ) * var_2;
    var_3 = clamp( var_1, 0, self.br_maxarmorhealth );

    if ( var_3 >= self.br_armorhealth )
        return;
    else
        self.br_armorhealth = var_3;

    var_4 = self.br_armorhealth / self.br_maxarmorhealth;
    var_5 = int( var_4 * 100 );
    scripts\mp\gametypes\br_public::updatebrscoreboardstat( "armorHealthRatio", int( self.br_armorhealth ) );
}

br_use_armor_plate( var_0, var_1 )
{
    self endon( "disconnect" );

    if ( var_1 == 0 )
        return;
    else if ( istrue( self.insertingarmorplate ) )
        return;
    else if ( self isswitchingweapon() )
        return;

    if ( !br_is_allowed_armor_insert() )
        return;

    var_2 = makeweapon( "armor_plate_deploy_mp" );
    var_3 = scripts\cp_mp\utility\killstreak_utility::createstreakinfo( "", self );
    var_3.armorweapon = var_2;
    br_toggle_armor_allows( 1 );
    thread br_watch_armor_cancel_notifys();
    var_4 = scripts\cp_mp\killstreaks\killstreakdeploy::switchtodeployweapon( var_2, var_3, ::br_insert_armor, undefined, undefined, undefined, undefined, 0 );
}

br_watch_armor_cancel_notifys()
{
    self endon( "br_armor_repair_end" );
    self endon( "disconnect" );
    br_add_player_commands();
    thread br_watch_armor_weapon();
    self.stoparmorinsert = 0;
    scripts\engine\utility::waittill_any_6( "death", "last_stand_start", "br_try_armor_cancel", "br_armor_plate_done" );
    self.stoparmorinsert = 1;
    thread br_armor_repair_end();
}

br_watch_armor_weapon()
{
    self endon( "disconnect" );
    self endon( "br_armor_repair_end" );

    while ( isdefined( self.currentweapon ) && isdefined( self.currentweapon.basename ) && self.currentweapon.basename != "armor_plate_deploy_mp" )
    {
        if ( self isonladder() )
            self notify( "br_try_armor_cancel" );

        waitframe();
    }

    while ( isdefined( self.currentweapon ) && isdefined( self.currentweapon.basename ) && self.currentweapon.basename == "armor_plate_deploy_mp" )
    {
        if ( self isonladder() )
            self notify( "br_try_armor_cancel" );

        waitframe();
    }

    self notify( "br_try_armor_cancel" );
}

br_toggle_armor_allows( var_0 )
{
    scripts\common\utility::allow_melee( !var_0 );
    scripts\common\utility::allow_killstreaks( !var_0 );
    scripts\common\utility::allow_crate_use( !var_0 );
    scripts\mp\equipment::allow_equipment( !var_0 );
    scripts\common\utility::allow_offhand_weapons( !var_0 );
    scripts\common\utility::allow_offhand_throwback( !var_0 );
    self.insertingarmorplate = var_0;
}

br_insert_armor( var_0 )
{
    self endon( "disconnect" );
    self endon( "br_armor_repair_end" );

    if ( !br_is_allowed_armor_insert() || istrue( self.stoparmorinsert ) )
        return;

    var_1 = gettime();
    var_2 = var_1 + 1860.0;
    var_3 = 2000.0;
    var_4 = 1860.0;

    for ( var_5 = 0; var_1 < var_2; var_1 = gettime() )
    {
        if ( !isdefined( var_0.armorweapon ) || var_0.armorweapon != self getcurrentweapon() )
            return;

        waitframe();
    }

    br_armor_plate_used();
    var_6 = ( var_3 - var_4 ) / 1000;
    wait( var_6 );

    while ( br_should_continue_adding_armor() )
    {
        var_7 = self.equipment["health"];
        var_8 = scripts\mp\equipment::getequipmentslotammo( "health" );

        if ( isdefined( var_7 ) && isdefined( var_8 ) && var_8 > 0 && self.br_armorhealth < self.br_maxarmorhealth )
        {
            var_9 = gettime() + 1250.0;

            while ( gettime() < var_9 )
            {
                if ( !isdefined( var_0.armorweapon ) || var_0.armorweapon != self getcurrentweapon() )
                    return;

                waitframe();
            }

            br_armor_plate_used();
            var_10 = 0.25;
            wait( var_10 );
            continue;
        }

        break;
    }

    self notify( "br_armor_plate_done" );
}

br_is_allowed_armor_insert()
{
    if ( isdefined( self.vehicle ) )
    {
        var_0 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getoccupantseat( self.vehicle, self );

        if ( var_0 == "driver" )
            return 0;
    }

    if ( self isparachuting() )
        return 0;
    else if ( istrue( self.revivingteammate ) )
        return 0;
    else if ( scripts\mp\supers::issuperinuse() && self.super.staticdata.ref != "super_deadsilence" )
        return 0;

    if ( self.br_armorhealth == self.br_maxarmorhealth )
    {
        scripts\mp\hud_message::showerrormessage( level.br_pickups.br_pickupdenyarmorfull );
        return 0;
    }

    return 1;
}

br_should_continue_adding_armor()
{
    var_0 = scripts\engine\utility::is_player_gamepad_enabled() && self getclientomnvar();
    var_1 = isdefined( self.armorqueued ) && self.armorqueued > 0;
    return var_0 || var_1;
}

br_add_player_commands()
{
    self notifyonplayercommand( "br_try_armor_cancel", "+weapnext" );
    self notifyonplayercommand( "br_try_armor_cancel", "+weapprev" );
    self notifyonplayercommand( "br_try_armor_cancel", "+attack" );
    self notifyonplayercommand( "br_try_armor_cancel", "+smoke" );
    self notifyonplayercommand( "br_try_armor_cancel", "+frag" );
    self notifyonplayercommand( "br_try_armor_cancel", "+melee_zoom" );
}

br_remove_player_commands()
{
    self notifyonplayercommandremove( "br_try_armor_cancel", "+weapnext" );
    self notifyonplayercommandremove( "br_try_armor_cancel", "+weapprev" );
    self notifyonplayercommandremove( "br_try_armor_cancel", "+attack" );
    self notifyonplayercommandremove( "br_try_armor_cancel", "+smoke" );
    self notifyonplayercommandremove( "br_try_armor_cancel", "+frag" );
    self notifyonplayercommandremove( "br_try_armor_cancel", "+melee_zoom" );
}

br_armor_repair_end()
{
    self endon( "disconnect" );
    self notify( "br_armor_repair_end" );
    br_remove_player_commands();

    while ( isdefined( self.currentweapon ) && isdefined( self.currentweapon.basename ) && self.currentweapon.basename == "armor_plate_deploy_mp" )
        waitframe();

    waitframe();

    if ( istrue( self.armorqueued ) )
        self.armorqueued = 0;

    br_toggle_armor_allows( 0 );
}
