// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    level.br_armory_kiosk = spawnstruct();
    level.br_armory_kiosk.scriptables = [];
    level.br_armory_kiosk_enabled = getdvarint( "scr_br_armory_kiosk", 1 ) != 0;

    if ( scripts\mp\gametypes\br_gametypes::isfeaturedisabled( "kiosk" ) )
    {
        level.br_armory_kiosk_enabled = 0;
        return;
    }

    if ( level.br_armory_kiosk_enabled )
    {
        scripts\engine\scriptable::scriptable_addusedcallbackbypart( "br_plunder_box", ::armorykioskused );
        scripts\mp\utility\lui_game_event_aggregator::registeronluieventcallback( ::onarmorykioskpurchase );
        _initsalesdiscount();
        _parsepurchaseitemtables();
        level thread _watchforcircleclosure();
    }
}

_initignoredtabspergamemode()
{
    if ( getdvar( "scr_br_gametype", "" ) == "dmz" )
        setdvar( "br_kiosk_ignored_tab_nums", "2,5" );
    else
        setdvar( "br_kiosk_ignored_tab_nums", "3,4,5" );
}

_initsalesdiscount()
{
    var_0 = getdvarint( "br_kiosk_sales_discount", 0 );
    level.br_armory_kiosk.sales_discount = int( clamp( var_0, 0, 100 ) );
    var_1 = getdvar( "br_kiosk_sales_discount_items", "" );
    level.br_armory_kiosk.sales_discount_items = strtok( var_1, "," );
    var_2 = 20;
    var_3 = level.br_armory_kiosk.sales_discount % var_2;

    if ( var_3 > 0 )
    {
        var_4 = int( floor( level.br_armory_kiosk.sales_discount / var_2 ) * var_2 );
        var_5 = var_3 / var_2 >= 0.5;

        if ( var_5 )
            var_4 = var_4 + var_2;

        level.br_armory_kiosk.sales_discount = int( var_4 );
    }

    if ( var_0 != level.br_armory_kiosk.sales_discount )
        setdvar( "br_kiosk_sales_discount", level.br_armory_kiosk.sales_discount );
}

_applysalesdiscount( var_0, var_1 )
{
    if ( var_1 == 0 )
        return var_0;
    else if ( var_1 == 100 )
        return 0;

    var_2 = ( 100 - var_1 ) * 0.01;
    return int( floor( var_0 * var_2 + 0.5 ) );
}

_parsepurchaseitemtables()
{
    var_0 = "mp/brKioskPurchases.csv";

    if ( getdvar( "scr_br_gametype", "" ) == "dmz" )
        var_0 = "mp/brKioskPurchases.csv";

    var_1 = 0;
    var_2 = 1;
    var_3 = 2;
    var_4 = 3;
    var_5 = 9;
    var_6 = 10;
    level.br_armory_kiosk.items = [];
    var_7 = tablelookupgetnumrows( var_0 );

    for ( var_8 = 0; var_8 < var_7; var_8++ )
    {
        var_9 = int( tablelookupbyrow( var_0, var_8, var_1 ) );
        var_10 = spawnstruct();
        var_10.type = tablelookupbyrow( var_0, var_8, var_2 );
        var_10.ref = tablelookupbyrow( var_0, var_8, var_3 );
        var_10.cost = int( tablelookupbyrow( var_0, var_8, var_4 ) );
        var_10.firesalediscount = int( tablelookupbyrow( var_0, var_8, var_5 ) );
        var_10.perkdiscount = int( tablelookupbyrow( var_0, var_8, var_6 ) );

        if ( var_10.ref == "supply_drop" )
        {
            var_11 = getdvarint( "scr_br_kiosk_supdropcost", 0 );

            if ( var_11 != 0 )
                var_10.cost = var_11;
        }

        if ( level.br_armory_kiosk.sales_discount > 0 )
        {
            var_12 = level.br_armory_kiosk.sales_discount_items.size == 0 || scripts\engine\utility::array_contains( level.br_armory_kiosk.sales_discount_items, var_10.ref );

            if ( var_12 )
                var_10.cost = _applysalesdiscount( var_10.cost, level.br_armory_kiosk.sales_discount );
        }

        if ( var_10.type == "loadout_default" )
        {
            level.br_armory_kiosk.loadoutdefaultcost = var_10.cost;
            level.br_armory_kiosk.loadoutdefaultfiresalediscount = var_10.firesalediscount;
            level.br_armory_kiosk.loadoutdefaultperkdiscount = var_10.perkdiscount;
            continue;
        }

        if ( var_10.type == "loadout_custom" )
        {
            level.br_armory_kiosk.loadoutcustomcost = var_10.cost;
            level.br_armory_kiosk.loadoutcustomfiresalediscount = var_10.firesalediscount;
            level.br_armory_kiosk.loadoutcustomperkdiscount = var_10.perkdiscount;
            continue;
        }

        if ( var_10.type == "teamrevive" )
        {
            level.br_armory_kiosk.teamrevivecost = var_10.cost;
            level.br_armory_kiosk.teamrevivefiresalediscount = var_10.firesalediscount;
            level.br_armory_kiosk.teamreviveperkdiscount = var_10.perkdiscount;
            continue;
        }

        level.br_armory_kiosk.items[var_9] = var_10;
    }
}

_getactualcost( var_0, var_1, var_2, var_3, var_4 )
{
    if ( var_1 )
        return _applysalesdiscount( var_0, var_2 );
    else if ( var_3 )
        return _applysalesdiscount( var_0, var_4 );

    return var_0;
}

_watchforcircleclosure()
{
    level endon( "game_ended" );
    setdvarifuninitialized( "scr_br_disable_kiosk_by_circle", 0 );

    for (;;)
    {
        level waittill( "br_circle_set" );
        var_0 = getdvarint( "scr_br_disable_kiosk_by_circle", 0 );

        if ( var_0 == 0 )
            continue;

        if ( level.br_circle.circleindex + 1 >= var_0 )
        {
            // disableallarmorykiosks();

            foreach ( var_2 in level.players )
            {
                if ( !isdefined( var_2 ) || !isalive( var_2 ) )
                    continue;

                var_2 thread scripts\mp\hud_message::showsplash( "br_kiosks_disabled" );
            }

            break;
        }
    }
}

showdiscountsplash( var_0 )
{
    var_1 = self;
    var_1 endon( "disconnect" );
    level endon( "game_ended" );

    if ( istrue( var_1.hasseendiscountsplash ) )
        return;

    if ( !isdefined( level.br_armory_kiosk.sales_discount ) )
        return;

    if ( level.br_armory_kiosk.sales_discount == 0 )
        return;

    var_1.hasseendiscountsplash = 1;

    if ( isdefined( var_0 ) && var_0 > 0 )
        wait( var_0 );

    if ( level.br_armory_kiosk.sales_discount_items.size == 0 )
        var_1 thread scripts\mp\hud_message::showsplash( "br_sales_event_all" );
    else
        var_1 thread scripts\mp\hud_message::showsplash( "br_sales_event_selective" );
}

onprematchdone()
{
    foreach ( var_1 in level.br_armory_kiosk.scriptables )
    {
        var_1 setscriptablepartstate( "br_plunder_box", "visible" );
        var_1.visible = 1;
    }
}

dangercircletick()
{
}

disableallarmorykiosks()
{
    foreach ( var_1 in level.br_armory_kiosk.scriptables )
    {
        if ( isdefined( var_1.visible ) )
            disablearmorykiosk( var_1 );
    }
}

disablearmorykiosk( var_0 )
{
    var_0 setscriptablepartstate( "br_plunder_box", "disabled" );
    var_0.visible = undefined;
    var_0.disabled = 1;

    if ( var_0 scripts\mp\gametypes\br_quest_util::checkforactiveobjicon() )
        var_0 scripts\mp\gametypes\br_quest_util::deletequestobjicon();
}

getallspawninstances()
{
    if ( !level.br_armory_kiosk_enabled )
        return;

    var_0 = getentitylessscriptablearray( "scriptable_br_plunder_box", "classname" );
    return var_0;
}

setspawninstances( var_0 )
{
    level.br_armory_kiosk.scriptables = var_0;
}

armorykioskused( var_0, var_1, var_2, var_3, var_4 )
{
    if ( istrue( level.gameended ) )
        return;

    if ( !var_3 scripts\cp_mp\utility\player_utility::_isalive() || istrue( var_3.inlaststand ) )
        return;

    if ( var_3 scripts\cp_mp\utility\player_utility::isusingremote() )
        return;

    if ( var_3 scripts\cp_mp\utility\player_utility::isinvehicle() )
        return;

    if ( istrue( var_3.insertingarmorplate ) )
        var_3 notify( "br_try_armor_cancel" );

    if ( var_2 == "visible" )
    {
        var_0 setscriptablepartstate( "br_plunder_box", "opening" );
        var_0 thread kioskfixupproneplayers();
        var_3 thread _runpurchasemenu( var_0 );
    }
    else if ( var_2 == "opening" || var_2 == "open" )
        var_3 thread _runpurchasemenu( var_0 );
}

kioskfixupproneplayers()
{
    if ( !getdvarint( "scr_br_kiosk_fix_prone_players", 1 ) )
        return;

    var_0 = getdvarfloat( "scr_br_kiosk_fix_prone_players_radius", 300 );
    var_1 = sortbydistancecullbyradius( level.players, self.origin, var_0 );

    foreach ( var_3 in var_1 )
    {
        if ( !isdefined( var_3 ) || !isalive( var_3 ) )
            continue;

        if ( var_3 getstance() != "prone" )
            continue;

        var_4 = var_3 getboundshalfsize();
        var_0 = var_4[0];
        var_5 = 2.0 * var_4[2];

        if ( capsuletracepassed( var_3.origin, var_0, var_5, undefined, 0, 0 ) )
            continue;

        var_3 setstance( "crouch", 1 );
    }
}

kiosksetupfiresaleforplayer( var_0, var_1 )
{
    if ( !isdefined( var_0.firesaleforplayers ) )
        var_0.firesaleforplayers = [ var_1 ];
    else if ( !scripts\engine\utility::array_contains( var_0.firesaleforplayers, var_1 ) )
        var_0.firesaleforplayers = scripts\engine\utility::array_add( var_0.firesaleforplayers, var_1 );

    if ( !var_0 scripts\mp\gametypes\br_quest_util::checkforactiveobjicon() )
        var_0 scripts\mp\gametypes\br_quest_util::createquestobjicon( "ui_mp_br_mapmenu_icon_poi_plunder_box_firesale", "active", var_0.origin );

    var_0 scripts\mp\gametypes\br_quest_util::showquestobjicontoplayer( var_1 );
}

iskioskfiresaleactiveforplayer( var_0, var_1 )
{
    if ( scripts\mp\gametypes\br_publicevents::ispubliceventoftypeactive( 2 ) )
        return 1;

    if ( !isdefined( var_0.firesaleforplayers ) )
        return 0;

    return scripts\engine\utility::array_contains( var_0.firesaleforplayers, var_1 );
}

kioskfiresaledoneforplayer( var_0, var_1 )
{
    if ( !isdefined( var_0.firesaleforplayers ) )
        return;

    var_0 scripts\mp\gametypes\br_quest_util::hidequestobjiconfromplayer( var_1 );
    var_0.firesaleforplayers = scripts\engine\utility::array_remove( var_0.firesaleforplayers, var_1 );
}

getkioskyawoffsetoverride()
{
    return 180.0 + randomfloatrange( -10.0, 10.0 );
}

_runpurchasemenu( var_0 )
{
    var_1 = self;
    level endon( "game_ended" );
    var_1 endon( "disconnect" );
    var_1 endon( "death" );
    var_1.br_kiosk = var_0;

    if ( scripts\mp\gametypes\br_public::isbotpracticematch() )
        var_1 notify( "kiosk_used" );

    var_2 = iskioskfiresaleactiveforplayer( var_0, var_1 );
    var_3 = var_1 scripts\mp\utility\perk::_hasperk( "specialty_br_cheaper_kiosk" );
    var_1 setclientomnvar( "ui_br_purchase_killstreak_response", 0 );

    if ( var_2 )
        var_1 setclientomnvar( "ui_br_open_purchase_killstreak", 2 );
    else if ( var_3 )
        var_1 setclientomnvar( "ui_br_open_purchase_killstreak", 3 );
    else
        var_1 setclientomnvar( "ui_br_open_purchase_killstreak", 1 );

    var_1.armorykioskpurchaseallowed = 1;
    scripts\mp\gametypes\br_analytics::branalytics_kiosk_menu_event( var_1, "menu_open" );
    var_1 thread _watchtoautoclosemenu( var_0 );
    var_1 setsoundsubmix( "iw8_br_plunder_kiosk_menu" );
}

_closepurchasemenuwithresponse( var_0 )
{
    var_1 = self;
    var_1 setclientomnvar( "ui_br_purchase_killstreak_response", var_0 );
    var_1 setclientomnvar( "ui_br_open_purchase_killstreak", 0 );
    var_1 clearsoundsubmix( "iw8_br_plunder_kiosk_menu" );
    var_1.br_kiosk = undefined;
    var_1.armorykioskpurchaseallowed = undefined;
    scripts\mp\gametypes\br_analytics::branalytics_kiosk_menu_event( var_1, "menu_close", "reason: " + var_0 );
}

_purchasemenuclosedbyclient( var_0 )
{
    var_0 _closepurchasemenuwithresponse( 0 );
    var_0 notify( "_watchToAutoCloseMenu_end" );
}

_watchtoautoclosemenu( var_0 )
{
    var_1 = self;
    var_1 endon( "disconnect" );
    var_1 notify( "_watchToAutoCloseMenu_end" );
    var_1 endon( "_watchToAutoCloseMenu_end" );
    var_1 childthread _proximitywatcher( var_0 );
    scripts\engine\utility::waittill_any_ents( var_1, "death", var_1, "last_stand_start", var_1, "pushed_too_far", level, "game_ended" );
    var_1 _closepurchasemenuwithresponse( 2 );
}

_proximitywatcher( var_0 )
{
    var_1 = self;
    var_2 = 64;
    var_3 = getdvarfloat( "MLLSRQSRT", 128 ) + var_2;
    var_4 = var_3 * var_3;

    for (;;)
    {
        wait 0.1;
        var_5 = distancesquared( var_1.origin, var_0.origin );

        if ( var_5 > var_4 )
        {
            var_1 notify( "pushed_too_far" );
            break;
        }
    }
}

_getequipmentammotomax( var_0 )
{
    var_1 = self;

    if ( !isdefined( var_0 ) )
        return 0;

    var_2 = var_1 scripts\mp\equipment::getequipmentammo( var_0 );
    var_3 = var_1 scripts\mp\equipment::getequipmentmaxammo( var_0 );
    return max( 0, var_3 - var_2 );
}

_maxoutequipmentammo( var_0 )
{
    var_1 = self;

    if ( !isdefined( var_0 ) )
        return 0;

    var_2 = var_1 scripts\mp\equipment::getequipmentammo( var_0 );
    var_3 = var_1 scripts\mp\equipment::getequipmentmaxammo( var_0 );

    if ( var_2 < var_3 )
        var_1 scripts\mp\equipment::setequipmentammo( var_0, var_3 );
}

_findgivearmoramountanddropleftovers( var_0, var_1 )
{
    var_2 = self;
    var_3 = var_2 scripts\mp\equipment::getequipmentslotammo( "health" );

    if ( !isdefined( var_3 ) )
        var_3 = 0;

    var_4 = var_2 scripts\mp\equipment::getequipmentmaxammo( "equip_armorplate" );

    if ( getdvarint( "scr_br_alt_mode_gg", 0 ) )
        var_5 = 2;
    else
        var_5 = 5;

    var_6 = int( clamp( var_5, 0, var_4 - var_3 ) );
    var_7 = var_5 - var_6;

    if ( var_7 > 0 && !istrue( var_1 ) )
    {
        var_8 = undefined;

        if ( istrue( var_0 ) )
            var_8 = getkioskyawoffsetoverride();

        [var_10, var_11, var_12] = scripts\mp\gametypes\br_pickups::getitemdroporiginandangles( 0, var_2.origin, var_2.angles, var_2, var_8 );
        scripts\mp\gametypes\br_pickups::spawnpickup( "brloot_armor_plate", var_10, var_11, var_7, 1, var_12 );
    }

    return var_6;
}

_validateitempurchase( var_0, var_1 )
{
    var_2 = self;
    var_3 = iskioskfiresaleactiveforplayer( var_2.br_kiosk, var_2 );
    var_4 = var_2 scripts\mp\utility\perk::_hasperk( "specialty_br_cheaper_kiosk" );
    var_5 = _getactualcost( var_0.cost, var_3, var_0.firesalediscount, var_4, var_0.perkdiscount );

    if ( !isdefined( var_2.plundercount ) )
        var_2.plundercount = 0;

    if ( var_2.plundercount < var_5 )
    {
        var_2 _closepurchasemenuwithresponse( 3 );
        return 0;
    }

    if ( var_0.type == "killstreak" )
    {
        if ( !istrue( var_1 ) )
        {
            if ( var_2 scripts\mp\gametypes\br_pickups::haskillstreak( var_0.ref ) )
            {
                var_2 _closepurchasemenuwithresponse( 4 );
                return 0;
            }
        }
    }
    else if ( var_0.type == "fieldupgrade" )
    {
        if ( var_2 scripts\mp\supers::issuperinuse() )
        {
            var_2 _closepurchasemenuwithresponse( 6 );
            return 0;
        }

        if ( !istrue( var_1 ) )
        {
            var_6 = var_2 scripts\mp\supers::getcurrentsuperref();

            if ( isdefined( var_6 ) && var_0.ref == var_6 )
            {
                var_2 _closepurchasemenuwithresponse( 5 );
                return 0;
            }
        }
    }
    else if ( var_0.type == "special" )
    {
        switch ( var_0.ref )
        {
            case "armor_bundle":
            case "armor":
                break;
            case "gas_mask":
                var_7 = spawnstruct();
                var_7.scriptablename = "brloot_equip_gasmask";
                var_8 = scripts\mp\gametypes\br_pickups::cantakepickup( var_7 );
                break;
            case "ammo_refill":
                var_9 = 0;

                if ( var_2 _getequipmentammotomax( var_2.equipment["primary"] ) > 0 )
                    var_9 = 1;
                else if ( var_2 _getequipmentammotomax( var_2.equipment["secondary"] ) > 0 )
                    var_9 = 1;
                else if ( !var_2 scripts\mp\gametypes\br_weapons::br_ammo_player_is_maxed_out() )
                    var_9 = 1;

                if ( !var_9 )
                {
                    var_2 _closepurchasemenuwithresponse( 8 );
                    return 0;
                }

                break;
            case "respawn_token":
                if ( scripts\mp\gametypes\br_pickups::respawntokendisabled() )
                {
                    var_2 _closepurchasemenuwithresponse( 9 );
                    return 0;
                }

                if ( istrue( var_2.hasrespawntoken ) )
                {
                    var_2 _closepurchasemenuwithresponse( 10 );
                    return 0;
                }

                break;
            case "self_revive_token":
                if ( var_2 scripts\mp\gametypes\br_public::hasselfrevivetoken() )
                {
                    var_2 _closepurchasemenuwithresponse( 10 );
                    return 0;
                }

                break;
            case "supply_drop":
                var_7 = spawnstruct();
                var_7.scriptablename = "brloot_offhand_advancedsupplydrop";
                var_7.count = 1;
                var_8 = scripts\mp\gametypes\br_pickups::cantakepickup( var_7 );

                if ( var_8 != 1 )
                {
                    var_2 _closepurchasemenuwithresponse( 7 );
                    return 0;
                }

                break;
        }
    }

    return 1;
}

_killstreakneedslocationselection( var_0 )
{
    switch ( var_0 )
    {
        case "precision_airstrike":
        case "toma_strike":
            return 1;
        case "uav":
            return 0;
        default:
            return 0;
    }
}

_locationselectioninterrupt()
{
    var_0 = self;
    scripts\engine\utility::waittill_any_ents( var_0, "death", level, "game_ended" );
    var_0 notify( "cancel_location" );
}

_handlekillstreakpurchase( var_0, var_1 )
{
    var_2 = self;
    var_2 endon( "disconnect" );
    var_3 = getdvarint( "scr_br_activateKSOnPurchase", 0 );

    if ( !var_3 )
    {
        var_2 scripts\mp\gametypes\br_pickups::forcegivekillstreak( var_0.ref, var_1, 1 );
        var_2 _makekioskpurchase( var_0.cost, var_0.firesalediscount, var_0.perkdiscount );
        var_2 thread scripts\mp\hud_message::showsplash( "br_killstreak_purchased" );
        var_2 scripts\cp_mp\challenges::onkioskpurchaseitem( "killstreak", var_0.ref );
        scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseitem( self, var_0.cost, "killstreak", var_0.ref );
    }
    else
    {
        if ( _killstreakneedslocationselection( var_0.ref ) )
        {
            var_4 = var_2.br_kiosk;
            var_2 _closepurchasemenuwithresponse( 16 );
            var_2 scripts\cp_mp\utility\player_utility::_freezecontrols( 1 );
            var_2 beginlocationselection( 0, 0, 0, 0, 4 );
            var_2 childthread _locationselectioninterrupt();
            var_5 = var_2 scripts\mp\killstreaks\mapselect::waittill_confirm_or_cancel( "confirm_location", "cancel_location" );
            var_2 endlocationselection();
            var_2 scripts\cp_mp\utility\player_utility::_freezecontrols( 0, 1 );

            if ( isdefined( var_5 ) && var_5.string == "confirm_location" )
            {
                var_6 = scripts\mp\gametypes\br::traceselectedmaplocation( var_5.location );
                var_2.kstargetlocation = var_6["position"];
                var_7 = var_2 scripts\mp\gametypes\br_pickups::forceusekillstreak( var_0.ref );

                if ( istrue( var_7 ) )
                {
                    var_2 _makekioskpurchase( var_0.cost, var_0.firesalediscount, var_0.perkdiscount );
                    var_2 thread scripts\mp\hud_message::showsplash( "br_killstreak_purchased_and_activated" );
                    scripts\cp_mp\challenges::onkioskpurchaseitem( "killstreak", var_0.ref );
                    scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseitem( self, var_0.cost, "killstreak", var_0.ref );
                    return;
                }

                return;
            }

            var_2 thread _runpurchasemenu( var_4 );
            return;
            return;
        }

        var_2 scripts\mp\gametypes\br_pickups::forcegivekillstreak( var_0.ref, var_1, 1 );
        var_7 = var_2 scripts\mp\gametypes\br_pickups::forceusekillstreak( var_0.ref );

        if ( istrue( var_7 ) )
        {
            var_2 _makekioskpurchase( var_0.cost, var_0.firesalediscount, var_0.perkdiscount );
            var_2 thread scripts\mp\hud_message::showsplash( "br_killstreak_purchased_and_activated" );
            scripts\cp_mp\challenges::onkioskpurchaseitem( "killstreak", var_0.ref );
            scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseitem( self, var_0.cost, "killstreak", var_0.ref );
        }
    }
}

_handlespecialpurchase( var_0, var_1 )
{
    var_2 = self;
    var_3 = 1;
    var_4 = 1;
    var_5 = undefined;

    switch ( var_0.ref )
    {
        case "armor":
            var_3 = scripts\mp\gametypes\br_pickups::br_forcegivecustompickupitem( var_2, "brloot_armor_plate", 1, undefined, 1 );
            break;
        case "armor_bundle":
            var_6 = var_2 _findgivearmoramountanddropleftovers( 1 );

            if ( var_6 <= 0 )
                var_3 = 1;
            else
                var_3 = scripts\mp\gametypes\br_pickups::br_forcegivecustompickupitem( var_2, "brloot_armor_plate", 1, var_6, 1 );

            break;
        case "gas_mask":
            var_3 = scripts\mp\gametypes\br_pickups::br_forcegivecustompickupitem( var_2, "brloot_equip_gasmask", 1, undefined, 1 );
            break;
        case "ammo_refill":
            var_2 scripts\mp\gametypes\br_weapons::br_ammo_player_max_out();
            var_2 _maxoutequipmentammo( var_2.equipment["primary"] );
            var_2 _maxoutequipmentammo( var_2.equipment["secondary"] );
            break;
        case "respawn_token":
            var_2 scripts\mp\gametypes\br_pickups::addrespawntoken();
            var_4 = 0;
            break;
        case "self_revive_token":
            var_2 scripts\mp\gametypes\br_pickups::addselfrevivetoken();
            var_4 = 0;
            break;
        case "supply_drop":
            var_3 = scripts\mp\gametypes\br_pickups::br_forcegivecustompickupitem( var_2, "brloot_offhand_advancedsupplydrop", 1, undefined, 1 );
            break;
        default:
            break;
    }

    if ( var_3 )
    {
        var_2 _makekioskpurchase( var_0.cost, var_0.firesalediscount, var_0.perkdiscount );

        if ( var_4 )
            var_2 thread scripts\mp\hud_message::showsplash( "br_item_purchased" );

        scripts\cp_mp\challenges::onkioskpurchaseitem( "special", var_0.ref );
        scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseitem( self, var_0.cost, "special", var_0.ref );
    }
}

_handlevehiclepurchase( var_0, var_1 )
{
    var_2 = ( 1, 1, 1 );
    var_3 = ( 1, 0, 0 );
    var_4 = ( 0, 1, 0 );
    var_5 = ( 0, 1, 1 );
    var_6 = 3;
    var_7 = 8;
    var_8 = self.br_kiosk.origin;

    if ( !scripts\cp_mp\vehicles\vehicle_tracking::canspawnvehicle() )
        return 0;

    if ( scripts\cp_mp\utility\player_utility::isinvehicle( 1 ) )
        return 0;

    var_9 = physics_createcontents( [ "physicscontents_solid", "physicscontents_water", "physicscontents_sky", "physicscontents_item", "physicscontents_vehicleclip" ] );
    var_10 = 300;
    var_11 = 90;
    var_12 = 300;
    var_13 = 150;
    var_14 = var_13 + var_10;
    var_15 = 0;
    var_16 = undefined;
    var_17 = undefined;

    for ( var_18 = undefined; var_15 < 360; var_15 = var_15 + var_11 )
    {
        var_19 = var_8 + ( sin( var_15 ) * var_10, cos( var_15 ) * var_10, 0 );
        var_16 = ( var_19[0], var_19[1], var_19[2] + var_14 );
        var_17 = ( var_19[0], var_19[1], var_19[2] - var_14 );
        var_20 = physics_spherecast( var_16, var_17, var_12, var_9, undefined, "physicsquery_closest" );

        if ( var_20.size > 0 )
        {
            var_21 = var_20[0]["position"];
            var_17 = ( var_16[0], var_16[1], var_20[0]["shape_position"][2] - var_10 );

            if ( !isdefined( var_20[0]["entity"] ) && abs( var_17[2] - var_19[2] ) < var_13 )
            {
                if ( !isdefined( var_18 ) )
                {
                    var_18 = var_17 + ( 0, 0, var_10 );

                    if ( !getdvarint( "scr_vehicleKioskFindAllSpawns", 0 ) > 0 )
                        break;
                }
            }
            else
            {

            }

            continue;
        }
    }

    if ( !isdefined( var_18 ) )
        return 0;

    var_22 = 150;
    var_23 = spawnstruct();
    var_23.origin = var_18 + ( 0, 0, var_22 );
    var_23.angles = ( 0, randomintrange( 0, 360 ), 0 );
    var_23.owner = self;
    var_23.spawntype = "GAME_MODE";
    var_24 = scripts\cp_mp\vehicles\vehicle_spawn::vehicle_spawn_spawnvehicle( var_0.ref, var_23 );

    if ( !isdefined( var_24 ) )
        return 0;

    var_25 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getdriverseat( var_24 );
    thread scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_enter( var_24, var_25, self );
    scripts\cp_mp\vehicles\vehicle_spawn::vehicle_spawn_preventrespawn( var_24 );
    return 1;
}

onarmorykioskpurchase( var_0, var_1 )
{
    var_2 = self;
    var_3 = var_2.br_kiosk;

    if ( !istrue( var_2.armorykioskpurchaseallowed ) )
        return;

    var_4 = "channel: " + var_0;

    if ( isdefined( var_1 ) )
        var_4 = var_4 + ", index: " + var_1;

    scripts\mp\gametypes\br_analytics::branalytics_kiosk_menu_event( var_2, "menu_purchase", var_4 );
    var_5 = getdvarint( "scr_br_kioskPurchaseDropItems", 1 );

    if ( var_0 == "br_cancel_purchase" )
        _purchasemenuclosedbyclient( var_2 );
    else if ( var_0 == "br_item_purchase" )
    {
        var_6 = var_1;
        var_7 = level.br_armory_kiosk.items[var_6];
        var_8 = var_2 _validateitempurchase( var_7, var_5 );

        if ( var_8 )
        {
            if ( var_7.type == "killstreak" )
                var_2 thread _handlekillstreakpurchase( var_7, var_5 );
            else if ( var_7.type == "fieldupgrade" )
            {
                var_2 scripts\mp\gametypes\br_pickups::forcegivesuper( var_7.ref, var_5, 1 );
                var_2 _makekioskpurchase( var_7.cost, var_7.firesalediscount, var_7.perkdiscount );
                var_2 thread scripts\mp\hud_message::showsplash( "br_field_upgrade_purchased" );
                scripts\cp_mp\challenges::onkioskpurchaseitem( "fieldUpgrade", var_7.ref );
                scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseitem( self, var_7.cost, "fieldUpgrade", var_7.ref );

                if ( level.allowsupers )
                    var_2 scripts\mp\supers::givesuperpoints( var_2 scripts\mp\supers::getsuperpointsneeded() );
            }
            else if ( var_7.type == "special" )
                var_2 _handlespecialpurchase( var_7, var_5 );
            else if ( var_7.type == "vehicle" )
            {
                var_9 = var_2 _handlevehiclepurchase( var_7, var_5 );

                if ( var_9 )
                {
                    var_2 _makekioskpurchase( var_7.cost, var_7.firesalediscount, var_7.perkdiscount );
                    var_2 thread scripts\mp\hud_message::showsplash( "br_vehicle_purchased" );
                    scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseitem( self, var_7.cost, "vehicle", var_7.ref );
                }
                else
                    var_2 scripts\mp\hud_message::showerrormessage( "MP/VEHICLE_PURCHASE_FAILED" );
            }
        }
    }
    else if ( var_0 == "br_loadout_purchase" )
    {
        var_10 = iskioskfiresaleactiveforplayer( var_2.br_kiosk, var_2 );
        var_11 = var_2 scripts\mp\utility\perk::_hasperk( "specialty_br_cheaper_kiosk" );
        var_12 = 0;
        var_13 = var_1;
        var_14 = level.br_armory_kiosk.loadoutcustomcost;
        var_15 = level.br_armory_kiosk.loadoutcustomfiresalediscount;
        var_16 = level.br_armory_kiosk.loadoutcustomperkdiscount;

        if ( scripts\mp\menus::isloadoutindexdefault( var_13 ) )
        {
            var_14 = level.br_armory_kiosk.loadoutdefaultcost;
            var_15 = level.br_armory_kiosk.loadoutdefaultfiresalediscount;
            var_16 = level.br_armory_kiosk.loadoutdefaultperkdiscount;
            var_12 = 1;
        }

        var_17 = _getactualcost( var_14, var_10, var_15, var_11, var_16 );

        if ( var_2.plundercount < var_17 )
        {
            var_2 _closepurchasemenuwithresponse( 3 );
            return;
        }

        var_18 = scripts\mp\menus::getclasschoice( var_13 );
        scripts\mp\gametypes\br_analytics::branalytics_inventory_snapshot( self, "purchasing_new_loadout" );
        var_2.pers["class"] = var_18;
        var_2.class = var_18;
        var_19 = var_2 scripts\mp\class::preloadandqueueclass( var_18 );
        scripts\mp\gametypes\br::br_giveselectedclass( var_2, var_5 );
        var_2 _makekioskpurchase( var_14, var_15, var_16 );
        var_2 thread scripts\mp\hud_message::showsplash( "br_loadout_purchased" );

        if ( istrue( var_12 ) )
            scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseitem( self, var_17, "defaultLoadout", "loadout_" + var_13 );
        else
            scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseloadout( self, var_17, var_19 );
    }
    else if ( var_0 == "br_team_revive" )
    {
        var_20 = var_1;
        var_10 = iskioskfiresaleactiveforplayer( var_2.br_kiosk, var_2 );
        var_15 = level.br_armory_kiosk.teamrevivefiresalediscount;
        var_11 = var_2 scripts\mp\utility\perk::_hasperk( "specialty_br_cheaper_kiosk" );
        var_16 = level.br_armory_kiosk.teamreviveperkdiscount;
        var_21 = !scripts\mp\gametypes\br_gametypes::isfeaturedisabled( "useTokenToReviveTeammate" );
        var_22 = istrue( var_2.hasrespawntoken ) && var_21;
        var_23 = _getactualcost( level.br_armory_kiosk.teamrevivecost, var_10, var_15, var_11, var_16 );

        if ( !var_22 && var_2.plundercount < var_23 )
        {
            var_2 _closepurchasemenuwithresponse( 3 );
            return 0;
        }

        var_24 = undefined;
        var_25 = scripts\mp\utility\teams::getteamdata( var_2.team, "players" );

        foreach ( var_27 in var_25 )
        {
            if ( !isdefined( var_27 ) || var_27 == var_2 )
                continue;

            if ( isdefined( var_27.br_squadindex ) && var_27.br_squadindex == var_20 )
            {
                var_24 = var_27;
                break;
            }
        }

        if ( !isdefined( var_24 ) )
        {
            var_2 _closepurchasemenuwithresponse( 12 );
            return;
        }

        if ( !var_24 scripts\mp\gametypes\br_public::iseligibleforteamrevive() && !getdvarint( "scr_br_all_assassin_version", 0 ) )
        {
            if ( scripts\mp\gametypes\br_public::isrespawningfromtoken( var_24 ) )
                var_2 _closepurchasemenuwithresponse( 14 );
            else if ( isalive( var_24 ) )
                var_2 _closepurchasemenuwithresponse( 15 );
            else
                var_2 _closepurchasemenuwithresponse( 13 );

            return;
        }

        var_29 = 0;

        if ( !var_22 )
        {
            var_30 = level.br_armory_kiosk.teamrevivecost;
            var_15 = level.br_armory_kiosk.teamrevivefiresalediscount;
            var_16 = level.br_armory_kiosk.teamreviveperkdiscount;
            var_2 _makekioskpurchase( var_30, var_15, var_16 );

            if ( istrue( var_2.hasrespawntoken ) )
                var_29 = 1;
            else
                var_2 scripts\mp\gametypes\br_pickups::addrespawntoken( 1 );

            var_2 scripts\cp_mp\challenges::onkioskpurchaseitem( "teamrevive", "teamrevive" );
            scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseitem( var_2, var_23, "teamrevive_money", "teamrevive" );
        }
        else
        {
            var_2 _makekioskpurchase( 0, 0, 0 );
            var_2 scripts\cp_mp\challenges::onkioskpurchaseitem( "teamrevive", "teamrevive" );
            scripts\mp\gametypes\br_analytics::branalytics_kiosk_purchaseitem( var_2, 0, "teamrevive_token", "teamrevive" );
        }

        var_24 thread scripts\mp\gametypes\br_gulag::playergulagautowin( var_2, var_22 );

        if ( var_29 )
            var_2 scripts\mp\gametypes\br_pickups::addrespawntoken( 1 );

        level thread scripts\mp\gametypes\br_quest_util::utilflare_shootflare( var_3.origin, "revive" );
        var_2 thread scripts\mp\hud_message::showsplash( "br_squadmate_revived" );
    }
}

_makekioskpurchase( var_0, var_1, var_2 )
{
    var_3 = self;
    var_4 = iskioskfiresaleactiveforplayer( var_3.br_kiosk, var_3 );
    var_5 = var_3 scripts\mp\utility\perk::_hasperk( "specialty_br_cheaper_kiosk" );

    if ( var_4 && var_1 > 0 )
        kioskfiresaledoneforplayer( var_3.br_kiosk, var_3 );

    if ( !scripts\mp\gametypes\br_public::isanytutorialorbotpracticematch() )
        var_3 thread scripts\mp\utility\points::giveunifiedpoints( "br_kioskBuy", undefined, scripts\mp\gametypes\br::calculatepurchasexp( var_0 ) );

    var_0 = _getactualcost( var_0, var_4, var_1, var_5, var_2 );

    if ( var_0 > 0 )
        var_3 scripts\mp\gametypes\br_plunder::playerplunderkioskpurchase( var_0 );

    if ( !isdefined( level.br_plunder ) )
        level.br_plunder = spawnstruct();

    if ( !isdefined( level.br_plunder.kiosk_spent_total ) )
        level.br_plunder.kiosk_spent_total = 0;

    level.br_plunder.kiosk_spent_total = level.br_plunder.kiosk_spent_total + var_0;

    if ( !isdefined( level.br_plunder.kiosk_num_purchases ) )
        level.br_plunder.kiosk_num_purchases = 0;

    level.br_plunder.kiosk_num_purchases++;
    var_3 _closepurchasemenuwithresponse( 1 );
}
