// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

spawnc130pathstruct( var_0, var_1 )
{
    var_2 = makepathparamsstruct( var_0, var_1 );
    var_3 = makepathstruct( var_2 );
    return var_3;
}

makepathparamsstruct( var_0, var_1 )
{
    var_2 = 160;
    var_3 = 200;

    if ( isdefined( var_0 ) )
        var_4 = var_0;
    else
        var_4 = ( 0, 0, 0 );

    if ( level.mapname == "mp_torez" )
    {
        var_2 = 165;
        var_3 = 195;
        var_4 = ( 3000, -2000, 0 );
    }

    var_5 = 6.28318;
    var_6 = randomfloatrange( 0, 360 );
    var_7 = randomfloatrange( var_2, var_3 );

    if ( isdefined( var_1 ) )
        var_8 = var_1;
    else
        var_8 = level.br_level.br_circleradii[3];

    var_9 = spawnstruct();
    var_9.r = var_8;
    var_9.randomangle = var_6;
    var_9.endangleoffset = var_7;
    var_9.centerpt = level.FirstCircleCenter;
    return var_9;
}

makepathstruct( var_0 )
{
    var_1 = var_0.r;
    var_2 = var_0.randomangle;
    var_3 = var_0.endangleoffset;
    var_4 = level.FirstCircleCenter;
    var_5 = ( var_2 + var_3 ) % 360;
    var_6 = ( var_1 * cos( var_2 ), var_1 * sin( var_2 ), scripts\cp_mp\parachute::getc130height() ) + var_4;
    var_7 = ( var_1 * cos( var_5 ), var_1 * sin( var_5 ), scripts\cp_mp\parachute::getc130height() ) + var_4;
    var_8 = vectornormalize( var_7 - var_6 );
    var_7 = var_7 + var_8 * var_1;
    var_6 = var_6 - var_8 * var_1 * 2;
    var_9 = spawnstruct();
    var_9.startpt = var_6;
    var_9.endpt = var_7;
    var_9.angle = vectortoangles( var_8 );
    return var_9;
}

snappointtomapbounds2d( var_0 )
{
    var_1 = level.br_level.br_mapbounds;

    if ( var_0[0] < var_1[1][0] )
        var_0 = ( var_1[1][0], var_0[1], var_0[2] );
    else if ( var_0[0] > var_1[0][0] )
        var_0 = ( var_1[0][0], var_0[1], var_0[2] );

    if ( var_0[1] < var_1[1][1] )
        var_0 = ( var_0[0], var_1[1][1], var_0[2] );
    else if ( var_0[1] > var_1[0][1] )
        var_0 = ( var_0[0], var_1[0][1], var_0[2] );

    return var_0;
}

ispointpaststart2d( var_0, var_1, var_2 )
{
    var_3 = ( var_0[0], var_0[1], 0 );
    var_4 = ( var_1[0], var_1[1], 0 );
    var_5 = ( var_2[0], var_2[1], 0 );
    var_6 = vectornormalize( var_3 - var_4 );
    var_7 = vectornormalize( var_5 - var_4 );
    var_8 = vectordot( var_6, var_7 );
    return var_8 > 0;
}

linecircleintersection2d( var_0, var_1, var_2, var_3 )
{
    var_4 = var_0[0] - var_2[0];
    var_5 = var_0[1] - var_2[1];
    var_6 = var_1[0] - var_2[0];
    var_7 = var_1[1] - var_2[1];
    var_8 = float( var_3 );
    var_9 = var_6 - var_4;
    var_10 = var_7 - var_5;
    var_11 = var_9 * var_9 + var_10 * var_10;
    var_12 = var_4 * var_7 - var_6 * var_5;
    var_13 = var_8 * var_8 * var_11 - var_12 * var_12;

    if ( var_13 < 0 )
        return;
    else if ( var_13 == 0 )
    {
        var_14 = var_12 * var_10 / var_11 + var_2[0];
        var_15 = -1 * var_12 * var_9 / var_11 + var_2[1];
        return ( var_14, var_15, 0 );
    }
    else
    {
        var_16 = sqrt( var_13 );
        var_17 = var_12 * var_10;
        var_18 = scripts\engine\utility::sign( var_10 ) * var_9 * var_16;
        var_19 = ( var_17 + var_18 ) / var_11 + var_2[0];
        var_20 = ( var_17 - var_18 ) / var_11 + var_2[0];
        var_21 = -1 * var_12 * var_9;
        var_22 = abs( var_10 ) * var_16;
        var_23 = ( var_21 + var_22 ) / var_11 + var_2[1];
        var_24 = ( var_21 - var_22 ) / var_11 + var_2[1];
        return [ ( var_19, var_23, 0 ), ( var_20, var_24, 0 ) ];
    }
}

getbestintersectionpt( var_0, var_1, var_2 )
{
    var_3 = linecircleintersection2d( var_0, var_1, var_2.origin, var_2.radius );

    if ( !isdefined( var_3 ) )
        return;
    else if ( !isarray( var_3 ) )
    {
        if ( ispointpaststart2d( var_3, var_0, var_1 ) )
            return var_3;
    }
    else
    {
        var_4 = ispointpaststart2d( var_3[0], var_0, var_1 );
        var_5 = ispointpaststart2d( var_3[1], var_0, var_1 );

        if ( !var_4 && !var_5 )
            return;
        else if ( var_4 && !var_5 )
            return var_3[0];
        else if ( var_5 && !var_4 )
            return var_3[1];
        else
        {
            var_6 = distance2dsquared( var_0, var_3[0] );
            var_7 = distance2dsquared( var_0, var_3[1] );

            if ( var_6 < var_7 )
                return var_3[0];
            else
                return var_3[1];
        }
    }
}

ray_trace_trigger_radius_2d( var_0, var_1, var_2 )
{
    var_3 = [];

    foreach ( var_5 in var_2 )
    {
        var_6 = getbestintersectionpt( var_0, var_1, var_5 );
        var_3[var_3.size] = var_6;
    }

    var_8 = undefined;
    var_9 = 0;

    foreach ( var_6 in var_3 )
    {
        var_11 = distance2dsquared( var_0, var_6 );

        if ( !isdefined( var_8 ) || var_11 < var_9 )
        {
            var_8 = var_6;
            var_9 = var_11;
        }
    }

    return var_8;
}

snappointtooutofboundstriggertrace( var_0, var_1 )
{
    if ( !isdefined( level.outofboundstriggers ) || level.outofboundstriggers.size == 0 )
        return snappointtomapbounds2d( var_1 );

    if ( !isdefined( level.outofboundstriggersplanetrace ) )
        level.outofboundstriggersplanetrace = level.outofboundstriggers;

    var_2 = physics_createcontents( [ "physicscontents_playertrigger" ] );
    var_3 = scripts\engine\trace::ray_trace_ents( var_0, var_1, level.outofboundstriggersplanetrace, var_2 );

    if ( var_3["fraction"] < 1.0 )
        var_1 = var_3["position"];

    if ( isdefined( level.outofboundstriggersspawned ) && level.outofboundstriggersspawned.size > 0 && getdvarint( "scr_br_spawnOOBKillswitch", 0 ) == 0 )
    {
        var_4 = ray_trace_trigger_radius_2d( var_0, var_1, level.outofboundstriggersspawned );

        if ( isdefined( var_4 ) )
        {
            var_5 = distance2dsquared( var_0, var_1 );
            var_6 = distance2dsquared( var_0, var_4 );

            if ( var_6 < var_5 )
                var_1 = ( var_4[0], var_4[1], var_1[2] );
        }
    }

    return var_1;
}

getplanepathsaferadiusfromcenter()
{
    var_0 = getdvarfloat( "scr_br_c130MaxRadiusPerc", 0.7 );
    var_1 = ( level.br_level.br_mapsize[0] / 2 + level.br_level.br_mapsize[1] / 2 ) / 2;
    var_2 = var_0 * var_1;
    return var_2;
}

iswithinplanepathsaferadius( var_0 )
{
    var_1 = level.br_level.br_mapcenter;
    var_2 = getplanepathsaferadiusfromcenter();
    var_3 = distance2d( var_1, var_0 );
    return var_3 < var_2;
}

spawnc130pathstructnew()
{
    var_0 = level.br_level.br_mapcenter;
    var_1 = getplanepathsaferadiusfromcenter();
    var_2 = randomfloat( 360 );

    if ( scripts\mp\gametypes\br_public::isbotpracticematch() )
    {
        if ( isdefined( level.infilplaneyaw ) )
            var_2 = level.infilplaneyaw;
        else
            var_2 = 75;
    }

    var_3 = anglestoforward( ( 0, var_2, 0 ) );
    var_3 = var_3 * ( var_1 * randomfloatrange( -1, 1 ) );
    var_3 = var_3 + ( 0, 0, getc130knownsafeheight() );
    var_0 = var_0 + var_3;

    if ( !scripts\mp\gametypes\br_public::isbotpracticematch() && !scripts\mp\gametypes\br_public::isdmzbotpracticematch() )
        var_0 = level.FirstCircleCenter;

    var_4 = ( 0, randomfloatrange( 0, 360 ), 0 );

    if ( scripts\mp\gametypes\br_public::isbotpracticematch() )
        var_4 = ( 0, 75, 0 );
    else
        var_4 = ( 0, getdvarfloat( "scr_br_c130PathAngle", var_4[1] ), 0 );

    var_5 = level.br_level.br_circleradii[0] * 2;
    var_6 = spawnc130pathstructnewinternal( var_0, var_4, var_5 );
    var_7 = scripts\cp_mp\parachute::getc130height();
    var_6.startpt = ( var_6.startpt[0], var_6.startpt[1], var_7 );
    var_6.endpt = ( var_6.endpt[0], var_6.endpt[1], var_7 );
    return var_6;
}

spawnc130pathstructnewinternal( var_0, var_1, var_2 )
{
    var_3 = anglestoforward( var_1 );
    var_2 = level.br_level.br_circleradii[0] * 2;

    if ( scripts\mp\gametypes\br_public::isbotpracticematch() )
        var_2 = level.br_level.br_circleradii[2] * 2;

    var_4 = var_0 - var_3 * var_2;
    var_5 = var_0 + var_3 * var_2;
    var_4 = snappointtooutofboundstriggertrace( var_0, var_4 );
    var_5 = snappointtooutofboundstriggertrace( var_0, var_5 );
    var_6 = var_4;
    var_7 = var_5;
    var_3 = vectornormalize( var_5 - var_4 );
    var_4 = var_4 - var_3 * getc130speed() * 10;
    var_5 = var_5 + var_3 * 100000;

    if ( scripts\mp\gametypes\br_public::isbotpracticematch() )
        var_4 = var_4 - var_3 * getc130speed() * 20;

    var_8 = spawnstruct();
    var_8.startpt = var_4;
    var_8.endpt = var_5;
    var_8.startptui = var_6;
    var_8.endptui = var_7;
    var_8.angle = var_1;
    var_8.pathdir = var_3;
    var_8.centerpt = level.FirstCircleCenter;
    return var_8;
}

getc130speed()
{
    if ( isdefined( level.br_level ) && isdefined( level.br_level.c130_speedoverride ) )
        return level.br_level.c130_speedoverride;

    return 3044;
}

getc130knownsafeheight()
{
    return 8000;
}

setc130heightoverrides( var_0, var_1 )
{
    if ( isdefined( var_0 ) )
        level.br_level.c130_heightoverride = var_0;

    if ( isdefined( var_1 ) )
        level.br_level.c130_sealeveloverride = var_1;

    setomnvar( "ui_br_altimeter_c130_height", scripts\cp_mp\parachute::getc130height() );
    setomnvar( "ui_br_altimeter_sea_height", scripts\cp_mp\parachute::getc130sealevel() );
}

updatec130pathomnvars( var_0 )
{
    if ( !isdefined( var_0 ) )
        return;

    if ( !isdefined( var_0.startpt ) || !isdefined( var_0.endpt ) || !isdefined( var_0.angle ) )
        return;

    setomnvar( "ui_br_c130_path_start_x", int( var_0.startptui[0] ) );
    setomnvar( "ui_br_c130_path_start_y", int( var_0.startptui[1] ) );
    setomnvar( "ui_br_c130_path_end_x", int( var_0.endptui[0] ) );
    setomnvar( "ui_br_c130_path_end_y", int( var_0.endptui[1] ) );
}

createtestc130path()
{
    self notify( "debug130Line" );

    if ( isdefined( level.br_level.br_mapcenter ) && isdefined( level.br_level.br_mapsize ) )
    {
        var_0 = spawnc130pathstructnew();
        level thread scripts\mp\gametypes\br_analytics::branalytics_planepath( level.br_level.br_circlecenters[4], var_0.angle[1], var_0.startptui, var_0.endptui );
    }
    else
        var_0 = spawnc130pathstruct();

    updatec130pathomnvars( var_0 );
    return var_0;
}

spawnc130( var_0 )
{
    var_1 = distance( var_0.startpt, var_0.endpt );
    var_2 = var_1 / getc130speed();
    level.br_ac130 = gunship_spawn( var_0.startpt, var_0.endpt, var_2 );
    level.br_ac130.pathstruct = var_0;
    return var_2;
}

spawnplayertoc130()
{
    if ( isdefined( level.infil_vignette_anim_type ) && level.infil_vignette_anim_type == "script_model" )
        self unlink();

    scripts\mp\gametypes\br_infils::endprematchskydiving();
    thread playerputinc130( level.br_ac130 );
    thread managejumpmasterinfodisplay();
    self.brneverlanded = 1;

    if ( istrue( self.isbrsquadleader ) && getdvar( "scr_br_gametype", "" ) != "dmz" )
        level scripts\mp\gametypes\br_public::brleaderdialogplayer( "deploy_squad_leader", self, 1, 0 );
}

playerputinc130( var_0 )
{
    self.angles = var_0.angles;
    self allowcrouch( 0 );
    self allowprone( 0 );
    thread listenjump( var_0, 0 );
    thread listenkick( var_0, 0 );
    self.br_infil_type = "c130";
    thread orbitcam( var_0 );
    self setclientomnvar( "ui_hide_nameplate_strings", 1 );
}

managejumpmasterinfodisplay()
{
    self endon( "disconnect" );
    self setclientomnvar( "ui_br_show_jumpmaster_info", 1 );
    scripts\engine\utility::waittill_any_2( "death", "freefall_complete" );
    self setclientomnvar( "ui_br_show_jumpmaster_info", 0 );
}

orbitcam( var_0 )
{
    self endon( "death" );

    if ( isdefined( level.infil_vignette_anim_type ) && level.infil_vignette_anim_type == "script_model" )
    {
        self.angles = var_0.angles;
        self playerlinkto( var_0, "" );
        self playerhide();
    }

    scripts\mp\utility\player::_visionsetnaked( "", 0 );
    self setplayerangles( var_0.angles );
    var_1 = 1;

    if ( isdefined( self.infilanimindex ) )
        var_1 = self.infilanimindex;

    var_2 = "cam_orbit_br_ac130_player" + var_1;
    self cameraset( var_2 );
}

gunship_spawn( var_0, var_1, var_2, var_3, var_4 )
{
    if ( !isdefined( var_3 ) )
        var_3 = 1;

    var_5 = spawn( "script_model", var_0 );
    var_5 setmodel( "veh8_mil_air_acharlie130_magma_animated" );
    var_5 setcandamage( 0 );
    var_5.maxhealth = 100000;
    var_5.health = var_5.maxhealth;
    var_5.cleanme = 1;
    var_5.startpt = var_0;
    var_5.dir = vectornormalize( var_1 - var_0 );
    var_5.angles = vectortoangles( var_5.dir );
    var_5.innards = spawn( "script_model", var_0 );
    var_5.innards setmodel( "veh8_mil_air_acharlie130_magma_rigid" );
    var_5.innards.cleanme = 1;
    var_5.innards linkto( var_5, "", ( 0, 0, 0 ), ( 0, 0, 0 ) );
    var_5.playeroffsets = [ ( 32, 30, -500 ), ( -32, 30, -500 ), ( 0, 30, -500 ), ( 16, 30, -500 ), ( -16, 30, -500 ) ];
    var_5.currentplayeroffset = 0;

    if ( var_3 )
        var_5 thread kickwhenoutofbounds( "c130" );

    if ( isdefined( var_4 ) )
        var_5 thread [[ var_4 ]]( var_1, var_2 );
    else
        var_5 thread gunship_handlemovement( var_1, var_2 );

    return var_5;
}

gunship_handlemovement( var_0, var_1 )
{
    level endon( "game_ended" );
    self endon( "death" );
    self hide();
    self.innards hide();
    self waittill( "start_moving" );
    self show();
    self.innards show();
    self moveto( var_0, var_1 );
    thread killaftertime( var_1, "c130" );
    thread gunship_spawnvfx();
    self playloopsound( "br_ac130_lp" );
}

gunship_spawnvfx()
{
    level endon( "game_ended" );

    if ( scripts\mp\utility\game::getgametype() == "br" )
    {
        wait 0.1;
        self setscriptablepartstate( "br_fx", "clouds" );
    }
    else
    {
        var_0 = level._effect["vfx_snatch_ac130_clouds"];

        if ( !isdefined( var_0 ) )
            return;

        wait 0.1;
        playfxontag( var_0, self, "tag_body" );
    }
}

inmapbounds( var_0 )
{
    var_1 = level.br_level.br_mapbounds;

    if ( isdefined( level.br_level.br_mapboundsfull ) )
        var_1 = level.br_level.br_mapboundsfull;

    if ( ( scripts\mp\gametypes\br_public::isdmzbotpracticematch() || scripts\mp\gametypes\br_public::isbotpracticematch() ) && isdefined( level.br_ac130 ) )
        var_2 = var_0[0] < var_1[1][0] && var_0[0] > var_1[0][0] && var_0[1] < var_1[1][1] && var_0[1] > var_1[0][1];
    else
        var_2 = var_0[0] < var_1[0][0] && var_0[0] > var_1[1][0] && var_0[1] < var_1[0][1] && var_0[1] > var_1[1][1];

    return var_2;
}

ispointinbounds( var_0, var_1 )
{
    var_2 = inmapbounds( var_0 );

    if ( ( scripts\mp\gametypes\br_public::isbotpracticematch() || scripts\mp\gametypes\br_public::isdmzbotpracticematch() ) && isdefined( level.br_ac130 ) )
        return var_2;

    if ( !var_2 )
        return 0;

    if ( iswithinplanepathsaferadius( var_0 ) )
        return 1;

    var_3 = scripts\mp\outofbounds::ispointinoutofbounds( var_0 );

    if ( var_3 )
        return 0;

    if ( istrue( var_1 ) )
    {
        var_4 = 16;
        var_5 = physics_createcontents( [ "physicscontents_playertrigger" ] );
        var_6 = physics_spherecast( var_0, var_0, var_4, var_5, undefined, "physicsquery_all" );

        foreach ( var_8 in var_6 )
        {
            var_9 = var_8["entity"];

            if ( isdefined( var_9 ) && isdefined( var_9.targetname ) && var_9.targetname == "OutOfBounds" )
                return 0;
        }
    }

    return 1;
}

planewaittillcandrop()
{
    var_0 = anglestoforward( self.angles );

    for (;;)
    {
        var_1 = vectornormalize( self.pathstruct.startptui - self.origin );
        var_2 = vectordot( var_0, var_1 ) < 0;

        if ( var_2 )
            break;

        waitframe();
    }
}

kickwhenoutofbounds( var_0 )
{
    level endon( "game_ended" );
    self endon( "death" );

    if ( !scripts\cp_mp\utility\game_utility::isrealismenabled() )
        setomnvarforallclients( "ui_hide_minimap", 1 );

    waitframe();
    planewaittillcandrop();
    var_1 = getc130knownsafeheight();

    while ( !ispointinbounds( ( self.origin[0], self.origin[1], var_1 ) ) )
        waitframe();

    if ( !scripts\cp_mp\utility\game_utility::isrealismenabled() )
        setomnvarforallclients( "ui_hide_minimap", 0 );

    level.br_latejoininfilready = 1;
    level.c130inbounds = 1;

    for (;;)
    {
        var_2 = anglestoforward( self.angles );
        var_3 = vectornormalize( self.pathstruct.centerpt - self.origin );
        var_4 = vectordot( var_2, var_3 ) < 0;

        if ( var_4 )
            break;

        waitframe();
    }

    var_5 = getdvarint( "scr_br_project_kick", 3500 );

    for (;;)
    {
        var_2 = anglestoforward( self.angles );
        var_6 = self.origin + var_2 * var_5;
        var_6 = ( var_6[0], var_6[1], var_1 );

        if ( !ispointinbounds( var_6 ) )
        {
            level.br_c130spawndone = 1;

            foreach ( var_8 in level.players )
            {
                if ( isdefined( var_8 ) && isdefined( var_8.br_infil_type ) && var_8.br_infil_type == var_0 && !isdefined( var_8.jumptype ) )
                {
                    var_8.jumptype = "outOfBounds";
                    var_8 notify( "halo_kick_c130" );
                }
            }

            break;
        }

        waitframe();
    }

    level.c130inbounds = undefined;
    level notify( "br_c130_left_bounds" );
}

killaftertime( var_0, var_1 )
{
    level endon( "game_ended" );
    self endon( "death" );
    wait( var_0 );

    if ( isdefined( self.players ) )
    {
        foreach ( var_3 in self.players )
        {
            if ( isdefined( var_3 ) && isdefined( var_3.br_infil_type ) && var_3.br_infil_type == var_1 && !isdefined( var_3.jumptype ) )
            {
                var_3.jumptype = "outOfBounds";
                var_3 notify( "halo_kick_c130" );
            }
        }
    }
    else
    {
        foreach ( var_3 in level.players )
        {
            if ( isdefined( var_3 ) && isdefined( var_3.br_infil_type ) && var_3.br_infil_type == var_1 && !isdefined( var_3.jumptype ) )
            {
                var_3.jumptype = "outOfBounds";
                var_3 notify( "halo_kick_c130" );
            }
        }
    }

    self stoploopsound();
    var_7 = level._effect["vfx_br_ac130_clouds"];
    var_8 = level._effect["vfx_br_ac130_oneshot"];

    if ( scripts\mp\utility\game::getgametype() != "br" )
        var_7 = level._effect["vfx_snatch_ac130_clouds"];

    if ( isdefined( var_7 ) )
        stopfxontag( var_7, self, "tag_body" );

    if ( isdefined( var_8 ) )
        stopfxontag( var_8, self, "tag_body" );

    wait 0.1;

    if ( isdefined( self.animstruct ) )
    {
        var_9 = 1;

        while ( var_9 )
        {
            var_9 = 0;

            foreach ( var_3 in level.players )
            {
                if ( isdefined( var_3.br_infil_type ) )
                {
                    var_9 = 1;
                    break;
                }
            }

            if ( var_9 )
                wait 0.5;
        }

        scripts\mp\gametypes\br_public::cleanac130struct( self.animstruct );
    }
    else
    {
        if ( isdefined( self.innards ) )
            self.innards delete();

        self delete();
    }
}

calctrailpoint()
{
    var_0 = self.origin - anglestoforward( self.angles ) * 150;
    return var_0;
}

listenkick( var_0, var_1 )
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    self endon( "cancel_c130" );
    self endon( "br_jump" );
    self waittill( "halo_kick_c130", var_2 );

    if ( !isdefined( var_2 ) )
        var_2 = ( 0, var_0.angles[1] + 180, 0 );

    self.brkickedfromplane = 1;
    thread leaveplane( var_0, var_1, var_2, 0 );
}

listenjump( var_0, var_1 )
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    self endon( "cancel_c130" );
    self endon( "br_jump" );
    var_2 = undefined;
    self.redeployenabled = 0;
    var_3 = getdvarint( "scr_br_squadLeaderForceJump", 0 );
    var_0 planewaittillcandrop();

    for (;;)
    {
        var_4 = scripts\engine\utility::waittill_either( "halo_jump_c130", "halo_jump_solo_c130" );

        if ( !isdefined( var_4 ) )
            var_4 = "halo_jump_c130";

        var_5 = scripts\mp\utility\teams::getteamdata( self.team, "players" );

        if ( !var_3 )
        {
            var_2 = var_0 calctrailpoint();

            if ( ispointinbounds( var_2 ) )
            {
                self.jumptype = "solo";
                self notify( "halo_kick_c130" );
                scripts\engine\utility::thread_on_notify( "infil_jump_done", scripts\mp\gametypes\br_public::updatebrscoreboardstat, "jumpMasterState", 0 );
                break;
            }
            else
                self iprintlnbold( &"MP_BR_INGAME/NOT_PLAYABLE" );

            continue;
        }

        var_6 = scripts\mp\gametypes\br_public::isplayerbrsquadleader() || isdefined( self.squadmemberindex ) && self.squadmemberindex == 0;

        if ( !var_6 && var_5.size > 1 )
        {
            if ( var_4 == "halo_jump_solo_c130" )
            {
                var_2 = var_0 calctrailpoint();

                if ( ispointinbounds( var_2 ) )
                {
                    self.jumptype = "solo";
                    self notify( "halo_kick_c130" );
                    scripts\engine\utility::thread_on_notify( "infil_jump_done", scripts\mp\gametypes\br_public::updatebrscoreboardstat, "jumpMasterState", 0 );
                    break;
                }
                else
                    self iprintlnbold( &"MP_BR_INGAME/NOT_PLAYABLE" );
            }

            continue;
        }

        var_2 = var_0 calctrailpoint();

        if ( ispointinbounds( var_2 ) )
        {
            if ( var_6 )
            {
                self.jumptype = "leader";
                var_7 = isdefined( level.squaddata );

                if ( var_7 )
                {
                    var_8 = level.squaddata[self.team][self.squadindex];
                    var_5 = var_8.players;
                }

                foreach ( var_10 in var_5 )
                {
                    if ( var_10 != self && isdefined( var_10.br_infil_type ) && !isdefined( var_10.jumptype ) )
                    {
                        var_10.jumptype = "follower";
                        var_10 notify( "halo_kick_c130", self getplayerangles() );
                    }

                    var_10 playlocalsound( "tmp_br_infil_ac130_jumpmaster_go" );
                }

                if ( var_4 != "halo_jump_solo_c130" && getdvarint( "scr_br_holdteamtojumpmaster", 0 ) )
                    thread holdteammatestosquadleader( var_5 );
                else
                {
                    foreach ( var_10 in var_5 )
                    {
                        if ( isdefined( var_10.br_infil_type ) )
                            setteammateomnvarsforplayer( var_10, var_5, 0 );
                    }
                }
            }

            break;
        }
        else
            self iprintlnbold( &"MP_BR_INGAME/NOT_PLAYABLE" );

        var_2 = var_0 calctrailpoint();
        waitframe();
    }

    thread leaveplane( var_0, var_1, self getplayerangles(), 0 );
}

leaveplane( var_0, var_1, var_2, var_3 )
{
    level endon( "game_ended" );
    self endon( "death_or_disconnect" );
    self endon( "cancel_c130" );
    setdvarifuninitialized( "scr_br_infil_hudoutline", 1 );
    self notify( "br_jump" );
    self allowcrouch( 1 );
    self allowprone( 1 );
    self.plotarmor = undefined;
    self.c130 = undefined;
    scripts\mp\gametypes\br_public::updatebrscoreboardstat( "isInInfilPlane", 0 );

    if ( isdefined( level.infilstruct ) && isdefined( level.infilstruct.playersinc130 ) )
        level.infilstruct.playersinc130--;

    self notifyonplayercommandremove( "halo_jump_c130", "+gostand" );
    self notifyonplayercommandremove( "halo_jump_solo_c130", "+gostand" );
    self notifyonplayercommandremove( "abandon_fireteam_leader", "+frag" );
    self notifyonplayercommandremove( "br_pass_squad_leader", "+usereload" );
    self notifyonplayercommandremove( "br_pass_squad_leader", "+activate" );
    self waittill( "infil_jump_done" );
    self cameradefault();
    self.br_infil_type = undefined;
    thread parachute( var_0, var_1, var_2, var_3 );
}

holdteammatestosquadleader( var_0 )
{
    level endon( "game_ended" );
    self endon( "death_or_disconnect" );
    thread watchforsquadleaddisconnect( var_0 );
    var_1 = self;
    wait 0.2;
    var_2 = [ ( -250, 0, 0 ), ( -150, -150, 0 ), ( -150, 150, 0 ) ];
    var_3 = 0;

    foreach ( var_5 in var_0 )
    {
        if ( !isdefined( var_5 ) || !isalive( var_5 ) )
            continue;

        if ( var_5 != var_1 )
        {
            if ( isdefined( var_5.jumptype ) && var_5.jumptype != "solo" )
            {
                var_5 thread pushplayertoplayeroffset( var_1, var_2[var_3] );
                var_3++;
                continue;
            }

            setteammateomnvarsforplayer( var_5, var_0, 0 );
        }
    }

    var_7 = 2700;
    var_8 = 999999999;

    while ( !self usebuttonpressed() && var_8 > var_7 )
    {
        var_9 = scripts\common\utility::groundpos( var_1.origin );
        var_8 = var_1.origin[2] - var_9[2];

        if ( var_1 isparachuting() )
            break;

        waitframe();
    }

    foreach ( var_11 in var_0 )
    {
        if ( !isdefined( var_11 ) || !isalive( var_11 ) )
            continue;

        if ( var_11 != self && istrue( var_11.beingpushed ) )
        {
            var_11 notify( "stop_push" );
            var_11.beingpushed = undefined;
        }

        setteammateomnvarsforplayer( var_11, var_0, 0 );
    }

    self notify( "hold_teammates_complete" );
}

watchforsquadleaddisconnect( var_0 )
{
    level endon( "game_ended" );
    self endon( "hold_teammates_complete" );
    scripts\engine\utility::waittill_any_2( "death", "disconnect" );

    foreach ( var_2 in var_0 )
    {
        if ( !isdefined( var_2 ) )
            continue;

        if ( var_2 != self && istrue( var_2.beingpushed ) )
        {
            var_2 notify( "stop_push" );
            var_2.beingpushed = undefined;
        }

        setteammateomnvarsforplayer( var_2, var_0, 0 );
    }
}

setteammateomnvarsforplayer( var_0, var_1, var_2 )
{
    var_3 = scripts\engine\utility::ter_op( var_0 scripts\mp\gametypes\br_public::isplayerbrsquadleader(), 2, var_2 );
    var_0 scripts\mp\gametypes\br_public::updatebrscoreboardstat( "jumpMasterState", var_3 );
}

playerparachutedetachresetomnvars()
{
    level endon( "game_ended" );
    self endon( "death_or_disconnect" );
    self endon( "stop_push" );
    self waittill( "skydive_deployparachute" );
    var_0 = scripts\mp\utility\teams::getteamdata( self.team, "players" );
    setteammateomnvarsforplayer( self, var_0, 0 );
}

pushplayertoplayeroffset( var_0, var_1 )
{
    level endon( "game_ended" );
    self.beingpushed = 1;
    var_2 = self;
    var_2 endon( "death_or_disconnect" );
    var_2 endon( "stop_push" );
    var_2 thread playerparachutedetachresetomnvars();
    var_3 = length( var_1 );

    while ( !var_2 isonground() && !var_2 usebuttonpressed() && isdefined( var_0 ) && !var_2 isparachuting() )
    {
        var_4 = var_0 getplayerangles();
        var_5 = rotatepointaroundvector( ( 0, 0, 1 ), var_1, var_4[1] );
        var_6 = var_0.origin + var_5 - var_2.origin;
        var_7 = length( var_6 );

        if ( var_7 > var_3 )
        {
            var_8 = var_2 getvelocity();
            var_2 setvelocity( var_6 + var_8 * 0.9 );
        }

        waitframe();
    }

    var_2 notify( "stop_push" );
    var_2.beingpushed = undefined;
    var_9 = scripts\mp\utility\teams::getteamdata( var_2.team, "players" );
    setteammateomnvarsforplayer( var_2, var_9, 0 );
}

parachute( var_0, var_1, var_2, var_3 )
{
    self setclientomnvar( "ui_br_infiled", 1 );
    self setclientomnvar( "ui_hide_nameplate_strings", 0 );
    self unlink();

    if ( isdefined( self.br_orbitcam ) )
        self.br_orbitcam delete();

    thread infilfreefallparachuteaudio( var_0 );
    waitframe();
    self playershow( 1 );

    if ( isdefined( var_2 ) )
        self setplayerangles( var_2 );

    if ( scripts\mp\utility\game::getgametype() == "br" )
    {
        self.br_isplayerbeforeinitialinfildeploy = undefined;
        scripts\mp\gametypes\br_analytics::branalytics_deploytriggered( self );
    }

    var_4 = ( 0, 0, 0 );

    if ( var_3 )
        var_4 = anglestoforward( var_0.angles ) * getc130speed();

    self.ignorefalldamagetime = gettime() + 5000;
    self skydive_setdeploymentstatus( 0 );
    thread scripts\cp_mp\parachute::startfreefall( 2.0, var_1, undefined, var_4 );
}

infilfreefallparachuteaudio( var_0 )
{
    self endon( "disconnect" );
    var_1 = self;

    if ( isdefined( var_0 ) )
        var_0 playsoundtoplayer( "br_ac130_flyby", var_1 );

    var_1 setsoundsubmix( "mp_br_infil_music", 0.0 );
    var_2 = game["music"]["br_plane_jump"].size - 1;
    var_3 = randomint( var_2 );
    var_1 setplayermusicstate( game["music"]["br_plane_jump"][var_3] );
    var_1.jump_music = 1;
    wait 1.0;
    var_1 clearclienttriggeraudiozone( 3.0 );
    wait 5.0;
    var_1 clearsoundsubmix( "mp_br_infil_music", 15.0 );
}

setplayervarinrespawnc130( var_0 )
{
    if ( isdefined( self.inrespawnc130 ) && self.inrespawnc130 == var_0 )
        return;

    self.inrespawnc130 = var_0;
    level notify( "update_circle_hide" );
}

waittoplayinfildialog()
{
    level endon( "game_ended" );
    level.br_ac130 endon( "death" );
    level.br_ac130 planewaittillcandrop();

    for (;;)
    {
        var_0 = level.br_ac130 calctrailpoint();

        if ( ispointinbounds( var_0 ) )
        {
            foreach ( var_2 in level.players )
            {
                if ( isplayer( var_2 ) )
                    var_2 playlocalsound( "scr_br_infil_ac130_klaxon" );
            }

            wait 1.0;
            level notify( "br_ready_to_jump" );
            scripts\mp\gametypes\br_analytics::branalytics_deployallowed();
            return;
        }

        waitframe();
    }
}
