// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    var_0 = getent( "infil_plane", "script_noteworthy" );
    level.brlatespawnplayer = ::latespawnplayer;

    if ( isdefined( var_0 ) )
        var_0 hide();

    setdvarifuninitialized( "br_infil_anim_enable_third_camera", 1 );
    setdvarifuninitialized( "br_infil_play_jump_anims", 1 );
    setdvarifuninitialized( "br_infil_bot_jumpmaster", 0 );
    level.infilselectionmethod = "";
    level.infilcanusemap = 0;

    if ( istrue( getdvarint( "br_spawnSelectionInfil", 0 ) ) )
    {
        level.infilselectionmethod = getdvar( "scr_br_infilselectionmethod", "exclusion" );
        level.infilcanusemap = 1;
        level.cansolospawn = getdvarint( "scr_br_canSoloJump", 1 );
    }

    initspawnexclusionpois();
    initinfillocationselectionhandlers();
}

setplayerprematchallows()
{
    scripts\mp\utility\player::enableplayerforspawnlogic( 0 );
    self allowmelee( 0 );
    self disableoffhandweapons();
    level.freefallstartcb = ::freefallstartfunc;
}

freefallstartfunc()
{
    self allowmelee( 1 );
    self enableoffhandweapons();
}

c130forcespawnplayer()
{
    self endon( "disconnect" );

    if ( self.class == "" )
    {
        self.class = "custom1";
        self.pers["class"] = "custom1";
    }

    scripts\mp\playerlogic::spawnplayer( 0 );
    self.br_infilstarted = 1;
    self notify( "brWaitAndSpawnClientComplete" );
    self setclientomnvar( "ui_br_transition_type", 0 );
    self setclientomnvar( "ui_br_extended_load_screen", 0 );
}

waitforc130andforcespawnallplayers()
{
    foreach ( var_1 in level.players )
    {
        if ( !isdefined( var_1 ) )
            continue;

        var_1 endprematchskydiving();

        if ( !isalive( var_1 ) )
            var_1 c130forcespawnplayer();
        else
            var_1.br_infilstarted = 1;

        if ( !isdefined( var_1 ) )
            continue;

        var_1 notify( "beginC130" );
    }

    if ( level.teambased )
    {
        foreach ( var_4 in level.teamnamelist )
        {
            var_5 = scripts\mp\utility\teams::getteamdata( var_4, "players" );
            var_6 = setupbrsquadleader( var_5 );

            if ( isdefined( var_6 ) )
            {
                registerbrsquadleaderjumpcommands( var_6 );
                var_6 thread watchbrsquadleaderdisconnect( var_4 );
            }

            scripts\mp\gametypes\br::updatesquadleaderpassstateforteam( var_4 );
        }
    }
    else
    {
        foreach ( var_1 in level.players )
            registerbrsquadleaderjumpcommands( var_1 );
    }

    if ( !scripts\mp\gametypes\br_gametypes::isfeaturedisabled( "oneLife" ) )
    {
        level.disablespawning = 1;
        setdynamicdvar( "scr_" + scripts\mp\utility\game::getgametype() + "_numLives", 1 );
    }

    level.snatchspawnalltoc130done = 1;
}

endprematchskydiving()
{
    var_0 = self;
    var_0 skydive_setdeploymentstatus( 0 );
    var_0 skydive_setbasejumpingstatus( 0 );

    if ( isdefined( var_0.ffsm_state ) )
        var_0.ffsm_state = 5;

    var_0 scripts\cp_mp\parachute::parachutecleanup();
}

registerbrsquadleaderjumpcommands( var_0 )
{
    if ( !istrue( var_0.jumpcomandsregistered ) )
    {
        var_0.jumpcomandsregistered = 1;
        var_0 scripts\mp\gametypes\br_public::updatebrscoreboardstat( "jumpMasterState", 2 );
        var_0 notifyonplayercommand( "halo_jump_c130", "+gostand" );
        var_0 notifyonplayercommand( "br_break_squad", "+breath_sprint" );
    }
}

watchbrsquadleaderdisconnect( var_0 )
{
    scripts\engine\utility::waittill_any_2( "death", "disconnect" );
    var_1 = scripts\mp\utility\teams::getteamdata( var_0, "players" );
    var_2 = setupbrsquadleader( var_1 );

    if ( isdefined( var_2 ) )
    {
        registerbrsquadleaderjumpcommands( var_2 );
        var_2 thread watchbrsquadleaderdisconnect( var_0 );
    }
}

performfailsafeinfil()
{
    var_0 = ( 0, 0, 3000 );

    if ( isdefined( level.prematchspawnorigins ) && level.prematchspawnorigins.size > 0 )
    {
        var_1 = scripts\engine\utility::random( level.prematchspawnorigins );
        var_0 = var_1.origin;
    }

    var_2 = ( 0, randomintrange( 0, 360 ), 0 );
    self setorigin( var_0, 1 );
    self setplayerangles( var_2 );
    wait 0.2;
    thread scripts\cp_mp\parachute::startfreefall( 0, 1 );
}

latespawnplayer()
{
    self endon( "disconnect" );
    var_0 = self;
    var_1 = scripts\mp\gametypes\br_public::istutorial() || scripts\mp\gametypes\br_public::isdmztutorial();

    if ( getdvar( "scr_br_lateSpawnFallback" ) != "" || var_1 )
        oldlatespawnplayer();
    else if ( !isalive( var_0 ) )
    {
        if ( !istrue( level.br_c130spawndone ) )
            var_0 thread latespawnsnatchtoc130();
        else
        {
            var_0.br_isininfil = 0;
            var_0.br_infilstarted = 1;
            var_2 = scripts\mp\utility\teams::getteamdata( var_0.team, "players" );

            if ( !isdefined( var_2 ) || var_2.size == 0 )
                var_2 = [ self ];

            setupbrsquadleader( var_2 );
            var_0 thread missedinfilplayerhandler();
        }
    }

    var_0 setclientomnvar( "ui_br_transition_type", 0 );
    var_0 setclientomnvar( "ui_br_extended_load_screen", 0 );
}

latespawnsnatchtoc130()
{
    var_0 = self;
    var_0 endon( "disconnect" );

    if ( !isalive( var_0 ) )
    {
        var_0.latetoinfil = 1;
        var_0 scripts\mp\playerlogic::spawnplayer( 0 );
    }

    var_0 playerhide();
    var_0.latetoinfil = undefined;
    var_0 freezecontrols( 1 );

    if ( var_0 scripts\mp\gametypes\br_public::isplayerbrsquadleader() )
        var_0.infilanimindex = 1;

    if ( !isdefined( var_0.infilanimindex ) && level.teambased )
    {
        var_1 = scripts\mp\utility\teams::getteamdata( var_0.team, "players" );
        var_2 = [];

        for ( var_3 = 0; var_3 < var_1.size - 1; var_3++ )
            var_2[var_3] = var_3 + 2;

        for ( var_3 = 0; var_3 < var_2.size; var_3++ )
        {
            var_4 = 0;

            foreach ( var_6 in var_1 )
            {
                if ( var_6 != var_0 && var_6 scripts\mp\gametypes\br_public::isplayerbrsquadleader() )
                    continue;

                if ( isdefined( var_6.infilanimindex ) && isdefined( var_2[var_3] ) && var_6.infilanimindex == var_2[var_3] )
                {
                    var_4 = 1;
                    break;
                }
            }

            if ( !var_4 )
            {
                var_0.infilanimindex = var_2[var_3];
                break;
            }
        }
    }

    var_0 playerjoininfil();
    var_0 playerlinktopositionent( level.latejoinersanimstruct );
    var_0.c130 = level.latejoinersanimstruct.movingc130;
    var_0 setorigin( level.latejoinersanimstruct.movingc130.origin );
    var_0 playerplayinfilloopanim( level.latejoinersanimstruct );
    waitframe();

    if ( isdefined( var_0.team ) && level.teambased )
    {
        var_1 = scripts\mp\utility\teams::getteamdata( var_0.team, "players" );

        foreach ( var_9 in var_1 )
        {
            var_0 showtoplayer( var_9 );
            var_9 showtoplayer( var_0 );
        }
    }

    if ( !isbot( var_0 ) )
        scripts\mp\gametypes\br_c130::orbitcam( level.br_ac130 );

    wait 0.5;
    var_0 freezecontrols( 0 );
    var_0 setclientomnvar( "ui_br_transition_type", 0 );
    var_0.br_infilstarted = 1;
}

missedinfilplayerhandler()
{
    var_0 = self;
    var_0.br_infilstarted = 1;
    var_0 scripts\mp\gametypes\br_pickups::addrespawntoken( 1 );
    var_0 scripts\mp\gametypes\br_gulag::playergulagautowin( undefined, undefined, 1 );
}

oldlatespawnplayer()
{
    self endon( "disconnect" );
    var_0 = self;

    if ( !isalive( var_0 ) )
        var_0 scripts\mp\playerlogic::spawnplayer( 0 );

    if ( level.teambased )
    {
        var_1 = scripts\mp\utility\teams::getteamdata( var_0.team, "players" );

        if ( !isdefined( var_1 ) || var_1.size == 0 )
            var_1 = [ self ];

        var_2 = setupbrsquadleader( var_1 );

        if ( isdefined( var_2 ) )
            registerbrsquadleaderjumpcommands( var_2 );
        else
        {

        }
    }
    else
    {
        var_0 scripts\mp\gametypes\br_public::updatebrscoreboardstat( "jumpMasterState", 2 );
        registerbrsquadleaderjumpcommands( var_0 );
    }

    var_0.br_infilstarted = 1;
}

takeloadoutatinfilend( var_0 )
{
    self takeweapon( self.weaponlist[0] );
    var_1 = makeweapon( "ks_remote_map_snatch" );
    var_2 = self getweaponslistall();

    foreach ( var_4 in var_2 )
    {
        if ( scripts\mp\utility\weapon::isgesture( var_4 ) )
            continue;

        if ( issameweapon( var_1, var_4 ) )
            continue;

        scripts\cp_mp\utility\inventory_utility::_takeweapon( var_4 );
    }

    self.primaryweaponobj = undefined;
    self.primaryweapon = "none";
    self.pers["primaryWeapon"] = self.primaryweapon;
    self.secondaryweaponobj = undefined;
    self.secondaryweapon = "none";
    self.pers["secondaryWeapon"] = self.secondaryweapon;

    if ( !istrue( var_0 ) )
    {
        var_6 = getforcedloadoutweapon();
        scripts\cp_mp\utility\inventory_utility::_giveweapon( var_6, 1 );
        thread scripts\cp_mp\utility\inventory_utility::domonitoredweaponswitch( var_6 );
        self setspawnweapon( var_6, 1 );

        if ( level.magcount == 0 )
        {
            self setweaponammoclip( var_6, 0 );
            self setweaponammostock( var_6, 0 );
        }
        else
        {
            self setweaponammoclip( var_6, weaponclipsize( var_6 ) );
            self setweaponammostock( var_6, weaponclipsize( var_6 ) * ( level.magcount - 1 ) );
        }

        self.secondaryweaponobj = var_6;
        self.secondaryweapon = getcompleteweaponname( self.secondaryweaponobj );
        self.pers["secondaryWeapon"] = self.secondaryweapon;
    }
}

getforcedloadoutweapon()
{
    return scripts\mp\class::buildweapon( "iw8_pi_mike9", [ "reflex", "none", "none", "none", "none" ], "none", "none", -1, undefined, undefined, undefined, undefined, undefined, 0 );
}

setupbrsquadleader( var_0 )
{
    if ( var_0.size == 0 )
        return undefined;

    var_1 = undefined;

    foreach ( var_3 in var_0 )
    {
        if ( isdefined( var_3 ) && var_3 scripts\mp\gametypes\br_public::isplayerbrsquadleader() )
            return var_3;
    }

    foreach ( var_3 in var_0 )
    {
        if ( level.onlinegame && var_3 isfireteamleader() )
        {
            var_1 = var_3;
            break;
        }
    }

    if ( !isdefined( var_1 ) )
    {
        var_7 = 0;
        var_8 = 0;

        foreach ( var_3 in var_0 )
        {
            var_10 = var_7 == isbot( var_3 );

            if ( var_10 )
            {
                var_8++;
                var_11 = 1.0 / var_8;

                if ( randomfloat( 1.0 ) < var_11 )
                    var_1 = var_3;
            }
        }
    }

    if ( !isdefined( var_1 ) )
    {
        foreach ( var_3 in var_0 )
        {
            var_1 = var_3;
            break;
        }
    }

    if ( !isdefined( var_1 ) )
        return undefined;

    var_1 scripts\mp\gametypes\br::setplayerbrsquadleader( 1 );

    foreach ( var_3 in var_0 )
    {
        if ( var_3 != var_1 )
            var_3 scripts\mp\gametypes\br::setplayerbrsquadleader( 0 );

        var_16 = scripts\engine\utility::ter_op( var_3 scripts\mp\gametypes\br_public::isplayerbrsquadleader(), 2, 1 );
        scripts\mp\gametypes\br_c130::setteammateomnvarsforplayer( var_3, var_0, var_16 );
    }

    return var_1;
}

buildac130infilanimstruct( var_0, var_1 )
{
    var_2 = spawnstruct();

    if ( isdefined( var_0 ) )
    {
        var_0.animstruct = var_2;
        var_2.movingc130 = var_0;
    }

    var_2.staticc130 = getent( "infil_plane", "script_noteworthy" );

    if ( isdefined( var_2.staticc130 ) )
        var_2.staticc130 show();
    else
    {
        var_2.staticc130 = spawn( "script_model", getdvarvector( "br_infil_anim_pos", ( 0, 0, 0 ) ) );
        var_2.staticc130 setmodel( "veh8_mil_air_acharlie130_magma_animated" );
        var_2.staticc130.cleanme = 1;
    }

    var_2.cameraent = spawn( "script_model", var_2.staticc130.origin );
    var_2.cameraent setmodel( "generic_prop_x5" );

    if ( isdefined( var_0 ) )
    {
        var_2.cameraentmoving = spawn( "script_model", var_2.movingc130.origin );
        var_2.cameraentmoving setmodel( "generic_prop_x5" );
        var_2.cameraentmoving linkto( var_2.movingc130, "tag_origin", ( 0, 0, 0 ), ( 0, 0, 0 ) );
    }

    spawnplayerpositionparentent( var_2, var_2.staticc130 );

    if ( var_1 == "script_model" )
    {
        var_2.playerslot1 = spawn( "script_model", var_2.staticc130.origin );
        var_2.playerslot1 setmodel( "fullbody_usmc_ar_br_infil" );
        var_2.playerslot2 = spawn( "script_model", var_2.staticc130.origin );
        var_2.playerslot2 setmodel( "fullbody_usmc_ar_br_infil" );
        var_2.playerslot3 = spawn( "script_model", var_2.staticc130.origin );
        var_2.playerslot3 setmodel( "fullbody_usmc_ar_br_infil" );
        var_2.playerslot4 = spawn( "script_model", var_2.staticc130.origin );
        var_2.playerslot4 setmodel( "fullbody_usmc_ar_br_infil" );
        var_2.playerslot1 linkto( var_2.playerpositionents["parent"], "j_prop_1", ( 0, 0, 0 ), ( 0, 0, 0 ) );
        var_2.playerslot2 linkto( var_2.playerpositionents["parent"], "j_prop_2", ( 0, 0, 0 ), ( 0, 0, 0 ) );
        var_2.playerslot3 linkto( var_2.playerpositionents["parent"], "j_prop_3", ( 0, 0, 0 ), ( 0, 0, 0 ) );
        var_2.playerslot4 linkto( var_2.playerpositionents["parent"], "j_prop_4", ( 0, 0, 0 ), ( 0, 0, 0 ) );
        var_2.infil_anim_type = "script_model";
    }
    else
    {
        var_3 = [ "j_prop_1", "j_prop_2", "j_prop_3", "j_prop_4" ];

        foreach ( var_5 in var_3 )
            spawnplayerpositionent( var_2, var_5 );

        var_2.infil_anim_type = "player";
    }

    var_2.aidoorchief = spawn( "script_model", var_2.staticc130.origin );
    var_2.aidoorchief setmodel( "fullbody_usmc_ar_br_infil" );

    if ( isdefined( var_0 ) )
        var_2.movingc130.innards linkto( var_2.movingc130, "", ( 0, 0, 0 ), ( 0, 0, 0 ) );

    var_2.aidoorchief linkto( var_2.playerpositionents["parent"], "j_prop_5", ( 0, 0, 0 ), ( 0, 0, 0 ) );
    var_2.cameraent linkto( var_2.staticc130, "", ( 0, 0, 0 ), ( 0, 0, 0 ) );
    var_2.cloudanimfx = spawnfx( level._effect["vfx_br_infil_cloud_anim"], var_2.staticc130.origin );
    return var_2;
}

spawnplayerpositionparentent( var_0, var_1 )
{
    var_0.playerpositionents["parent"] = spawn( "script_model", var_1.origin );
    var_0.playerpositionents["parent"] setmodel( "generic_prop_x5" );
    var_0.playerpositionents["parent"] linkto( var_1, "", ( 0, 0, 0 ), ( 0, 0, 0 ) );
}

spawnplayerpositionent( var_0, var_1 )
{
    var_0.playerpositionents[var_1] = spawn( "script_model", var_0.playerpositionents["parent"] gettagorigin( var_1 ) );
    var_0.playerpositionents[var_1] setmodel( "tag_player" );
    var_0.playerpositionents[var_1] linkto( var_0.playerpositionents["parent"], var_1, ( 0, 0, 0 ), ( 0, 0, 0 ) );
}

#using_animtree("script_model");

getanimsforplanefacing( var_0 )
{
    var_1 = self getplayerangles( 1 );
    var_2 = anglestoforward( var_1 );
    var_3 = anglestoforward( var_0.movingc130.angles );
    var_4 = anglestoright( var_0.movingc130.angles );
    var_5 = vectordot( var_2, var_3 );
    var_6 = vectordot( var_2, var_4 );
    var_7 = cos( 45.0 );

    if ( var_5 < -1.0 * var_7 )
        return [ "sdr_mp_infil_ac130_jump_genpropx10", %sdr_mp_infil_ac130_jump_genpropx10, "sdr_mp_infil_ac130_jump" ];

    if ( var_6 > var_7 )
        return [ "sdr_mp_infil_ac130_jump_genpropx10_90_l", %sdr_mp_infil_ac130_jump_genpropx10_90_l, "sdr_mp_infil_ac130_jump_90_l" ];
    else if ( var_6 < -1.0 * var_7 )
        return [ "sdr_mp_infil_ac130_jump_genpropx10_90_r", %sdr_mp_infil_ac130_jump_genpropx10_90_r, "sdr_mp_infil_ac130_jump_90_r" ];
    else if ( var_6 > 0.0 )
        return [ "sdr_mp_infil_ac130_jump_genpropx10_180_l", %sdr_mp_infil_ac130_jump_genpropx10_180_l, "sdr_mp_infil_ac130_jump_180_l" ];
    else
        return [ "sdr_mp_infil_ac130_jump_genpropx10_180_r", %sdr_mp_infil_ac130_jump_genpropx10_180_r, "sdr_mp_infil_ac130_jump_180_r" ];
}

playjumpsoundtosquad( var_0 )
{
    var_1 = "";

    if ( var_0 scripts\mp\gametypes\br_public::isplayerbrsquadleader() )
        var_1 = "br_infil_squad_leader_jump";
    else
        var_1 = "br_infil_squadmate_jump";

    var_0 playsoundtoteam( var_1, var_0.team, var_0 );
}

watchinfiljumpanim( var_0 )
{
    self endon( "death_or_disconnect" );

    if ( !isdefined( level.infiljumpentsspawned ) )
        level.infiljumpentsspawned = 0;

    self.hasspawnweapons = 0;
    self waittill( "br_jump" );
    var_1 = scripts\mp\utility\teams::getteamdata( self.team, "players" );
    var_2 = [];

    if ( self.jumptype == "leader" )
    {
        foreach ( var_4 in var_1 )
        {
            if ( isdefined( var_4.infilanimindex ) )
                var_2[var_2.size] = var_4;
        }
    }
    else if ( self.jumptype == "solo" || self.jumptype == "outOfBounds" )
        var_2 = [ self ];

    var_6 = var_2.size > 0;

    if ( var_6 )
    {
        var_7 = getdvarint( "br_infil_play_jump_anims", 1 ) != 0;

        if ( level.infiljumpentsspawned >= 100 )
            var_7 = 0;

        var_8 = undefined;

        if ( var_7 )
        {
            var_8 = 0;
            [var_10, var_11, var_12] = getanimsforplanefacing( var_0 );
            var_13["parent"] = spawn( "script_model", var_0.movingc130.origin );
            level.infiljumpentsspawned++;
            var_13["parent"] setmodel( "generic_prop_x10" );
            var_13["parent"] linkto( var_0.movingc130, "tag_body", ( 0, 0, 0 ), ( 0, 0, 0 ) );

            foreach ( var_4 in var_2 )
            {
                var_15 = "j_prop_" + ( var_4.infilanimindex + 2 );
                var_13[var_15] = spawn( "script_model", var_13["parent"] gettagorigin( var_15 ) );
                level.infiljumpentsspawned++;
                var_13[var_15] setmodel( "tag_player" );
                var_13[var_15] linkto( var_13["parent"], var_15, ( 0, 0, 0 ), ( 0, 0, 0 ) );
                var_4 playerlinkto( var_13[var_15], "tag_player" );
                var_4 playershow( 1 );
                var_4 playanimscriptsceneevent( "scripted_scene", var_12 );
                var_4.infilanimindex = undefined;
                var_4 playlocalsound( "scr_br_infil_jump_stinger" );
                level thread playjumpsoundtosquad( var_4 );
            }

            var_13["parent"] scriptmodelplayanim( var_10, "prop" );
            var_17 = getanimlength( var_11 );
            var_18 = 1.0;
            var_17 = max( var_17, var_18 + 0.1 );
            wait( var_17 - var_18 );

            foreach ( var_4 in var_2 )
                var_4 cameradefault();

            wait( var_18 );

            foreach ( var_22 in var_13 )
            {
                var_22 delete();
                level.infiljumpentsspawned--;
            }
        }
        else
        {
            var_8 = 1;
            waittillframeend;
        }

        foreach ( var_4 in var_2 )
        {
            var_4.infilanimindex = undefined;
            var_4 stopanimscriptsceneevent();
            var_4 notify( "infil_jump_done" );
            var_4 scripts\mp\gametypes\br::playerexecutionsenable();
        }

        if ( var_8 )
        {
            waitframe();

            if ( isdefined( var_0.movingc130 ) )
            {
                if ( isdefined( var_0.movingc130.playeroffsets ) && isdefined( var_0.movingc130.currentplayeroffset ) )
                {
                    foreach ( var_4 in var_2 )
                    {
                        var_27 = var_0.movingc130.playeroffsets[var_0.movingc130.currentplayeroffset];
                        var_4 setorigin( var_0.movingc130.origin + var_27, 1, 1 );
                        var_0.movingc130.currentplayeroffset++;

                        if ( var_0.movingc130.currentplayeroffset == var_0.movingc130.playeroffsets.size )
                            var_0.movingc130.currentplayeroffset = 0;

                        var_4 playershow( 1 );
                        level thread playjumpsoundtosquad( var_4 );
                    }
                }
            }
        }
    }
}

playinfilplayeranims( var_0 )
{
    var_1 = getanimlength( %sdr_mp_infil_ac130_redux_player1 );

    foreach ( var_3 in level.players )
    {
        var_3 thread [[ level.parachutetakeweaponscb ]]();
        var_3 scripts\mp\gametypes\br::playerexecutionsdisable();
        var_3.c130 = var_0.movingc130;
        var_3.plotarmor = 1;
        var_3 playerlinktopositionent( var_0 );
        var_4 = "sdr_mp_infil_ac130_redux_player" + var_3.infilanimindex;
        var_3 playanimscriptsceneevent( "scripted_scene", var_4 );
    }

    wait( var_1 );

    foreach ( var_3 in level.players )
        var_3 thread playerplayinfilloopanim( var_0 );
}

playerlinktopositionent( var_0 )
{
    if ( !isdefined( self.infilanimindex ) )
        self.infilanimindex = 1;

    var_1 = "j_prop_" + self.infilanimindex;
    self playerlinkto( var_0.playerpositionents[var_1], "tag_player" );
}

playerplayinfilloopanim( var_0 )
{
    if ( !isdefined( self.infilanimindex ) )
        self.infilanimindex = 1;

    var_1 = "sdr_mp_infil_ac130_loop_pl0" + self.infilanimindex;
    self playanimscriptsceneevent( "scripted_scene", var_1 );
    thread watchinfiljumpanim( var_0 );
}

redlight( var_0 )
{
    var_0 endon( "stopScene" );
    var_0.staticc130 waittillmatch( "plane", "gored" );
    var_1 = getentitylessscriptablearray( "infil_blinking_light", "script_noteworthy" );

    foreach ( var_3 in var_1 )
        var_3 setscriptablepartstate( "light_blinking_slow", "light_on", 1 );
}

greenlight( var_0 )
{
    var_0 endon( "stopScene" );
    var_0.staticc130 waittillmatch( "plane", "gogreen" );
    var_1 = getentitylessscriptablearray( "infil_blinking_light", "script_noteworthy" );

    foreach ( var_3 in var_1 )
        var_3 setscriptablepartstate( "light_blinking_slow", "light_jump", 1 );
}

offlight( var_0 )
{
    var_1 = getentitylessscriptablearray( "infil_blinking_light", "script_noteworthy" );

    foreach ( var_3 in var_1 )
        var_3 setscriptablepartstate( "light_blinking_slow", "light_off_hold", 1 );
}

playerwind( var_0 )
{
    var_0 endon( "stopScene" );
    var_0.staticc130 scripts\engine\utility::waittill_match_or_timeout( "plane", "opendoor", 30.0 );

    foreach ( var_2 in level.players )
    {
        if ( isbot( var_2 ) )
            continue;

        var_2 scripts\mp\utility\player::setwind( "100", 1 );
    }

    var_0.aidoorchief scripts\mp\utility\player::setwind( "100" );
}

clearplayerwind( var_0 )
{
    foreach ( var_2 in level.players )
        var_2.manualoverridewindmaterial = undefined;

    var_0.aidoorchief scripts\mp\utility\player::setwind( "0" );
}

clearsoundsubmixmpbrinfilac130()
{
    waitandpause( 7.7 );

    foreach ( var_1 in level.players )
        var_1 clearsoundsubmix( "mp_br_infil_ac130", 30.0 );
}

clearsoundsubmixmpbrinfilanim()
{
    waitandpause( 0.65 );

    foreach ( var_1 in level.players )
        var_1 clearsoundsubmix( "mp_br_infil_anim", 3.0 );
}

clearsoundsubmixfadetoblackamb()
{
    waitandpause( 0.5 );

    foreach ( var_1 in level.players )
        var_1 clearsoundsubmix( "fade_to_black_all_except_music_scripted5_and_amb", 1.0 );
}

setsoundsubmixfadetoblackamb()
{
    waitandpause( 2.0 );

    foreach ( var_1 in level.players )
    {
        var_1 clearsoundsubmix( "fade_to_black_all_except_music_and_scripted5", 0.5 );
        var_1 setsoundsubmix( "fade_to_black_all_except_music_scripted5_and_amb", 2.0 );
    }
}

playac130infilanim( var_0 )
{
    thread setsoundsubmixfadetoblackamb();
    playac130animinternal( var_0 );
    transitionac130tomovinganim( var_0 );
    endac130infilanimsinternal( var_0 );
}

cloud_cover( var_0 )
{
    var_0 endon( "stopScene" );
    var_0.staticc130 waittillmatch( "plane", "transitionstart" );
    triggerfx( var_0.cloudanimfx );
}

fade_cover( var_0 )
{
    level endon( "game_ended" );

    if ( !isdefined( var_0.cameraentmoving ) )
        return;

    var_1 = newhudelem();
    var_1.x = 0;
    var_1.y = 0;
    var_1 setshader( "white", 640, 480 );
    var_1.alignx = "left";
    var_1.aligny = "top";
    var_1.horzalign = "fullscreen";
    var_1.vertalign = "fullscreen";
    var_1.sort = -1;
    var_1.color = ( 0.88, 0.88, 0.88 );
    var_1 setautoboxcalculationusingdobj( 1 );
    var_1.alpha = 0;
    var_2 = 0.16;
    var_3 = 0.5;
    var_0.cameraentmoving waittillmatch( "camera", "fadeinstart" );
    var_1 fadeovertime( var_2 );
    var_1.alpha = 1;
    var_0.cameraentmoving waittillmatch( "camera", "fadeoutstart" );
    var_1 fadeovertime( var_3 );
    var_1.alpha = 0;
    waitandpause( var_3 + 0.1 );
    var_1 destroy();
}

infil_light_dvars( var_0 )
{
    var_1 = getdvarfloat( "LKOLRONRNQ" );
    var_2 = getdvarint( "LTQMSPKRKO" );
    var_3 = getdvarint( "MROOOROPKL" );
    var_4 = getdvarfloat( "NPONLLLSPL" );
    setdvar( "LKOLRONRNQ", 1000.0 );
    setdvar( "LTQMSPKRKO", 6 );
    setdvar( "MROOOROPKL", 8 );
    setdvar( "NPONLLLSPL", 0.25 );
    var_0 scripts\engine\utility::waittill_either( "infil_reset_light_dvars", "stopScene" );
    setdvar( "LKOLRONRNQ", var_1 );
    setdvar( "LTQMSPKRKO", var_2 );
    setdvar( "MROOOROPKL", var_3 );
    setdvar( "NPONLLLSPL", var_4 );
}

playac130animinternal( var_0 )
{
    var_0 endon( "stopScene" );
    var_1 = undefined;

    if ( var_0.infil_anim_type == "player" )
    {
        foreach ( var_3 in level.teamnamelist )
        {
            var_4 = scripts\mp\utility\teams::getteamdata( var_3, "players" );
            var_5 = [];

            for ( var_6 = 0; var_6 < var_4.size - 1; var_6++ )
                var_5[var_6] = var_6 + 2;

            foreach ( var_13, var_8 in var_4 )
            {
                var_8 playerhide();

                if ( var_8 scripts\mp\gametypes\br_public::isplayerbrsquadleader() )
                    var_8.infilanimindex = 1;
                else
                {
                    var_9 = scripts\engine\utility::random( var_5 );
                    var_8.infilanimindex = var_9;
                    var_5 = scripts\engine\utility::array_remove( var_5, var_9 );
                }

                foreach ( var_11 in var_4 )
                    var_8 showtoplayer( var_11 );
            }
        }
    }
    else
    {

    }

    var_18 = 34;
    var_19 = 5.6;
    var_20 = 50.7;
    var_21 = 2.0;
    var_22 = 4;
    var_0.cameraent scriptmodelplayanim( "sdr_mp_infil_ac130_redux_players_cam", "camera" );

    if ( isdefined( var_0.cameraentmoving ) )
        var_0.cameraentmoving scriptmodelplayanim( "sdr_mp_infil_ac130_redux_players_cam", "camera" );

    if ( isdefined( var_0.movingc130 ) )
        var_0.movingc130 stoploopsound();

    var_23 = scripts\mp\gametypes\br_public::isusinginfilselection();

    foreach ( var_8 in level.players )
    {
        if ( !var_23 )
        {
            var_8 setsoundsubmix( "mp_br_infil_anim", 0.0 );
            var_8 setsoundsubmix( "mp_br_infil_music", 0.0 );
            var_8 setsoundsubmix( "mp_br_infil_ac130", 0.0 );
            var_8 setclienttriggeraudiozone( "mp_donetsk_infil_int", 1.0 );
        }

        var_0.cameraentlinktag = "j_prop_" + var_8.infilanimindex;
        var_8 cameraunlink();
        var_8 cameralinkto( var_0.cameraent, var_0.cameraentlinktag, 1, 1 );
        var_8 setclientdvar( "QTSPTNLOL", var_18 );
        var_8 enablephysicaldepthoffieldscripting();
        var_8 setphysicaldepthoffield( var_19, var_20, var_21, var_22 );
        var_8 scripts\mp\utility\player::_freezelookcontrols( 1 );
    }

    thread clearsoundsubmixmpbrinfilanim();
    thread getlightingvalues();
    playfxontag( level._effect["vfx_br_ac130_clouds"], var_0.staticc130, "tag_body" );
    var_0.staticc130 scriptmodelplayanim( "sdr_mp_infil_ac130_redux_players_ac130", "plane" );

    if ( isdefined( var_0.movingc130 ) )
    {
        var_0.movingc130 scriptmodelplayanim( "sdr_mp_infil_ac130_redux_players_ac130", "plane" );
        var_0.movingc130.innards scriptmodelplayanim( "sdr_mp_infil_ac130_redux_players_ac130", "planeInnards" );
    }

    var_0.playerpositionents["parent"] scriptmodelplayanim( "sdr_mp_infil_ac130_redux_character_link", "prop" );

    if ( var_0.infil_anim_type == "script_model" )
    {
        var_0.playerslot1 scriptmodelplayanim( "sdr_mp_infil_ac130_redux_player1", "p1" );
        var_0.playerslot2 scriptmodelplayanim( "sdr_mp_infil_ac130_redux_player2", "p2" );
        var_0.playerslot3 scriptmodelplayanim( "sdr_mp_infil_ac130_redux_player3", "p3" );
        var_0.playerslot4 scriptmodelplayanim( "sdr_mp_infil_ac130_redux_player4", "p4" );
    }
    else if ( var_0.infil_anim_type == "player" )
        thread playinfilplayeranims( var_0 );

    var_0.aidoorchief scriptmodelplayanim( "sdr_mp_infil_ac130_redux_doorchief", "doorchief" );
    level thread offlight( var_0 );
    level thread redlight( var_0 );
    level thread greenlight( var_0 );
    level thread playerwind( var_0 );
    level thread cloud_cover( var_0 );
    level thread fade_cover( var_0 );
    level thread infil_light_dvars( var_0 );
    level thread delaystreamtomovingplane( var_0 );
    var_0.cameraent scripts\engine\utility::waittill_match_or_timeout( "camera", "transition", 30.0 );
    var_0 notify( "infil_reset_light_dvars" );
    level clearplayerwind( var_0 );
    var_26 = 0.1;
    var_27 = 0.0;
    var_28 = 0.2;
}

delaystreamtomovingplane( var_0 )
{
    if ( isdefined( var_0.movingc130 ) && getdvarint( "scr_br_streamToMovingPlane", 1 ) == 1 )
    {
        var_1 = getdvarint( "scr_br_streamToMovingPlaneDelay", 8 );
        wait( var_1 );
        var_2 = var_0.movingc130.origin;
        var_3 = getdvarint( "scr_br_streamToMovingPlaneForward", 0 );

        if ( var_3 > 0 )
        {
            var_4 = anglestoforward( var_0.movingc130.angles );
            var_2 = var_0.movingc130.origin + var_4 * var_3;
        }

        foreach ( var_6 in level.players )
        {
            var_6 calloutmarkerping_getorigin( 0.0 );
            var_6 scripts\mp\gametypes\br_public::playerstreamhintlocation( var_2 );
        }
    }
}

stopstreamtomovingplane( var_0 )
{
    if ( isdefined( var_0.movingc130 ) && getdvarint( "scr_br_streamToMovingPlane", 1 ) == 1 )
    {
        var_1 = getdvarint( "scr_br_streamToMovingPlaneEndDelay", 5 );
        wait( var_1 );

        foreach ( var_3 in level.players )
            var_3 thread scripts\mp\gametypes\br_public::playerclearstreamhintorigin();
    }
}

unfreezeplayercontrols( var_0 )
{
    wait( var_0 );

    foreach ( var_2 in level.players )
        var_2 scripts\mp\utility\player::_freezelookcontrols( 0 );
}

transitionac130tomovinganim( var_0 )
{
    var_1 = 65;
    var_2 = 14;
    var_3 = 35;
    var_4 = 2.0;
    var_5 = 4;

    if ( isdefined( var_0.cameraentmoving ) )
    {
        foreach ( var_7 in level.players )
        {
            var_7 setpredictedstreamloaddist( 0.0 );

            if ( !isdefined( var_7.infilanimindex ) )
                var_7.infilanimindex = 1;

            var_0.cameraentlinktag = "j_prop_" + var_7.infilanimindex;
            var_7 cameraunlink();
            var_7 cameralinkto( var_0.cameraentmoving, var_0.cameraentlinktag, 1, 1 );
            var_7 setclientdvar( "QTSPTNLOL", var_1 );
            var_7 setphysicaldepthoffield( var_2, var_3, var_4, var_5 );
        }

        thread clearsoundsubmixfadetoblackamb();
    }
    else
    {
        foreach ( var_7 in level.players )
            var_7 setpredictedstreamloaddist( 0.0 );
    }

    if ( isdefined( var_0.cloudanimfx ) )
    {
        if ( isdefined( var_0.movingc130 ) )
            var_0.cloudanimfx.origin = var_0.movingc130.origin;
    }

    var_0.staticc130 hide();
    var_0.cameraent unlink();
    var_0.playerpositionents["parent"] unlink();

    if ( isdefined( var_0.movingc130 ) )
    {
        var_0.playerpositionents["parent"] linkto( var_0.movingc130, "", ( 0, 0, 0 ), ( 0, 0, 0 ) );
        var_0.cameraent linkto( var_0.movingc130, "", ( 0, 0, 0 ), ( 0, 0, 0 ) );
        var_0.movingc130 notify( "start_moving" );
    }

    setomnvar( "ui_hide_player_icons", 0 );

    foreach ( var_7 in level.players )
    {
        if ( !isdefined( var_7 ) )
            continue;

        var_7 setclienttriggeraudiozone( "mp_donetsk_infil_ext", 2.0 );
    }

    thread clearsoundsubmixmpbrinfilac130();

    if ( var_0.infil_anim_type == "script_model" )
    {
        var_0.playerslot1 scriptmodelplayanim( "sdr_mp_infil_ac130_loop_pl01", "p1" );
        var_0.playerslot2 scriptmodelplayanim( "sdr_mp_infil_ac130_loop_pl02", "p2" );
        var_0.playerslot3 scriptmodelplayanim( "sdr_mp_infil_ac130_loop_pl03", "p3" );
        var_0.playerslot4 scriptmodelplayanim( "sdr_mp_infil_ac130_loop_pl04", "p4" );
    }

    var_0.aidoorchief scriptmodelplayanim( "sdr_mp_infil_ac130_loop_doorchief", "doorchief" );
    level thread playac130infilloopanims( var_0 );

    if ( isdefined( var_0.cameraentmoving ) )
        var_0.cameraentmoving waittillmatch( "camera", "end" );

    thread unfreezeplayercontrols( 1.2 );
}

endac130infilanimsinternal( var_0 )
{
    thread lightsreset();
    stopfxontag( level._effect["vfx_br_ac130_clouds"], var_0.staticc130, "tag_body" );
    var_0.staticc130 stoploopsound();

    if ( isdefined( var_0.movingc130 ) )
        var_0.movingc130 playloopsound( "br_ac130_lp" );

    foreach ( var_2 in level.players )
    {
        var_2 setpredictedstreamloaddist( 0.0 );
        var_2 cameraunlink();
        var_2 setclientdvar( "QTSPTNLOL", 65 );
        var_2 disablephysicaldepthoffieldscripting();
        var_2 scripts\mp\utility\player::setdof_default();
    }

    level thread stopstreamtomovingplane( var_0 );
}

playac130infilloopanims( var_0 )
{
    if ( isdefined( var_0.movingc130 ) )
    {
        var_0.movingc130 scriptmodelplayanim( "sdr_mp_infil_ac130_loop2_plane", "plane" );
        var_0.movingc130.innards scriptmodelplayanim( "sdr_mp_infil_ac130_loop2_plane", "planeInnards" );
    }

    var_0.playerpositionents["parent"] scriptmodelplayanim( "sdr_mp_infil_ac130_loop_genpropx10", "prop" );
}

infilvideopreload()
{
    var_0 = "mp_donetsk_c130_intro";
    preloadcinematicforall( var_0 );
}

infilvideoplay()
{
    thread scripts\mp\music_and_dialog::stopsuspensemusic();
    var_0 = "mp_donetsk_c130_intro";
    setglobalsoundcontext( "lobby_fade", "", 2 );

    foreach ( var_2 in level.players )
    {
        var_2 playlocalsound( "br_infil_part1_lr" );
        var_2 clearsoundsubmix( "mp_br_lobby_fade", 1.5 );
        var_2 setsoundsubmix( "fade_to_black_all_except_music_and_scripted5", 0.5 );
        var_3 = game["music"]["br_infil_intro"].size - 1;
        var_4 = randomint( var_3 );
        var_2 setplayermusicstate( game["music"]["br_infil_intro"][var_4] );
    }

    playcinematicforall( var_0 );

    foreach ( var_2 in level.players )
    {
        if ( !istrue( var_2.latetoinfil ) )
            var_2 setclientomnvar( "ui_br_bink_overlay_state", 3 );
    }
}

infilvideocompletecallback( var_0, var_1 )
{
    if ( var_0 == "bink_complete" )
    {
        self setclientomnvar( "ui_br_bink_overlay_state", 0 );
        self preloadcinematicforplayer();
    }
}

infilvideowaituntilcomplete()
{
    scripts\mp\utility\lui_game_event_aggregator::registeronluieventcallback( ::infilvideocompletecallback );
    wait 3.2;
}

beginbrc130playeraniminfilsequence( var_0, var_1 )
{
    foreach ( var_3 in level.players )
        var_3 setpredictedstreamloaddist( -1.0 );

    level.infilstruct = spawnstruct();
    level.infilstruct.playersinc130 = 0;

    if ( !isdefined( var_0 ) )
        var_0 = scripts\mp\gametypes\br_c130::createtestc130path();

    level.infilstruct.c130pathstruct = var_0;
    level.infilstruct.transporttime = scripts\mp\gametypes\br_c130::spawnc130( level.infilstruct.c130pathstruct );
    level.infilstruct.firstc130endtime = level.infilstruct.transporttime + gettime();
    var_5 = buildac130infilanimstruct( level.br_ac130, var_1 );
    infilvideopreload();

    if ( isdefined( level.preinfilstreamfunc ) )
        [[ level.preinfilstreamfunc ]]( var_5 );

    level.infilcinematicactive = 1;
    level.allowprematchdamage = 0;
    level.br_ac130 thread gunship_updateplayercount();
    transitionplayerstoac130cinematic( level.players, var_1, var_5.staticc130 );

    if ( scripts\mp\gametypes\br_public::isbotpracticematch() || scripts\mp\gametypes\br_public::isdmzbotpracticematch() )
    {
        foreach ( var_3 in level.players )
        {
            if ( isplayer( var_3 ) )
                var_3 notify( "play_intro" );
        }
    }

    infilvideoplay();
    infilvideowaituntilcomplete();
    level thread infilallfadetoblack( 0.0, 3.45, 0.6 );
    level.latejoinersanimstruct = var_5;
    playac130infilanim( var_5 );
    transitionplayersoutofac130cinematic( level.players, var_1 );
    level.infilcinematicactive = 0;
    level.infilstruct.infil_anim_type = var_1;
    scripts\mp\gametypes\br_public::brleaderdialog( "match_start" );
    var_8 = scripts\mp\gametypes\br_public::istutorial() || scripts\mp\gametypes\br_public::isdmztutorial();

    if ( !var_8 )
    {
        var_9 = getdvar( "scr_br_lateSpawnFallback" ) == "";

        foreach ( var_3 in level.players )
        {
            if ( !istrue( var_3.br_isininfil ) && var_9 )
                continue;

            var_3 thread playerjoininfil();

            if ( var_3 scriptablegetmidpoint() )
                registerheadlessinfil( var_3 );
        }
    }

    if ( isdefined( level.headlessinfilplayers ) )
        level thread headlessinfils();
}

infilallfadetoblack( var_0, var_1, var_2, var_3 )
{
    if ( !isdefined( level.infilblackoverlay ) )
    {
        level.infilblackoverlay = newhudelem();
        level.infilblackoverlay.x = 0;
        level.infilblackoverlay.y = 0;
        level.infilblackoverlay setshader( "black", 640, 480 );
        level.infilblackoverlay.alignx = "left";
        level.infilblackoverlay.aligny = "top";
        level.infilblackoverlay.horzalign = "fullscreen";
        level.infilblackoverlay.vertalign = "fullscreen";
        level.infilblackoverlay.sort = -1;
        level.infilblackoverlay setautoboxcalculationusingdobj( 1 );
    }

    if ( isdefined( var_0 ) && var_0 > 0 )
    {
        foreach ( var_5 in level.players )
        {
            var_5 setsoundsubmix( "iw8_br_infil_fadeout", 0.0 );
            var_5 setsoundsubmix( "mp_br_infil_music", 0.0 );
        }

        level.infilblackoverlay.alpha = 0;
        level.infilblackoverlay fadeovertime( var_0 );
        level.infilblackoverlay.alpha = 1;
        wait( var_0 );
    }

    if ( !scripts\mp\gametypes\br_public::isusinginfilselection() )
    {
        level.infilblackoverlay.alpha = 1;

        foreach ( var_5 in level.players )
        {
            var_5 setsoundsubmix( "mp_br_infil_anim", 0.0 );
            var_5 setsoundsubmix( "mp_br_infil_ac130", 0.0 );
        }
    }

    if ( isdefined( var_3 ) )
        level waittill( var_3 );

    if ( isdefined( var_1 ) && var_1 > 0 )
        wait( var_1 );

    if ( isdefined( var_2 ) && var_2 > 0 )
    {
        level.infilblackoverlay.alpha = 1;
        level.infilblackoverlay fadeovertime( var_2 );
        level.infilblackoverlay.alpha = 0;

        foreach ( var_5 in level.players )
        {
            if ( !scripts\mp\gametypes\br_public::isusinginfilselection() )
                var_5 setclienttriggeraudiozone( "mp_donetsk_infil_int", var_2 );

            var_5 clearsoundsubmix( "iw8_br_infil_fadeout", 2 );
        }

        wait( var_2 );
    }

    level.infilblackoverlay.alpha = 0;
}

infilallfadetowhite( var_0, var_1, var_2 )
{
    if ( !isdefined( level.infilwhiteoverlay ) )
    {
        level.infilwhiteoverlay = newhudelem();
        level.infilwhiteoverlay.x = 0;
        level.infilwhiteoverlay.y = 0;
        level.infilwhiteoverlay setshader( "white", 640, 480 );
        level.infilwhiteoverlay.alignx = "left";
        level.infilwhiteoverlay.aligny = "top";
        level.infilwhiteoverlay.horzalign = "fullscreen";
        level.infilwhiteoverlay.vertalign = "fullscreen";
        level.infilwhiteoverlay.sort = -1;
    }

    if ( isdefined( var_0 ) && var_0 > 0 )
    {
        level.infilwhiteoverlay.alpha = 0;
        level.infilwhiteoverlay fadeovertime( var_0 );
        level.infilwhiteoverlay.alpha = 1;

        foreach ( var_4 in level.players )
            var_4 setsoundsubmix( "iw8_mp_end_round", var_0 );

        waitandpause( var_0 );
    }

    if ( isdefined( var_1 ) && var_1 > 0 )
        waitandpause( var_1 );

    if ( isdefined( var_2 ) && var_2 > 0 )
    {
        level.infilwhiteoverlay.alpha = 1;
        level.infilwhiteoverlay fadeovertime( var_2 );
        level.infilwhiteoverlay.alpha = 0;

        foreach ( var_4 in level.players )
            var_4 clearsoundsubmix( "iw8_mp_end_round", var_2 );

        waitandpause( var_2 );
    }
}

transitionplayerstoac130cinematic( var_0, var_1, var_2 )
{
    foreach ( var_4 in var_0 )
    {
        if ( !isdefined( var_4 ) )
            continue;

        if ( isdefined( var_2 ) )
            var_4.c130 = level.br_ac130;

        var_4 scripts\mp\utility\player::hidehudenable();
    }

    scripts\mp\deathicons::removealldeathicons();
    setomnvar( "ui_hide_player_icons", 1 );
    thread infilallfadetoblack( 1, 1.5, 1, "prematch_respawn_finished" );

    foreach ( var_4 in var_0 )
    {
        if ( !isdefined( var_4 ) )
            continue;

        var_4 predictstreampos( var_2.origin, 1 );
    }

    waitandpause( 1 );
    scripts\mp\gametypes\br_vehicles::emptyallvehicles();
    setomnvar( "ui_in_infil", 1 );
    level notify( "prematch_fade_done" );
    waitforc130andforcespawnallplayers();
    level notify( "prematch_respawn_finished" );

    foreach ( var_4 in var_0 )
    {
        if ( !isdefined( var_4 ) )
            continue;

        if ( !isdefined( var_4.sessionstate ) || var_4.sessionstate == "spectator" )
            continue;

        var_4 setorigin( var_2.origin );
    }

    waitandpause( 1.5 );

    foreach ( var_4 in var_0 )
    {
        if ( !isdefined( var_4 ) )
            continue;

        var_4 clearpredictedstreampos();
        var_4 endprematchskydiving();
        var_4.br_isininfil = 1;
    }

    if ( var_1 == "script_model" )
    {
        foreach ( var_4 in var_0 )
        {
            if ( !isdefined( var_4 ) )
                continue;

            var_4 playerhide();
        }
    }
}

transitionplayersoutofac130cinematic( var_0, var_1 )
{
    var_2 = var_1 == "script_model";

    foreach ( var_4 in var_0 )
    {
        if ( scripts\mp\gametypes\br::get_int_or_0( var_4.hidehudenabled ) > 0 )
            var_4 scripts\mp\utility\player::hidehuddisable();

        var_4 visionsetfadetoblackforplayer( "", 1.0 );

        if ( var_2 )
            var_4 playershow();
    }

    setomnvar( "ui_in_infil", -1 );
}

gunship_updateplayercount()
{
    level endon( "game_ended" );
    self notify( "ac130_player_count" );
    self endon( "ac130_player_count" );

    for (;;)
    {
        setomnvar( "ui_br_players_left_in_plane", level.infilstruct.playersinc130 );

        if ( !isdefined( self ) )
            break;

        wait 0.5;
    }
}

playerjoininfil()
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    self notify( "joining_Infil" );
    var_0 = self;
    var_0.br_infilstarted = 1;
    var_0.health = var_0.maxhealth;
    var_0 scripts\mp\gametypes\br_c130::spawnplayertoc130();
    var_0 playersetupcontrolsforinfil();
    var_0 scripts\mp\gametypes\br_public::updatebrscoreboardstat( "isInInfilPlane", 1 );
    level.infilstruct.playersinc130++;
    var_0 thread playercleanupinfilondisconnect();
}

playercleanupinfilondisconnect()
{
    level endon( "game_ended" );
    self endon( "death" );
    self endon( "cancel_c130" );
    self endon( "br_jump" );
    self waittill( "disconnect" );

    if ( isdefined( level.infilstruct ) && isdefined( level.infilstruct.playersinc130 ) )
        level.infilstruct.playersinc130--;
}

playersetupcontrolsforinfil( var_0 )
{
    if ( !isdefined( var_0 ) )
        var_0 = 0;

    self setclientomnvar( "ui_br_infil_started", 1 );
    self setclientomnvar( "ui_br_infiled", 0 );

    if ( !var_0 )
        self notifyonplayercommand( "halo_jump_c130", "+gostand" );
    else
        self notifyonplayercommand( "halo_jump_solo_c130", "+gostand" );

    self notifyonplayercommand( "br_pass_squad_leader", "+usereload" );
    self notifyonplayercommand( "br_pass_squad_leader", "+activate" );
}

getlightingvalues()
{

}

lightsshot02()
{

}

lightsreset()
{

}

initinfillocationselectionhandlers()
{
    registerinfillocationselectionhandler( "exclusion", ::handleexclusionils, ::spawnselectionbegin, ::spawnselectionend );
}

handleinfillocationselection( var_0 )
{
    var_1 = self;
    var_2 = level.infilselectionmethod;
    var_3 = getinfillocationselectionfunc( var_2 );

    if ( !isdefined( var_3 ) )
        return;

    return var_1 [[ var_3 ]]( var_0.location, var_0.angles );
}

registerinfillocationselectionhandler( var_0, var_1, var_2, var_3 )
{
    if ( !isdefined( level.br_infillocationselectionhandlers ) )
        level.br_infillocationselectionhandlers = [];

    var_4 = spawnstruct();
    var_4.locationselectionfunc = var_1;
    var_4.spawnselectstartfunc = var_2;
    var_4.spawnselectendfunc = var_3;
    level.br_infillocationselectionhandlers[var_0] = var_4;
}

getinfillocationselectionfunc( var_0 )
{
    if ( !isdefined( level.br_infillocationselectionhandlers ) )
        return undefined;

    var_1 = level.br_infillocationselectionhandlers[var_0];

    if ( !isdefined( var_1 ) )
        return undefined;

    return var_1.locationselectionfunc;
}

handleexclusionils( var_0, var_1 )
{
    var_2 = self;

    if ( !istrue( level.cansolospawn ) && !istrue( var_2.issquadleader ) )
        return 0;

    [var_4, var_5] = getspawnselectionpoi( var_0 );
    var_6 = getspawnselectionexclusionsize( var_0, var_4, var_5 );

    if ( isdefined( var_2.team ) )
    {
        var_7 = scripts\mp\utility\player::getteamarray( var_2.team );
        var_6 = var_6 * var_7.size;
    }

    if ( istrue( level.cansolospawn ) && !istrue( var_2.issquadleader ) )
        return var_2 handlesoloexclusionils( var_0, var_1, var_6 );

    foreach ( var_9 in level.br_spawns )
    {
        var_10 = var_2 getsquadspawnstruct();

        if ( isdefined( var_10 ) && var_9 == var_10 )
        {
            if ( level.cansolospawn )
            {
                if ( var_2 checksolospawnselections( var_9, var_6, var_0, 1 ) )
                    return 1;
            }

            continue;
        }
        else if ( level.cansolospawn )
        {
            if ( !var_2 checksolospawnselections( var_9, var_6, var_0, 0 ) )
                return 0;
        }

        if ( pow( var_6 + var_9.spawnexclusion2ddist, 2 ) > distance2dsquared( var_9.locationorigin, var_0 ) )
        {
            var_2 thread sendplayerstatusmessage( 50, 2.0 );
            var_2 playlocalsound( "br_map_selection_error" );
            return 0;
        }
    }

    return var_2 registerspawnlocation( var_0, var_1, var_6 );
}

handlesoloexclusionils( var_0, var_1, var_2 )
{
    var_3 = self;

    foreach ( var_5 in level.br_spawns )
    {
        var_6 = getsquadspawnstruct();
        var_7 = 0;

        if ( isdefined( var_6 ) && var_5 == var_6 )
            var_7 = 1;

        if ( pow( var_2 + var_5.spawnexclusion2ddist, 2 ) > distance2dsquared( var_5.locationorigin, var_0 ) )
        {
            if ( var_7 )
            {
                var_8 = var_3 getsolospawnstruct();
                deletesolospawnstruct( var_8 );
                var_3 thread sendplayerstatusmessage( 56, 2.0 );
                var_3 playlocalsound( "br_map_selection_placed" );
                return 1;
            }

            var_3 thread sendplayerstatusmessage( 50, 2.0 );
            var_3 playlocalsound( "br_map_selection_error" );
            return 0;
        }

        if ( var_7 && var_3 checksolospawnselections( var_5, var_2, var_0, var_7 ) )
            return 1;
    }

    return var_3 registerspawnlocation( var_0, var_1, var_2 );
}

checksolospawnselections( var_0, var_1, var_2, var_3 )
{
    var_4 = self;

    foreach ( var_6 in var_0.solospawn )
    {
        if ( !isdefined( var_6 ) )
            continue;

        var_7 = var_4 getsolospawnstruct();

        if ( isdefined( var_7 ) && var_6 == var_7 )
            continue;

        if ( pow( var_1 + var_6.spawnexclusion2ddist, 2 ) > distance2dsquared( var_6.locationorigin, var_2 ) )
        {
            if ( !var_3 )
            {
                var_4 thread sendplayerstatusmessage( 50, 2.0 );
                var_4 playlocalsound( "br_map_selection_error" );
                return 0;
            }

            var_2 = var_6.locationorigin;
            var_8 = var_6.locationangles;
            var_1 = var_6.spawnexclusion2ddist;

            if ( isdefined( var_7 ) && isdefined( var_7.circleent ) )
                var_7.circleent delete();

            var_9 = var_4 registerspawnlocation( var_2, var_8, var_1 );

            if ( !var_9 )
                return var_9;

            if ( !istrue( var_4.issquadleader ) )
                var_4 thread sendplayerstatusmessage( 55, 2.0 );
            else
                var_4 thread sendplayerstatusmessage( 54, 2.0 );

            return var_9;
        }
    }

    if ( !var_3 )
        return 1;

    return 0;
}

sendplayerstatusmessage( var_0, var_1 )
{
    var_2 = self;
    var_2 notify( "sendPlayerStatusMessage" );
    var_2 endon( "sendPlayerStatusMessage" );
    var_2 scripts\mp\utility\lower_message::setlowermessageomnvar( var_0 );

    if ( isdefined( var_1 ) )
    {
        wait( var_1 );
        var_2 scripts\mp\utility\lower_message::setlowermessageomnvar( 0 );
    }
}

registerspawnlocation( var_0, var_1, var_2 )
{
    var_3 = self;
    var_4 = scripts\engine\trace::create_default_contents( 1 );

    if ( istrue( var_3.issquadleader ) )
    {
        var_5 = var_3 getsquadspawnstruct();

        if ( !isdefined( var_5 ) )
            var_5 = var_3 initsquadspawnstruct();
    }
    else if ( istrue( level.cansolospawn ) )
    {
        var_5 = var_3 getsolospawnstruct();

        if ( !isdefined( var_5 ) )
            var_5 = var_3 initsolospawnstruct();
    }
    else
        return 0;

    var_6 = getdvarfloat( "scr_infil_plus_spawn_height", 5500.0 );
    var_7 = ( 0, 0, var_6 );
    var_8 = ( 0, 0, 10000 );
    var_9 = var_0 + var_8;
    var_10 = var_0 - var_8;
    var_11 = scripts\engine\trace::ray_trace( var_9, var_10, undefined, var_4 );
    var_12 = var_0;

    if ( var_11["hittype"] != "hittype_none" )
        var_12 = var_11["position"];

    var_5.locationorigin = var_12 + var_7;

    if ( istrue( var_3.issquadleader ) )
        var_5.groundorigin = var_12;

    var_5.locationangles = var_1;
    var_5.spawnexclusion2ddist = var_2;
    [var_14, var_15, var_16] = var_5.locationorigin;

    if ( isdefined( var_5.circleent ) )
        var_5.circleent.origin = ( var_14, var_15, var_2 );
    else
    {
        var_5.circleent = spawnmapcircle( var_14, var_15, var_2, var_3 );

        if ( istrue( var_3.issquadleader ) )
            var_5.circleent setmapcircleiconindex( 1 );
    }

    var_17 = scripts\mp\utility\teams::getfriendlyplayers( var_3.team, 0 );

    foreach ( var_19 in var_17 )
    {
        if ( !istrue( var_3.issquadleader ) )
        {
            var_19 thread sendplayerstatusmessage( 64, 2.0 );
            var_19 playlocalsound( "br_map_selection_placed" );
            continue;
        }

        var_19 thread sendplayerstatusmessage( 57, 2.0 );
        var_19 playlocalsound( "br_map_selection_placed" );
    }

    return 1;
}

assignrandomspawnselection()
{
    var_0 = self;

    if ( !isdefined( var_0.issquadleader ) )
    {
        var_0.issquadleader = 1;
        var_1 = scripts\mp\utility\teams::getfriendlyplayers( var_0.team, 0 );

        foreach ( var_3 in var_1 )
        {
            if ( var_3 != var_0 )
                var_3.issquadleader = 0;
        }
    }

    var_5 = ( 0, 0, 0 );

    for ( var_6 = 0; var_6 < 3; var_6++ )
    {
        var_7 = randomfloatrange( level.mapsafecorners[1][0], level.mapsafecorners[0][0] );
        var_8 = randomfloatrange( level.mapsafecorners[1][1], level.mapsafecorners[0][1] );
        var_5 = ( var_7, var_8, 0 );
        var_9 = var_0 handleexclusionils( var_5 );

        if ( var_9 )
            return 1;
    }

    var_0 registerspawnlocation( var_5, undefined, getdvarint( "scr_map_selection_dense_min", 2000 ) );
    return 0;
}

notifyafkofselection( var_0 )
{
    var_1 = self;
    var_2 = scripts\mp\utility\teams::getfriendlyplayers( var_1.team, 0 );
    var_3 = "";

    if ( var_0 )
        var_3 = "Safe Spawn Selection Assigned";
    else
        var_3 = "Unsafe Spawn Selection Assigned";

    foreach ( var_5 in var_2 )
        var_5 iprintlnbold( var_3 );
}

teleportplayertoselection()
{
    var_0 = self;
    var_0 playershow( 1 );
    var_0 unlink( 1 );
    var_1 = var_0 getsquadspawnstruct();

    if ( isdefined( var_1.locationorigin ) )
    {
        var_2 = var_1.locationorigin;
        var_3 = var_0 getsolospawnstruct();

        if ( isdefined( var_3 ) )
            var_2 = var_3.locationorigin;

        var_4 = 512;
        var_5 = ( 0, 60 * var_0.br_squadindex % 360, 0 );
        var_6 = anglestoforward( var_5 ) * var_4;
        var_2 = var_2 + var_6 + ( 0, 0, randomfloatrange( 0, 512 ) );

        if ( getdvarint( "scr_br_fallbackinfilspawn", 0 ) )
        {
            var_0.forcespawnorigin = var_2;
            var_0.forcespawnangles = undefined;
            var_0.alreadyaddedtoalivecount = 1;
            var_0 scripts\mp\playerlogic::spawnplayer( 0, 0 );
        }
        else
        {
            var_0 setorigin( var_2, 1 );
            var_0 setplayerangles( var_5 );
        }
    }

    var_0 stopanimscriptsceneevent();
    var_0 clearpredictedstreampos();
    var_0 playershow( 1 );
    var_0.br_infilstarted = 1;
    var_0 setclientomnvar( "ui_br_infil_started", 1 );
    var_0 setclientomnvar( "ui_br_infiled", 1 );
    var_0 scripts\cp_mp\parachute::startfreefall( 0, 0 );
    var_0 scripts\mp\gametypes\br_weapons::br_ammo_player_clear();
    scripts\mp\gametypes\br_weapons::br_ammo_update_weapons( var_0 );
}

postspawnselectionstream()
{
    var_0 = self;
    var_1 = var_0 getsolospawnstruct();
    var_2 = var_0 getsquadspawnstruct();

    if ( isdefined( var_1 ) )
        var_0 predictstreampos( var_1.locationorigin, 1 );
    else if ( isdefined( var_2 ) )
        var_0 predictstreampos( var_2.locationorigin, 1 );
}

spawnselectionbegin()
{
    setomnvar( "ui_match_start_text", "prepare_for_infil" );
    scripts\mp\gamelogic::matchstarttimerperplayer_internal( 10 );
    scripts\mp\flags::gameflaginit( "end_spawn_selection", 0 );
    level notify( "begin_infil_map_selection" );

    if ( !isdefined( level.br_spawns ) )
        level.br_spawns = [];

    foreach ( var_1 in level.players )
    {
        var_1 thread scripts\mp\gametypes\br::playerselectspawnsequence();
        var_1.isselectingspawn = 1;
    }

    wait 2.0;
    setomnvar( "ui_br_map_spawn", 1 );
}

spawnselectionend()
{
    scripts\mp\flags::gameflagset( "end_spawn_selection" );
    var_0 = getdvarint( "scr_sendAfkToGulag", 0 );

    foreach ( var_2 in level.players )
    {
        var_2 notify( "cancel_location" );
        var_2 thread sendplayerstatusmessage( 51, 2.0 );
        var_3 = var_2 getsquadspawnstruct();

        if ( !isdefined( var_3 ) )
        {
            if ( var_0 )
            {
                var_2.brmapselectionafk = 1;
                continue;
            }
            else
            {
                var_4 = var_2 assignrandomspawnselection();
                var_2 notifyafkofselection( var_4 );
            }
        }

        var_2.brmapselectionafk = 0;
        var_2.isselectingspawn = 0;
        var_2 postspawnselectionstream();
    }

    thread removespawnselections();
    wait 4;

    foreach ( var_2 in level.players )
    {
        var_2 thread sendplayerstatusmessage( 0 );
        var_2 scripts\mp\gametypes\br_public::updatebrscoreboardstat( "jumpMasterState", 0 );
    }

    thread waitteardowninfilmapomnvars();
}

waitteardowninfilmapomnvars()
{
    level endon( "game_ended" );
    level waittill( "infils_ready" );
    setomnvar( "ui_br_map_spawn", 0 );
}

getsolospawnstruct()
{
    var_0 = self;

    if ( !istrue( level.cansolospawn ) || istrue( var_0.issquadleader ) )
        return undefined;

    var_1 = var_0 getsquadspawnstruct();

    if ( isdefined( var_0.br_squadindex ) && isdefined( var_1 ) )
    {
        if ( isdefined( var_1.solospawn[var_0.br_squadindex] ) && isdefined( var_1.solospawn[var_0.br_squadindex].locationorigin ) )
            return var_1.solospawn[var_0.br_squadindex];
    }

    return undefined;
}

getsquadspawnstruct()
{
    var_0 = self;

    if ( isdefined( level.br_spawns ) && isdefined( var_0.team ) && isdefined( level.br_spawns[var_0.team] ) && isdefined( level.br_spawns[var_0.team].locationorigin ) )
        return level.br_spawns[var_0.team];

    return undefined;
}

initsolospawnstruct()
{
    var_0 = self;

    if ( !istrue( level.cansolospawn ) || istrue( var_0.issquadleader ) )
        return undefined;

    var_1 = var_0 getsquadspawnstruct();

    if ( isdefined( var_1 ) && isdefined( var_0.br_squadindex ) )
    {
        var_1.solospawn[var_0.br_squadindex] = spawnstruct();
        var_1.solospawn[var_0.br_squadindex].circleent = undefined;
        return var_1.solospawn[var_0.br_squadindex];
    }

    return undefined;
}

initsquadspawnstruct()
{
    var_0 = self;

    if ( !istrue( var_0.issquadleader ) )
        return undefined;

    if ( isdefined( level.br_spawns ) && isdefined( var_0.team ) )
    {
        level.br_spawns[var_0.team] = spawnstruct();
        level.br_spawns[var_0.team].circleent = undefined;
        level.br_spawns[var_0.team].solospawn = [];
        return level.br_spawns[var_0.team];
    }

    return undefined;
}

deletesolospawnstruct( var_0 )
{
    if ( isdefined( var_0.circleent ) )
        var_0.circleent delete();

    var_1 = undefined;
}

deletesquadspawnstruct( var_0 )
{
    if ( isdefined( var_0.circleent ) )
        var_0.circleent delete();

    var_0 = undefined;
}

classselectionbeginnonexclusion()
{
    scripts\mp\flags::gameflaginit( "end_spawn_selection", 0 );

    foreach ( var_1 in level.players )
        var_1 thread scripts\mp\gametypes\br::playerstartselectspawnclassnonexclusion();
}

classselectionendnonexclusion()
{
    scripts\mp\flags::gameflagset( "end_spawn_selection" );
}

removespawnselections()
{
    wait 25;

    if ( isdefined( level.br_spawns ) )
    {
        foreach ( var_1 in level.br_spawns )
        {
            if ( isdefined( var_1.solospawn ) )
            {
                foreach ( var_3 in var_1.solospawn )
                    deletesolospawnstruct( var_3 );
            }

            deletesquadspawnstruct( var_1 );
        }
    }
}

getspawnselectionlockedtimer()
{
    return 5;
}

spawnselectioninfil( var_0 )
{
    foreach ( var_2 in level.players )
    {
        var_2.br_infilstarted = 1;
        var_2 setclientomnvar( "ui_br_infil_started", 1 );
        var_2 setclientomnvar( "ui_br_infiled", 1 );
    }

    var_4 = buildac130infilanimstruct( undefined, var_0 );
    playac130infilanim( var_4 );
}

initspawnexclusionpois()
{
    setdvarifuninitialized( "scr_map_selection_sparse_min", 813 );
    setdvarifuninitialized( "scr_map_selection_sparse_max", 1000 );
    setdvarifuninitialized( "scr_map_selection_semidense_min", 625 );
    setdvarifuninitialized( "scr_map_selection_semidense_max", 813 );
    setdvarifuninitialized( "scr_map_selection_dense_min", 500 );
    setdvarifuninitialized( "scr_map_selection_dense_max", 625 );
    setdvarifuninitialized( "scr_map_selection_falloff_max_distance", 25000 );
    setdvarifuninitialized( "scr_map_selection_falloff_fxn", "continuous" );
    level.br_spawnsparsepois = [ "boneyard", "farm", "lumber", "dam", "smallAirport", "quarry" ];
    level.br_spawnsemidensepois = [ "transit", "hospital", "port", "stadium", "tvStation", "storagetown", "supermarket" ];
    level.br_spawndensepois = [ "gulag", "northDowntown", "southDowntown", "eastAirport", "westAirport" ];
    var_0 = getdvarint( "scr_map_selection_sparse_min" );
    var_1 = getdvarint( "scr_map_selection_sparse_max" );

    foreach ( var_3 in level.br_spawnsparsepois )
    {
        level.br_spawnpois[var_3] = spawnstruct();
        level.br_spawnpois[var_3].exclusionmin = var_0;
        level.br_spawnpois[var_3].exclusionmax = var_1;
    }

    var_5 = getdvarint( "scr_map_selection_semidense_min" );
    var_6 = getdvarint( "scr_map_selection_semidense_max" );

    foreach ( var_3 in level.br_spawnsemidensepois )
    {
        level.br_spawnpois[var_3] = spawnstruct();
        level.br_spawnpois[var_3].exclusionmin = var_5;
        level.br_spawnpois[var_3].exclusionmax = var_6;
    }

    var_9 = getdvarint( "scr_map_selection_dense_min" );
    var_10 = getdvarint( "scr_map_selection_dense_max" );

    foreach ( var_3 in level.br_spawndensepois )
    {
        level.br_spawnpois[var_3] = spawnstruct();
        level.br_spawnpois[var_3].exclusionmin = var_9;
        level.br_spawnpois[var_3].exclusionmax = var_10;
    }

    level.br_spawnpois["transit"].pos = ( -12420, -26792, 0 );
    level.br_spawnpois["boneyard"].pos = ( -26542, -21776, 0 );
    level.br_spawnpois["hospital"].pos = ( 7827, -22240, 0 );
    level.br_spawnpois["port"].pos = ( 35008, -37117, 0 );
    level.br_spawnpois["farm"].pos = ( 48757, -25620, 0 );
    level.br_spawnpois["gulag"].pos = ( 51019, -52257, 0 );
    level.br_spawnpois["lumber"].pos = ( 51048, -8557, 0 );
    level.br_spawnpois["stadium"].pos = ( 28873, -9839, 0 );
    level.br_spawnpois["tvStation"].pos = ( 14423, 4999, 0 );
    level.br_spawnpois["northDowntown"].pos = ( 20311, -18724, 0 );
    level.br_spawnpois["southDowntown"].pos = ( 22076, -29372, 0 );
    level.br_spawnpois["storagetown"].pos = ( -24594, -3984, 0 );
    level.br_spawnpois["supermarket"].pos = ( -12782, -3634, 0 );
    level.br_spawnpois["eastAirport"].pos = ( -8280, 5837, 0 );
    level.br_spawnpois["westAirport"].pos = ( -21055, 7124, 0 );
    level.br_spawnpois["dam"].pos = ( -26873, 32208, 0 );
    level.br_spawnpois["smallAirport"].pos = ( 5823, 38518, 0 );
    level.br_spawnpois["quarry"].pos = ( 32653, 26929, 0 );
}

getspawnselectioncontexclusiongrowth( var_0, var_1, var_2, var_3 )
{
    var_4 = getdvarint( "scr_map_selection_falloff_max_distance" );
    var_5 = distance2d( var_0, var_1 );

    if ( var_5 > var_4 )
        return getdvarint( "scr_map_selection_exclusion", 2800 );

    var_6 = log( var_3 ) / ( log( var_2 ) * var_4 );
    var_7 = var_2 * exp( var_6 * var_5 );
    return var_7;
}

getspawnselectionconstexclusiongrowth( var_0, var_1, var_2, var_3 )
{
    var_4 = var_2 / var_3;
    var_5 = getdvarint( "scr_map_selection_falloff_max_distance" );
    var_6 = distance2d( var_0, var_1 );

    if ( var_6 > var_5 )
        return getdvarint( "scr_map_selection_exclusion", 2800 );

    var_7 = var_6 / var_5;
    var_8 = var_2 * pow( 1 + var_4, var_7 );
    return var_8;
}

getspawnselectionlerpexclusiongrowth( var_0, var_1, var_2, var_3 )
{
    var_4 = getdvarint( "scr_map_selection_falloff_max_distance" );
    var_5 = distance2d( var_0, var_1 );

    if ( var_5 > var_4 )
        return getdvarint( "scr_map_selection_exclusion", 2800 );

    var_6 = var_5 / var_4;
    var_7 = scripts\engine\math::lerp( var_2, var_3, var_6 );
    return var_7;
}

getspawnselectionpoi( var_0 )
{
    var_1 = 2147483647;
    var_2 = undefined;

    foreach ( var_6, var_4 in level.br_spawnpois )
    {
        var_5 = distance2d( var_0, var_4.pos );

        if ( var_5 < var_1 )
        {
            var_1 = var_5;
            var_2 = var_6;
        }
    }

    return [ var_1, var_2 ];
}

getspawnselectionexclusionsize( var_0, var_1, var_2 )
{
    var_3 = getdvar( "scr_map_selection_falloff_fxn", "continuous" );
    var_4 = level.br_spawnpois[var_2];

    switch ( var_3 )
    {
        case "continuous":
            var_4.spawnexclusion2ddist = getspawnselectioncontexclusiongrowth( var_4.pos, var_0, var_4.exclusionmin, var_4.exclusionmax );
            break;
        case "constant":
            var_4.spawnexclusion2ddist = getspawnselectionconstexclusiongrowth( var_4.pos, var_0, var_4.exclusionmin, var_4.exclusionmax );
            break;
        case "lerp":
            var_4.spawnexclusion2ddist = getspawnselectionlerpexclusiongrowth( var_4.pos, var_0, var_4.exclusionmin, var_4.exclusionmax );
            break;
        default:
            var_4.spawnexclusion2ddist = getdvarint( "scr_map_selection_exclusion", 2800 );
    }

    return var_4.spawnexclusion2ddist;
}

getinfilspawnoffset()
{
    if ( istrue( level.infilcanusemap ) )
        return getdvarfloat( "scr_map_selection_height_offset", 2000 );

    return getdvarfloat( "scr_br_dropSpawnOffsetMinZ", 12000 );
}

waitandpause( var_0 )
{
    wait( var_0 );
}

movetowithpause( var_0, var_1, var_2, var_3 )
{
    self moveto( var_0, var_1, var_2, var_3 );
}

rotatetowithpause( var_0, var_1, var_2, var_3 )
{
    self rotateto( var_0, var_1, var_2, var_3 );
}

headlessinfils()
{
    var_0 = distance( level.br_ac130.pathstruct.startpt, level.br_ac130.pathstruct.endpt );
    var_1 = var_0 / scripts\mp\gametypes\br_c130::getc130speed() / level.headlessinfilplayers.size;

    for ( var_2 = 0; var_2 < level.headlessinfilplayers.size; var_2++ )
    {
        wait( var_1 );
        level.headlessinfilplayers[var_2] notify( "halo_jump_c130" );
    }

    level.headlessinfilplayers = undefined;
}

registerheadlessinfil( var_0 )
{
    if ( !isdefined( level.headlessinfilplayers ) )
        level.headlessinfilplayers = [];

    level.headlessinfilplayers[level.headlessinfilplayers.size] = var_0;
}
