// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    level.averagealliesz = 0;
    level.loot_choppers = [];
    scripts\cp_mp\utility\script_utility::registersharedfunc( "br_lootchopper", "lootChopper_onCrateUse", ::lootchopper_oncrateuse );
}

lootchopper_initspawninfo( var_0 )
{
    var_1 = lootchopper_getspawnlocations( var_0 );
    level.loot_chopper_spawns = [];
    level.loot_chopper_spawns["quad_1"] = [];
    level.loot_chopper_spawns["quad_2"] = [];
    level.loot_chopper_spawns["quad_3"] = [];
    level.loot_chopper_spawns["quad_4"] = [];

    if ( !isdefined( var_1 ) )
        return;

    foreach ( var_3 in var_1 )
    {
        var_4 = undefined;
        var_5 = undefined;
        var_6 = undefined;

        if ( var_0.isvalid )
        {
            foreach ( var_10, var_8 in var_0.quadpoints )
            {
                var_9 = distance2dsquared( var_3.origin, var_8 );

                if ( !isdefined( var_4 ) || var_9 < var_4 )
                {
                    var_4 = var_9;
                    var_5 = var_8;
                    var_6 = "quad_" + ( var_10 + 1 );
                }
            }
        }
        else
        {
            foreach ( var_10, var_8 in level.quadgridcenterpoints )
            {
                var_9 = distance2dsquared( var_3.origin, var_8 );

                if ( !isdefined( var_4 ) || var_9 < var_4 )
                {
                    var_4 = var_9;
                    var_5 = var_8;
                    var_6 = "quad_" + ( var_10 + 1 );
                }
            }
        }

        var_3.origin = var_3.origin * ( 1, 1, 0 );
        var_3.origin = scripts\mp\gametypes\br::getoffsetspawnorigin( var_3.origin, ( 0, 0, 10000 ) );
        level.loot_chopper_spawns[var_6][level.loot_chopper_spawns[var_6].size] = var_3;
    }
}

lootchopper_getspawnlocations( var_0 )
{
    var_1 = [];
    var_0 = scripts\mp\gametypes\br_circle::getrandompointincurrentcircle( );
    foreach ( var_3 in level.br_prematchspawnlocations )
    {
        if ( var_0.isvalid )
        {
            if ( distance2dsquared( var_3.origin, var_0.center ) > var_0.radius * var_0.radius )
                continue;
        }

        var_4 = spawnstruct();
        var_4.origin = scripts\mp\gametypes\br_circle::getrandompointincurrentcircle() + ( 0 , 0 , 4000);
        var_1[var_1.size] = var_4;
    }

    return var_1;
}

lootchopper_initcircleinfo( var_0, var_1 )
{
    var_2 = spawnstruct();
    var_2.isvalid = isdefined( var_0 ) && isdefined( var_1 );

    if ( var_2.isvalid )
    {
        var_2.center = var_0;
        var_2.radius = var_1;
        var_3 = 45.0;
        var_4 = cos( var_3 );
        var_5 = sin( var_3 );
        var_2.quadpoints[0] = var_0 + ( -1.0 * var_4, var_5, 0 ) * var_1 * 0.5;
        var_2.quadpoints[1] = var_0 + ( var_4, var_5, 0 ) * var_1 * 0.5;
        var_2.quadpoints[2] = var_0 + ( var_4, -1.0 * var_5, 0 ) * var_1 * 0.5;
        var_2.quadpoints[3] = var_0 + ( -1.0 * var_4, -1.0 * var_5, 0 ) * var_1 * 0.5;
    }

    return var_2;
}

lootchopper_managespawns()
{
    level endon( "game_ended" );

    if ( scripts\mp\gametypes\br_public::isdmztutorial() )
        return;

    var_0 = undefined;
    var_1 = undefined;

    if ( isdefined( level.br_circle ) && isdefined( level.br_circle.safecircleent ) )
    {
        var_0 = scripts\mp\gametypes\br_circle::getsafecircleorigin();
        var_1 = scripts\mp\gametypes\br_circle::getsafecircleradius();
    }

    var_2 = lootchopper_initcircleinfo( var_0, var_1 );
    lootchopper_initspawninfo( var_2 );
    level waittill( "br_prematchEnded" );
    var_3 = getdvarint( "scr_dmz_lc_max_active", 5 );
    var_4 = getdvarint( "scr_dmz_lc_min_spawn_dist", 6000 );
    var_5 = getdvarint( "scr_dmz_lc_spawn_cooldown_min", 360 );
    var_6 = getdvarint( "scr_dmz_lc_spawn_cooldown_max", 480 );

    if ( level.mapname == "mp_br_mechanics" )
        var_4 = 1000;

    for (;;)
    {
        var_7 = getdvarint( "scr_dmz_lc_active", 0 );

        if ( !var_7 )
        {
            waitframe();
            continue;
        }

        var_8 = randomintrange( var_5, var_6 );

        if ( istrue( level.usemilestonephases ) )
            scripts\mp\flags::gameflagwait( "activate_cash_helis" );
        else
            wait( var_8 );

        if ( level.loot_choppers.size < var_3 )
        {
            var_9 = var_3 - level.loot_choppers.size;

            for ( var_10 = 0; var_10 < var_9; var_10++ )
            {
                var_11 = var_10 + 1;

                if ( var_11 > 4 )
                    var_11 = 1;

                var_12 = lootchopper_findunoccupiedpatrolzone( level.loot_chopper_spawns["quad_" + var_11], var_4 );

                if ( !isdefined( var_12 ) )
                    wait 1;

                if ( var_10 == 0 )
                    scripts\mp\gametypes\br_gametype_dmz::showsplashtoall( "br_lootchopper_incoming" );

                lootchopper_spawn( var_12 );

                if ( istrue( level.usemilestonephases ) )
                    wait( randomintrange( 1, 2 ) );
            }

            if ( istrue( level.usemilestonephases ) )
                return;

            continue;
        }

        while ( level.loot_choppers.size >= var_3 )
            waitframe();
    }
}

lootchopper_findunoccupiedpatrolzone( var_0, var_1 )
{
    var_2 = undefined;

    if ( var_0.size > 0 )
    {
        var_3 = [];

        foreach ( var_5 in var_0 )
        {
            if ( istrue( var_5.chopperoccupied ) )
                continue;

            if ( lootchopper_isnearbyoccupiedspawns( var_5, var_1 ) )
                continue;

            var_5.chopperoccupied = 1;
            var_3[var_3.size] = var_5;
        }

        if ( var_3.size > 0 )
            var_2 = var_3[randomint( var_3.size )];
    }

    return var_2;
}

lootchopper_isnearbyoccupiedspawns( var_0, var_1 )
{
    var_2 = 0;
    var_3 = level.loot_chopper_spawns;
    var_4 = var_1 * var_1;

    foreach ( var_6 in var_3 )
    {
        foreach ( var_8 in var_6 )
        {
            if ( istrue( var_8.chopperoccupied ) )
            {
                if ( distance2dsquared( var_0.origin, var_8.origin ) < var_4 )
                {
                    var_2 = 1;
                    break;
                }
            }
        }

        if ( istrue( var_2 ) )
            break;
    }

    return var_2;
}

lootchopper_getzonebyindex( var_0 )
{
    var_1 = undefined;
    var_2 = 0;

    foreach ( var_5, var_4 in level.loot_chopper_spawns )
    {
        if ( var_2 == var_0 )
        {
            var_1 = var_4;
            break;
        }

        var_2++;
    }

    return var_1;
}

lootchopper_spawn( var_0 )
{
    var_1 = undefined;
    var_2 = getdvarint( "scr_dmz_lc_patrol_radius", 4000 );

    if ( isdefined( var_0 ) )
        var_1 = var_0.origin;
    else
    {
        var_3 = [];

        foreach ( var_5 in level.players )
        {
            if ( scripts\mp\utility\player::isreallyalive( var_5 ) )
                var_3[var_3.size] = var_5;
        }

        if ( var_3.size > 0 )
        {
            var_7 = randomint( var_3.size );
            var_1 = var_3[var_7].origin;
        }

        if ( isdefined( var_1 ) )
            var_1 = scripts\mp\gametypes\br::getoffsetspawnorigin( var_1, ( 0, 0, 10000 ) );
    }

    if ( !isdefined( var_1 ) )
        return;

    var_8 = scripts\cp_mp\killstreaks\chopper_support::getpathstart( var_1 );
    var_9 = vectortoangles( var_1 - var_8 );
    var_10 = scripts\cp_mp\vehicles\vehicle_tracking::_spawnhelicopter( level.players[randomint( level.players.size )], var_8, var_9, "veh_chopper_support_dmz_mp", "veh8_mil_air_palfa_east" );

    if ( !isdefined( var_10 ) )
        return;

    var_10.speed = 100;
    var_10.accel = 50;
    var_10.lifetime = getdvarint( "scr_dmz_lc_lifetime", 9999 );
    var_10.team = "neutral";
    var_10.angles = var_9;
    var_10.flaresreservecount = getdvarint( "scr_dmz_lc_flares", 0 );
    var_10.currentdamagestate = 0;
    var_10.pathstart = var_8;
    var_10.pathgoal = var_1;
    var_10.currentaction = "patrol";
    var_10.currenttarget = undefined;
    var_10.heightoffset = ( 0, 0, getdvarint( "scr_dmz_lc_height", 1500 ) );
    var_10.patrolzone = var_0;
    var_10.patrollocation = var_1;
    var_10.patrolradius = var_2;
    var_10.stage3accradius = 35;
    var_10.crashoffset = var_10.heightoffset[2] - 250;
    var_10 setmaxpitchroll( 15, 15 );
    var_10 vehicle_setspeed( var_10.speed, var_10.accel );
    var_10 sethoverparams( 50, 5, 2.5 );
    var_10 setturningability( 0.5 );
    var_10 setyawspeed( 100, 25, 25, 0.1 );
    var_10 setcandamage( 1 );
    var_10 setneargoalnotifydist( 768 );
    var_10 setvehicleteam( var_10.team );
    var_10.health = getdvarint( "scr_dmz_lc_health", 5000 );
    var_10.maxhealth = getdvarint( "scr_dmz_lc_health", 5000 );
    var_10 scripts\mp\sentientpoolmanager::registersentient( "Level_Vehicle", var_10.team );
    var_10 lootchopper_setupdamagefunctionality();
    var_10 setscriptablepartstate( "blinking_lights", "on", 0 );
    var_10 setscriptablepartstate( "engine", "on", 0 );
    var_10.frontturret = spawnturret( "misc_turret", var_10 gettagorigin( "tag_turret_front" ), "chopper_support_turret_mp" );
    var_10.frontturret setmodel( "veh8_mil_air_ahotel64_turret_wm_east" );
    var_10.frontturret.team = var_10.team;
    var_10.frontturret.angles = var_10.angles;
    var_10.frontturret.turreton = 1;
    var_10.frontturret.name = "front_turret";
    var_10.frontturret.attackingtarget = undefined;
    var_10.frontturret.vehicleparent = "loot_chopper";
    var_10.frontturret linkto( var_10 );
    var_10.frontturret setturretteam( var_10.team );
    var_10.frontturret setturretmodechangewait( 0 );
    var_10.frontturret setmode( "manual" );
    var_10.frontturret setdefaultdroppitch( 45 );
    var_10.frontturret.groundtargetent = spawn( "script_model", var_10.origin );
    var_10.frontturret.groundtargetent setmodel( "tag_origin" );
    var_10.frontturret.groundtargetent dontinterpolate();
    var_10.rearturret = spawnturret( "misc_turret", var_10 gettagorigin( "tag_turret_rear" ), "chopper_support_turret_mp" );
    var_10.rearturret setmodel( "veh8_mil_air_ahotel64_turret_wm_east" );
    var_10.rearturret.team = var_10.team;
    var_10.rearturret.angles = var_10.angles;
    var_10.rearturret.turreton = 1;
    var_10.rearturret.name = "rear_turret";
    var_10.rearturret.attackingtarget = undefined;
    var_10.rearturret.vehicleparent = "loot_chopper";
    var_10.rearturret linkto( var_10 );
    var_10.rearturret setturretteam( var_10.team );
    var_10.rearturret setturretmodechangewait( 0 );
    var_10.rearturret setmode( "manual" );
    var_10.rearturret setdefaultdroppitch( 45 );
    var_10.rearturret.groundtargetent = spawn( "script_model", var_10.origin );
    var_10.rearturret.groundtargetent setmodel( "tag_origin" );
    var_10.rearturret.groundtargetent dontinterpolate();
    level.loot_choppers[level.loot_choppers.size] = var_10;
    var_10.patrolfunc = ::lootchopper_patrolzone;
    var_10.lootfunc = ::lootchopper_droploot;
    var_10.cleanupfunc = ::lootchopper_cleanup;
    var_10 lootchopper_createobjective();
    var_10 thread scripts\cp_mp\killstreaks\chopper_support::choppersupport_neargoalsettings();

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "flares", "handleIncomingStinger" ) )
        var_10 thread [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "flares", "handleIncomingStinger" ) ]]( scripts\cp_mp\killstreaks\chopper_support::choppersupport_handlemissiledetection );

    var_10 thread scripts\cp_mp\killstreaks\chopper_support::choppersupport_movetolocation( var_10.pathgoal, 1 );
    return var_10;
}

lootchopper_setupdamagefunctionality()
{
    self.vehiclename = "loot_chopper";
    scripts\mp\vehicles\damage::set_vehicle_hit_damage_data( self.vehiclename, 20 );
    lootchopper_modifyweapondamage( "iw8_la_gromeo_mp", 4.0, 20 );
    lootchopper_modifyweapondamage( "iw8_la_kgolf_mp", 4.0, 20 );
    lootchopper_modifyweapondamage( "iw8_la_rpapa7_mp", 4.0, 20 );
    lootchopper_modifyweapondamage( "iw8_la_juliet_mp", 5.0, 20 );
    lootchopper_modifyweapondamage( "iw8_la_gromeoks_mp", 4.0, 20 );
    lootchopper_modifyweapondamage( "iw8_la_mike32_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "iw8_ar_mike4_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "iw8_ar_akilo47_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "c4_mp_p", 4.0, 20 );
    lootchopper_modifyweapondamage( "semtex_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "frag_grenade_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "pop_rocket_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "molotov_mp", 1.81818, 20 );
    lootchopper_modifyweapondamage( "at_mine_ap_mp", 1.81818, 20 );
    lootchopper_modifyweapondamage( "at_mine_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "thermite_mp", 1, 36 );
    lootchopper_modifyweapondamage( "thermite_av_mp", 1, 36 );
    lootchopper_modifyweapondamage( "thermite_bolt_mp", 1, 36 );
    lootchopper_modifyweapondamage( "emp_grenade_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "claymore_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "apache_proj_mp", 5.0, 20 );
    lootchopper_modifyweapondamage( "toma_proj_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "cruise_proj_mp", 6.66667, 20 );
    lootchopper_modifyweapondamage( "artillery_mp", 6.66667, 20 );
    lootchopper_modifyweapondamage( "nuke_mp", 10.0, 20 );
    lootchopper_modifyweapondamage( "ac130_105mm_mp", 10.0, 20 );
    lootchopper_modifyweapondamage( "ac130_40mm_mp", 5.0, 20 );
    lootchopper_modifyweapondamage( "ac130_25mm_mp", 2.85714, 20 );
    lootchopper_modifyweapondamage( "hover_jet_proj_mp", 5.0, 20 );
    scripts\cp_mp\vehicles\vehicle_damage::vehicle_damage_enableownerdamage( self );
    scripts\mp\vehicles\damage::get_vehicle_mod_damage_data( self.vehiclename, 1 );
    scripts\mp\vehicles\damage::set_pre_mod_damage_callback( self.vehiclename, ::lootchopper_premodifydamage );
    scripts\mp\vehicles\damage::set_post_mod_damage_callback( self.vehiclename, ::lootchopper_postmodifydamage );
    scripts\mp\vehicles\damage::set_death_callback( self.vehiclename, ::lootchopper_handledeathdamage );
    scripts\cp_mp\vehicles\vehicle_tracking::vehicle_tracking_registerinstance( self );
}

lootchopper_modifyweapondamage( var_0, var_1, var_2 )
{
    scripts\mp\vehicles\damage::set_weapon_hit_damage_data_for_vehicle( var_0, var_1, self.vehiclename );
    scripts\mp\vehicles\damage::set_vehicle_hit_damage_data_for_weapon( self.vehiclename, var_2, var_0 );
}

lootchopper_premodifydamage( var_0 )
{
    var_1 = var_0.damage;
    var_2 = var_0.attacker;
    return 1;
}

lootchopper_postmodifydamage( var_0 )
{
    scripts\cp_mp\killstreaks\chopper_support::choppersupport_modifydamage( var_0 );

    if ( !isdefined( self.attackers ) )
        self.attackers = [];

    var_1 = lootchopper_getattackerdata( var_0.attacker );

    if ( !isdefined( var_1 ) )
    {
        var_2 = spawnstruct();
        var_2.player = var_0.attacker;
        var_2.objweapon = var_0.objweapon;
        var_2.totaldamage = var_0.damage;
        self.attackers[self.attackers.size] = var_2;
    }
    else
    {
        var_1.totaldamage = var_1.totaldamage + var_0.damage;
        var_1.objweapon = var_0.objweapon;
    }

    return 1;
}

lootchopper_handledeathdamage( var_0 )
{
    scripts\cp_mp\killstreaks\chopper_support::choppersupport_handledeathdamage( var_0 );
    var_1 = undefined;
    var_2 = undefined;
    var_3 = var_0.attacker;

    foreach ( var_5 in self.attackers )
    {
        if ( isdefined( var_5.player ) )
        {
            if ( var_3 == var_5.player )
                var_1 = "br_loot_chopper_destroyed";
            else
                var_1 = "br_loot_chopper_destroyed_assist";

            var_2 = scripts\mp\rank::getscoreinfovalue( var_1 );
            var_5.player thread scripts\mp\rank::giverankxp( var_1, var_2, var_5.objweapon );
            var_5.player thread scripts\mp\events::killeventtextpopup( var_1, 0 );
        }
    }

    self notify( "death" );
    return 1;
}

lootchopper_patrolzone( var_0 )
{
    if ( self.currentaction != "patrol" )
        self.currentaction = "patrol";
    else if ( self.currentaction == "patrol" && !istrue( var_0 ) )
        return;

    self clearlookatent();
    self setneargoalnotifydist( 300 );
    var_1 = 0;
    var_2 = 0;

    for (;;)
    {
        if ( self.currentaction == "attacking" )
        {
            if ( !istrue( var_1 ) )
                var_1 = 1;

            waitframe();
            continue;
        }

        if ( !istrue( var_0 ) && istrue( var_1 ) )
            var_1 = 0;

        var_3 = self.patrollocation + anglestoforward( ( 0, var_2, 0 ) ) * int( self.patrolradius / 1.2 );
        var_2 = var_2 + 90;
        scripts\cp_mp\killstreaks\chopper_support::choppersupport_movetolocation( var_3, 1 );

        if ( var_2 >= 360 )
            var_2 = 0;

        wait 0.5;
    }
}

lootchopper_droploot()
{
    var_0 = lootchopper_finddroplocation( self.origin + ( 0, 0, 500 ) );

    if ( isdefined( var_0 ) )
    {
        var_1 = scripts\cp_mp\killstreaks\airdrop::dropbrlootchoppercrate( self.origin, var_0 );
        var_2 = scripts\cp_mp\killstreaks\airdrop::gettriggerobject( var_1 );
        var_2.usetimeoverride = 10;
    }
}

lootchopper_finddroplocation( var_0 )
{
    var_1 = undefined;
    var_2 = var_0 - ( 0, 0, 20000 );
    var_3 = [ self, self.frontturret, self.rearturret ];
    var_4 = scripts\engine\trace::ray_trace( var_0, var_2, var_3 );

    if ( isdefined( var_4 ) && var_4["hittype"] != "hittype_none" )
        var_1 = var_4["position"];

    return var_1;
}

lootchopper_oncrateuse( var_0 )
{
    var_1 = getdvarint( "scr_dmz_lc_plunder_reward", 100000 );

    if ( istrue( level.bmoovertime ) )
    {
        var_2 = getdvarint( "scr_dmz_lc_plunder_bonus_reward", 50000 );
        var_1 = var_1 + var_2;
    }

    self.itemsdropped = 0;
    var_3 = scripts\mp\gametypes\br_plunder::dropplunderbyrarity( var_1 / 100, 10 );

    foreach ( var_5 in var_3 )
        var_5.lootsource = "loot_chopper";

    if ( !isdefined( var_0.lootcachesopened ) )
        var_0.lootcachesopened = 1;
    else
        var_0.lootcachesopened++;

    var_0 scripts\mp\utility\stats::setextrascore1( var_0.lootcachesopened );
    var_0 thread scripts\mp\utility\points::giveunifiedpoints( "br_loot_chopper_box_open" );
}

lootchopper_cleanup()
{
    if ( isdefined( self.dropzone ) )
        self.dropzone delete();

    if ( isdefined( self.patrolzone ) )
        self.patrolzone.chopperoccupied = undefined;

    if ( isdefined( self.objectiveiconid ) )
        scripts\mp\objidpoolmanager::returnobjectiveid( self.objectiveiconid );

    scripts\cp_mp\vehicles\vehicle_tracking::vehicle_tracking_deregisterinstance( self );
    level.loot_choppers = scripts\engine\utility::array_remove( level.loot_choppers, self );
}

lootchopper_createobjective()
{
    var_0 = scripts\mp\objidpoolmanager::requestobjectiveid( 1 );

    if ( var_0 != -1 )
    {
        scripts\mp\objidpoolmanager::objective_add_objective( var_0, "active", self.origin, "ui_mp_br_mapmenu_icon_boss_chopper", "icon_medium" );
        scripts\mp\objidpoolmanager::update_objective_setbackground( var_0, 1 );
        scripts\mp\objidpoolmanager::objective_playermask_showtoall( var_0 );
        scripts\mp\objidpoolmanager::update_objective_onentity( var_0, self );
        objective_sethideelevation( var_0, 1 );
    }

    self.objectiveiconid = var_0;
}

lootchopper_getattackerdata( var_0 )
{
    var_1 = undefined;

    if ( !isdefined( var_0 ) )
        return var_1;

    foreach ( var_3 in self.attackers )
    {
        if ( var_0 == var_3.player )
        {
            var_1 = var_3;
            break;
        }
    }

    return var_1;
}
