// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    var_0 = getdvarfloat( "scr_br_pe_choppers_weight", 1.0 );
    scripts\mp\gametypes\br_publicevents::registerpublicevent( 1, ::validatefunc, var_0, ::waitfunc, ::activatefunc );
}

validatefunc()
{
    var_0 = scripts\mp\utility\game::getsubgametype() == "dmz";
    return !var_0;
}

waitfunc()
{
    level endon( "game_ended" );
    var_0 = calculateeventstarttime();
    wait( var_0 );
}

activatefunc()
{
    level endon( "game_ended" );
    scripts\mp\gametypes\br_publicevents::showsplashtoall( "br_pe_choppers_start" );
    level thread spawnchoppers();
    var_0 = 10.0;
    waituntilallchoppersaredead( var_0 );
}

calculateeventstarttime()
{
    var_0 = getdvarfloat( "scr_br_pe_choppers_starttime_min", 555.0 );
    var_1 = getdvarfloat( "scr_br_pe_choppers_starttime_max", 765.0 );

    if ( var_1 > var_0 )
        return randomfloatrange( var_0, var_1 );
    else
        return var_0;
}

waituntilallchoppersaredead( var_0 )
{
    level endon( "game_ended" );

    if ( isdefined( var_0 ) )
        wait( var_0 );

    for (;;)
    {
        var_1 = level.loot_choppers;

        if ( !isdefined( var_1 ) )
            break;

        var_1 = scripts\engine\utility::array_removeundefined( var_1 );

        if ( var_1.size == 0 )
            break;

        wait 1.0;
    }
}

spawnchoppers()
{
    level endon( "game_ended" );
    var_0 = undefined;
    var_1 = undefined;

    if ( isdefined( level.br_circle ) && isdefined( level.br_circle.safecircleent ) )
    {
        var_0 = level.br_level.br_circlecenters[4];
        var_1 = level.br_level.br_circleradii[6];
    }
    else
    {
        level.adjusteventdistributionpadding = 35;
        level.pushdistributiontowardoppositecorner = 1;
        level.buystationsusepaddingdistribution = 0;
        level thread scripts\mp\gametypes\br_functional_poi::setupmapquadrantcornersandgrid();
    }

    scripts\mp\gametypes\br_lootchopper::init();
    scripts\cp_mp\utility\script_utility::registersharedfunc( "br_lootchopper", "lootChopper_onCrateUse", ::oncrateuse );
    var_2 = scripts\mp\gametypes\br_lootchopper::lootchopper_initcircleinfo( var_0, var_1 );
    scripts\mp\gametypes\br_lootchopper::lootchopper_initspawninfo( var_2 );
    var_3 = getdvarint( "scr_br_pe_choppers_count", 5 );
    var_4 = getdvarint( "scr_br_pe_choppers_mindist", 6000 );

    if ( level.mapname == "mp_br_mechanics" )
        var_4 = 1000;

    for ( var_5 = 0; var_5 < var_3; var_5++ )
    {
        var_6 = var_5 % 4 + 1;
        var_7 = scripts\mp\gametypes\br_lootchopper::lootchopper_findunoccupiedpatrolzone( level.loot_chopper_spawns["quad_" + var_6], var_4 );
        var_8 = scripts\mp\gametypes\br_lootchopper::lootchopper_spawn( var_7 );

        if ( isdefined( var_8 ) )
        {
            var_8.lootfunc = ::dropcrate;
            var_8.frontturret.turretdisabled = 1;
            var_8.rearturret.turretdisabled = 1;
            var_8.flaresreservecount = getdvarint( "scr_br_pe_choppers_flares", 0 );
            var_8.health = getdvarint( "scr_br_pe_choppers_health", 5000 );
            var_8.maxhealth = getdvarint( "scr_br_pe_choppers_health", 5000 );
        }

        wait 1;
    }

    var_9 = getdvarfloat( "scr_br_pe_chopppers_circle_damage_start_time", 10.0 );
    level.br_pe_chopper_damage_time = gettime() + int( var_9 * 1000.0 );
}

dropcrate()
{
    var_0 = scripts\mp\gametypes\br_lootchopper::lootchopper_finddroplocation( self.origin + ( 0, 0, 500 ) );

    if ( isdefined( var_0 ) )
    {
        var_1 = scripts\cp_mp\killstreaks\airdrop::dropbrlootchoppercrate( self.origin, var_0 );
        var_2 = scripts\cp_mp\killstreaks\airdrop::gettriggerobject( var_1 );
        var_2.usetimeoverride = 10;

        if ( !isdefined( level.br_pe_chopper_crates ) )
            level.br_pe_chopper_crates = [];

        level.br_pe_chopper_crates[level.br_pe_chopper_crates.size] = var_1;
    }
}

oncrateuse( var_0 )
{
    var_1 = 10000;
    self.itemsdropped = 0;
    scripts\mp\gametypes\br_plunder::dropplunderbyrarity( var_1 / 100, 10 );

    if ( !isdefined( var_0.lootcachesopened ) )
        var_0.lootcachesopened = 1;
    else
        var_0.lootcachesopened++;

    var_0 scripts\mp\utility\stats::setextrascore1( var_0.lootcachesopened );
    var_0 thread scripts\mp\utility\points::giveunifiedpoints( "br_loot_chopper_box_open" );
}

dangercircletick( var_0, var_1 )
{
    if ( !isdefined( level.br_pe_chopper_damage_time ) || gettime() < level.br_pe_chopper_damage_time )
        return;

    var_2 = getdvarfloat( "scr_br_pe_choppers_circle_damage_tick", 500.0 );
    var_3 = 240.0;
    var_4 = level.loot_choppers;

    if ( isdefined( var_4 ) )
    {
        var_4 = scripts\engine\utility::array_removeundefined( var_4 );

        foreach ( var_6 in var_4 )
        {
            var_7 = 0;
            var_8 = var_6.origin;
            var_9 = distance2d( var_0, var_8 );

            if ( var_9 + var_3 > var_1 )
                var_7 = 1;

            if ( var_7 )
            {
                var_10 = var_6.health;
                var_11 = var_6.maxhealth;
                var_6 dodamage( var_2, var_8, undefined, undefined, "MOD_TRIGGER_HURT", "danger_circle_br" );
            }
        }
    }

    var_13 = getdvarfloat( "scr_br_circle_object_cleanup_threshold", 2400.0 );
    var_14 = level.br_pe_chopper_crates;

    if ( isdefined( var_14 ) )
    {
        var_14 = scripts\engine\utility::array_removeundefined( var_14 );

        foreach ( var_16 in var_14 )
        {
            var_17 = distance2dsquared( var_16.origin, var_0 );
            var_18 = max( 0, var_1 + var_13 );

            if ( var_17 > var_18 * var_18 )
                var_16 thread scripts\cp_mp\killstreaks\airdrop::destroycrate();
        }
    }
}
