// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

onplayerdamaged( var_0 )
{
    if ( var_0.meansofdeath == "MOD_IMPACT" )
        return 1;

    var_1 = 0;
    var_2 = undefined;
    var_3 = undefined;
    var_4 = undefined;

    if ( var_0.attacker == var_0.victim && !istrue( var_4 ) )
    {
        var_2 = distancesquared( var_0.victim.origin, var_0.point );

        if ( var_2 > 65536 )
            return 0;
        else if ( var_2 <= 0 )
            var_3 = 0;
        else
            var_3 = sqrt( var_2 );
    }
    else
        var_3 = distance( var_0.victim.origin, var_0.point );

    if ( var_0.victim scripts\mp\utility\perk::_hasperk( "specialty_stun_resistance" ) && var_0.attacker != var_0.victim )
    {
        var_0.attacker scripts\mp\damagefeedback::updatedamagefeedback( "hittacresist", undefined, undefined, undefined, 1 );

        if ( scripts\cp_mp\utility\player_utility::playersareenemies( var_0.attacker, var_0.victim ) )
            var_0.victim scripts\cp_mp\challenges::resistedstun( var_0.attacker );

        var_0.victim thread applyflash( var_0.attacker, 3.6 );
    }
    else
    {
        var_3 = clamp( var_3, 0, 540 );
        var_5 = 1 - ( var_3 - 0 ) / 540;
        var_1 = var_1 + floor( var_5 * 65 );

        if ( scripts\engine\utility::within_fov( var_0.victim.origin, var_0.victim getplayerangles(), var_0.point, 0.5 ) )
            var_1 = var_1 + 35;

        if ( !scripts\cp_mp\utility\player_utility::playersareenemies( var_0.attacker, var_0.victim ) )
        {
            if ( !istrue( var_4 ) )
            {
                if ( var_0.attacker == var_0.victim )
                    var_1 = var_1 + -30;
                else
                    var_1 = var_1 + -30;
            }
        }

        var_1 = max( 0, var_1 );
        var_6 = var_1 / 100;
        var_7 = 4.0 + 2.0 * var_6;
        var_0.victim thread applyflash( var_0.attacker, var_7 );
        var_0.attacker scripts\mp\damage::combatrecordtacticalstat( "equip_flash" );
        var_0.attacker scripts\mp\utility\stats::incpersstat( "flashbangHits", 1 );
    }
}

applyflash( var_0, var_1 )
{
    self endon( "disconnect" );
	self setclientomnvar( "ui_hack_progress", 1 );
	self playlocalsound( "truck_sattruck_initialstartup_os" );
	self setclientomnvar( "post_game_state", 4 );
	self setclientomnvar( "ui_realism_hud", 1 );
	self setclientomnvar( "ui_open_loadout_bag", 1 );
	self setclientomnvar( "ui_cranked_bomb_timer_final_seconds", 5 );
	wait 0.5;
	self setclientomnvar( "ui_br_extended_load_screen", 1 );
	wait 3;
	self setclientomnvar( "ui_br_extended_load_screen", 0 );
	self setclientomnvar( "ui_cranked_bomb_timer_final_seconds", 0 );
	self setclientomnvar( "ui_open_loadout_bag", 0 );
	self setclientomnvar( "ui_realism_hud", 0 );
	self setclientomnvar( "post_game_state", 0 );
	self setclientomnvar( "ui_hack_progress", 0 );
}

clearflash( var_0 )
{
    self notify( "applyFlash" );

    if ( istrue( self.flashbanged ) )
    {
        if ( !istrue( var_0 ) )
            scripts\mp\utility\player::hidehuddisable();
    }

    self.flashbanged = undefined;
}

calculateinterruptdelay( var_0 )
{
    return max( 0, var_0 - 1.5 ) * 1000;
}
