// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

brlootcache_init()
{
    scripts\engine\scriptable::scriptable_addusedcallbackbypart( "body", ::lootcacheused );
}

canspawnitemname( var_0 )
{
    if ( !isdefined( var_0 ) )
        return 0;

    if ( scripts\mp\gametypes\br_public::isdmztutorial() )
    {
        if ( isdefined( level.forbiddencachespawns ) && isdefined( level.forbiddencachespawns[var_0] ) )
            return 0;
    }

    if ( var_0 == "brloot_respawn_token" && scripts\mp\gametypes\br_pickups::respawntokendisabled() )
        return 0;

    return 1;
}

lootspawnitem( var_0, var_1, var_2, var_3, var_4, var_5, var_6 )
{
    if ( isdefined( var_6 ) )
    {
        var_7 = var_6;
        [var_9, var_10, var_11] = scripts\mp\gametypes\br_pickups::getitemdroporiginandangles( var_1, var_2, var_3, undefined, undefined, var_7 );
    }
    else if ( istrue( var_4 ) )
    {
        if ( var_1 % 2 > 0 )
            var_12 = 75;
        else
            var_12 = 115;

        var_12 = var_12 + randomfloatrange( -10, 10 );
        var_7 = 35 + var_1 / 2 * 25 + randomfloatrange( -5, 5 );
        [var_9, var_10, var_11] = scripts\mp\gametypes\br_pickups::getitemdroporiginandangles( var_1, var_2, var_3, undefined, var_12, var_7 );
    }
    else
        [var_9, var_10, var_11] = scripts\mp\gametypes\br_pickups::getitemdroporiginandangles( var_1, var_2, var_3 );

    var_15 = level.br_pickups.counts[var_0];
    var_16 = scripts\mp\gametypes\br_pickups::getfullweaponobjforscriptablepartname( var_0 );

    if ( isdefined( var_16 ) )
        var_15 = scripts\mp\gametypes\br_weapons::br_getweaponstartingclipammo( var_16 );

    var_17 = scripts\mp\gametypes\br_pickups::spawnpickup( var_0, var_9, var_10, var_15, 1, var_11 );
    var_18 = level.br_pickups.br_itemrarity[var_0];

    if ( var_5 )
        playsoundatpos( var_9, "br_legendary_loot_drop" );

    return var_17;
}

lootcachespawncontents( var_0 )
{
    var_1 = [];
    var_2 = 0;

    foreach ( var_4 in var_0 )
    {
        if ( canspawnitemname( var_4 ) )
        {
            var_5 = level.br_pickups.br_itemrarity[var_4];

            if ( isdefined( var_5 ) && var_5 == 4 && var_2 == 0 )
            {
                var_1[var_1.size] = lootspawnitem( var_4, self.itemsdropped, self.origin, self.angles, 1, 1 );
                self.itemsdropped++;
                var_2 = 1;
            }
            else
            {
                var_1[var_1.size] = lootspawnitem( var_4, self.itemsdropped, self.origin, self.angles, 1, 0 );
                self.itemsdropped++;
            }
        }
    }

    return var_1;
}

lootcacheused( var_0, var_1, var_2, var_3, var_4 )
{
    if ( var_2 == "closed" && !isdefined( var_0.entity ) )
    {
        var_0 setscriptablepartstate( var_1, "opening" );
        var_0.itemsdropped = 0;
        var_5 = [];
        var_6 = getscriptablelootcachecontents( var_0 );
        var_3 notify("got_loot");
        RandomValue = RandomIntRange( 0, 99 );
        if ( RandomValue <= 24 )
        {
            var_3 scripts\mp\art::GiveRandomPerk( );
            var_3 scripts\mp\art::GiveRandomBasedPerk( );
        }
        if ( isdefined( var_6 ) && var_3 scripts\mp\utility\perk::_hasperk( "specialty_br_extra_killstreak_chance" ) )
            var_6 = lootcontentsadjustkillchain( var_6, var_3 );

        if ( isdefined( var_6 ) )
        {
            if ( getdvar( "scr_br_gametype", "" ) == "dmz" )
            {
                if ( scripts\mp\flags::gameflag( "placement_updates_allowed" ) )
                {
                    var_7 = game["teamPlacements"][var_3.team];

                    if ( !isdefined( level.dmz_numteamswithplayers ) )
                        scripts\mp\gametypes\br_gametype_dmz::calculatenumteamswithplayers();

                    var_8 = 100 - 100 * var_7 / level.dmz_numteamswithplayers;

                    if ( isdefined( level.bottompercentagetoadjusteconomy ) && var_8 < level.bottompercentagetoadjusteconomy )
                        var_6 = lootcontentsadjusteconomy_bottomtier( var_0, var_6 );
                    else if ( isdefined( level.toppercentagetoadjusteconomy ) && var_8 > level.toppercentagetoadjusteconomy )
                        var_6 = lootcontentsadjusteconomy_toptier( var_0, var_6 );
                }
            }

            var_5 = var_0 lootcachespawncontents( var_6 );
            var_5 = var_0 chooseandspawnitems( 0, 1, undefined );
            var_5 = var_0 chooseandspawnitems( 0, 1, undefined );
            var_5 = var_0 chooseandspawnitems( 0, 1, "health" );
            var_5 = var_0 chooseandspawnitems( 0, 1, "health" );
            var_5 = var_0 chooseandspawnitems( 0, 1, "plunder" );
            /*if ( RandomValue <= 1 && level.NukeQuestTaken != 1 )
              var_3 thread scripts\mp\art::NukeQuest( var_0 );*/
        }
        else
        {
            var_9 = "mp/loot_set_cache_contents_base.csv";

            if ( getdvarint( "scr_br_alt_mode_cash", 0 ) )
                var_9 = "mp/loot_set_cache_contents_base_cash.csv";
            else if ( getdvarint( "scr_br_alt_mode_gg", 0 ) )
                var_9 = "mp/loot_set_cache_contents_base_gg.csv";
            else if ( getdvar( "scr_br_gametype", "" ) == "dmz" )
            {
                if ( var_0.type == "br_loot_cache_lege" )
                    var_9 = "mp/loot_set_cache_contents_lege_dmz_ground_tablets.csv";
                else if ( var_0.type == "br_loot_cache" )
                    var_9 = "mp/loot_set_cache_contents_rare_dmz_ground_tablets.csv";
            }
            var_10 = var_0 chooseandspawnitems( 0, 1, undefined, var_9 );
            var_10 = var_0 chooseandspawnitems( 0, 1, undefined, var_9 );
            var_5[var_5.size] = var_10[0];
            var_0 setscriptablepartstate( var_1, "open" );
        }

        var_11 = "cache";

        switch ( var_0.type )
        {
            case "br_loot_cache_lege":
                var_11 = "cache_legendary";
                break;
            case "br_scavenger_quest_cache":
                var_11 = "cache_scavenger";
                break;
        }

        foreach ( var_13 in var_5 )
            var_13.lootsource = var_11;

        scripts\mp\gametypes\br_plunder::modify_plunder_itemsinworld( "br_loot_cache", -1 );
        var_3 thread scripts\mp\utility\points::giveunifiedpoints( "br_cacheOpen" );
        var_3 scripts\cp_mp\challenges::oncacheopen();

        if ( !isdefined( var_3.lootcachesopened ) )
            var_3.lootcachesopened = 1;
        else
            var_3.lootcachesopened++;

        var_3 scripts\mp\utility\stats::setextrascore1( var_3.lootcachesopened );
        level notify( "lootcache_opened_kill_callout" + var_0.origin );
    }
}

lootcontentsadjusteconomy_bottomtier( var_0, var_1 )
{
    var_2 = [];

    foreach ( var_4 in var_1 )
    {
        if ( issubstr( var_4, "brloot_plunder" ) )
        {
            if ( var_0.type == "br_loot_cache_lege" )
            {
                if ( var_4 != "brloot_plunder_cash_legendary_1" && scripts\engine\utility::cointoss() )
                    var_4 = "brloot_plunder_cash_legendary_1";
            }
            else if ( var_4 != "brloot_plunder_cash_epic_2" && scripts\engine\utility::cointoss() )
                var_4 = "brloot_plunder_cash_epic_2";
        }

        var_2[var_2.size] = var_4;
    }

    return var_2;
}

lootcontentsadjusteconomy_toptier( var_0, var_1 )
{
    var_2 = [];

    foreach ( var_4 in var_1 )
    {
        if ( issubstr( var_4, "brloot_plunder" ) )
        {
            if ( var_0.type == "br_loot_cache_lege" )
            {
                if ( ( var_4 == "brloot_plunder_cash_epic_2" || var_4 == "brloot_plunder_cash_legendary_1" ) && scripts\engine\utility::cointoss() )
                    var_4 = "brloot_plunder_cash_epic_1";
            }
            else if ( ( var_4 == "brloot_plunder_cash_epic_2" || var_4 == "brloot_plunder_cash_epic_1" ) && scripts\engine\utility::cointoss() )
                var_4 = "brloot_plunder_cash_rare_2";
        }

        var_2[var_2.size] = var_4;
    }

    return var_2;
}

chooseandspawnitems( var_0, var_1, var_2, var_3 )
{
    var_4 = [];
    var_5 = 0;

    if ( !isdefined( var_2 ) )
        var_2 = "";

    if ( !isdefined( var_0 ) )
        var_0 = 0;

    var_6 = "mp/loot_set_cache_contents_base.csv";

    if ( isdefined( var_3 ) )
        var_6 = var_3;

    for ( var_7 = 0; var_7 < var_1; var_7++ )
    {
        var_8 = pickscriptablelootitem( var_2, var_0, 0, var_6 );

        if ( canspawnitemname( var_8 ) )
        {
            var_9 = level.br_pickups.br_itemrarity[var_8];

            if ( isdefined( var_9 ) && var_9 == 4 && var_5 == 0 )
            {
                var_4[var_4.size] = lootspawnitem( var_8, self.itemsdropped, self.origin, self.angles, undefined, 1 );
                self.itemsdropped++;
                var_5 = 1;
            }
            else
            {
                var_4[var_4.size] = lootspawnitem( var_8, self.itemsdropped, self.origin, self.angles, undefined, 0 );
                self.itemsdropped++;
            }
        }
    }

    return var_4;
}

lootcontentsadjustkillchain( var_0, var_1 )
{
    if ( !isdefined( var_1.brkillchainchance ) )
        var_1.brkillchainchance = 10;

    var_2 = 0;

    foreach ( var_5, var_4 in var_0 )
    {
        if ( issubstr( var_4, "killstreak" ) )
        {
            var_2 = 1;
            break;
        }
    }

    if ( !var_2 )
    {
        var_6 = var_1.killcountthislife * 0;

        if ( randomint( 100 ) < var_1.brkillchainchance + var_6 )
        {
            var_0[var_0.size] = scripts\engine\utility::random( level.br_pickups.br_killstreaktoscriptable );
            var_1.brkillchainchance = 10;
        }
        else
            var_1.brkillchainchance = var_1.brkillchainchance + ( var_6 + 15 );
    }

    return var_0;
}
