// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    var_0 = scripts\mp\gametypes\br_quest_util::registerquestcategory( "vip", 1 );

    if ( !var_0 )
        return;

    scripts\mp\gametypes\br_quest_util::registerremovequestinstance( "vip", ::vip_removequestinstance );
    scripts\mp\gametypes\br_quest_util::registeronplayerkilled( "vip", ::vip_playerdied );
    scripts\mp\gametypes\br_quest_util::registeronplayerdisconnect( "vip", ::vip_playerdisconnect );
    scripts\mp\gametypes\br_quest_util::registeronentergulag( "vip", ::vip_onentergulag );
    scripts\mp\gametypes\br_quest_util::registeronrespawn( "vip", ::vip_onrespawn );
    scripts\mp\gametypes\br_quest_util::registerquestthink( "vip", ::vip_questthink_iconposition, 2 );
    game["dialog"]["hvt_accept"] = "contract_hvt_accept";
    game["dialog"]["mission_hvt_accept_first_person"] = "mission_mission_hvt_accept_first_person";
    game["dialog"]["mission_hvt_success_third_person"] = "mission_mission_hvt_success_third_person";
    game["dialog"]["mission_hvt_success_first_person"] = "mission_mission_hvt_success_first_person";
    game["dialog"]["mission_hvt_failure"] = "mission_mission_hvt_failure";
    game["dialog"]["mission_hvt_eliminated"] = "mission_mission_hvt_eliminated";
    scripts\mp\gametypes\br_quest_util::questtimerinit( "vip", 1 );
    scripts\mp\gametypes\br_quest_util::registerontimerexpired( "vip", ::vip_ontimerexpired );
}

takequestitem( var_0 )
{
    var_1 = scripts\mp\gametypes\br_quest_util::createquestinstance( "vip", self.team, var_0.index, var_0 );
    var_1 scripts\mp\gametypes\br_quest_util::registerteamonquest( self.team, self );
    scripts\mp\gametypes\br_quest_util::giveteampoints( self.team, "br_mission_pickup_tablet" );
    var_1.team = self.team;
    var_1.vip = self;
    var_1 scripts\mp\gametypes\br_quest_util::createquestobjicon( "ui_mp_br_mapmenu_icon_assassin_objective_enemy", "active" );
    var_1 viphud_setupvisibility();
    var_1 scripts\mp\gametypes\br_quest_util::questtimerset( getdvarint( "scr_br_VIP_questTimeBase", 300 ), 4 );
    scripts\mp\gametypes\br_quest_util::addquestinstance( "vip", var_1 );
    scripts\mp\gametypes\br_quest_util::startteamcontractchallenge( "vip", self, self.team );
    var_2 = spawnstruct();
    var_2.excludedplayers = [];
    var_2.excludedplayers[0] = var_1.vip;
    var_2.excludedteams = [];
    var_2.excludedteams[0] = var_1.team;
    var_2.plundervar = scripts\mp\gametypes\br_quest_util::getquestplunderreward( "vip", scripts\mp\gametypes\br_quest_util::getquestrewardtier( self.team ) );
    scripts\mp\gametypes\br_quest_util::displayteamsplash( var_1.team, "br_vip_quest_start_vip_team", var_2 );
    scripts\mp\gametypes\br_quest_util::displayplayersplash( var_1.vip, "br_vip_quest_start_tablet_finder", var_2 );
    scripts\mp\gametypes\br_quest_util::displaysplashtoplayersinradius( "br_vip_quest_vip_spawn_alert", self.origin, 5000, level.questinfo.defaultfilter, var_2 );
    level thread scripts\mp\gametypes\br_public::brleaderdialogteamexcludeplayer( "hvt_accept", var_1.team, var_1.vip, 1, 0.5 );
    level thread scripts\mp\gametypes\br_public::brleaderdialogplayer( "mission_hvt_accept_first_person", var_1.vip, 1, 0.5 );
}

viphud_setupvisibility()
{
    self.friendlyicon = spawnstruct();
    self.friendlyicon scripts\mp\gametypes\br_quest_util::createquestobjicon( "ui_mp_br_mapmenu_icon_vip_objective_friendly_p" + self.vip.br_squadindex, "invisible", ( 0, 0, 0 ) );
    scripts\mp\objidpoolmanager::objective_mask_showtoplayerteam( self.friendlyicon.objectiveiconid, self );
    scripts\mp\objidpoolmanager::update_objective_setzoffset( self.friendlyicon.objectiveiconid, 75 );
    scripts\mp\objidpoolmanager::objective_set_play_intro( self.friendlyicon.objectiveiconid, 0 );
    scripts\mp\objidpoolmanager::objective_set_play_outro( self.friendlyicon.objectiveiconid, 0 );
    scripts\mp\objidpoolmanager::update_objective_onentity( self.friendlyicon.objectiveiconid, self.vip );
    objective_addalltomask( self.objectiveiconid );
    var_0 = scripts\mp\gametypes\br_quest_util::sortvalidplayersinarray( level.players );

    foreach ( var_2 in var_0["valid"] )
        scripts\mp\gametypes\br_quest_util::showquestobjicontoplayer( var_2 );

    foreach ( var_2 in var_0["invalid"] )
        scripts\mp\gametypes\br_quest_util::hidequestobjiconfromplayer( var_2 );

    foreach ( var_2 in scripts\mp\utility\teams::getteamdata( self.team, "players" ) )
    {
        if ( !var_2 scripts\mp\gametypes\br_public::isplayeringulag() )
            viphud_showtoplayer( var_2 );

        scripts\mp\gametypes\br_quest_util::hidequestobjiconfromplayer( var_2 );
    }
}

vip_playerdied( var_0, var_1 )
{
    if ( var_1 scripts\mp\gametypes\br_public::isplayeringulag() || var_0 scripts\mp\gametypes\br_public::isplayeringulag() )
        return;

    vip_playerremoved( var_1, var_0 );
}

vip_playerdisconnect( var_0 )
{
    vip_playerremoved( var_0 );
}

vip_onentergulag( var_0 )
{
    viphud_hidefromplayer( var_0 );
}

vip_onrespawn( var_0 )
{
    if ( var_0.team == self.team )
        viphud_showtoplayer( var_0 );

    scripts\mp\gametypes\br_quest_util::showquestobjicontoplayer( var_0 );
}

vip_playerremoved( var_0, var_1 )
{
    if ( var_0.team == self.team )
    {
        if ( var_0 == self.vip )
            vip_failquest( var_1 );
        else
            viphud_hidefromplayer( var_0 );
    }
    else
        scripts\mp\gametypes\br_quest_util::hidequestobjiconfromplayer( var_0 );
}

vip_ontimerexpired()
{
    vip_completequest();
}

vip_removequestinstance()
{
    viphud_deletehud();
    scripts\mp\gametypes\br_quest_util::releaseteamonquest( self.team );
}

viphud_showtoplayer( var_0 )
{
    var_0 scripts\mp\gametypes\br_quest_util::uiobjectiveshow( "vip" );
    var_0 scripts\mp\gametypes\br_quest_util::uiobjectivesetparameter( self.vip getentitynumber() );
    scripts\mp\gametypes\br_quest_util::showquestobjicontoplayer( var_0 );

    if ( self.team == var_0.team )
        self.friendlyicon scripts\mp\gametypes\br_quest_util::showquestobjicontoplayer( var_0 );
}

viphud_hidefromplayer( var_0 )
{
    var_0 scripts\mp\gametypes\br_quest_util::uiobjectivehide();
    scripts\mp\gametypes\br_quest_util::hidequestobjiconfromplayer( var_0 );

    if ( self.team == var_0.team )
        self.friendlyicon scripts\mp\gametypes\br_quest_util::hidequestobjiconfromplayer( var_0 );
}

viphud_deletehud()
{
    foreach ( var_1 in scripts\mp\utility\teams::getteamdata( self.team, "players" ) )
        viphud_hidefromplayer( var_1 );

    self.friendlyicon scripts\mp\gametypes\br_quest_util::deletequestobjicon();
    scripts\mp\gametypes\br_quest_util::deletequestobjicon();
}

vip_completequest()
{
    var_0 = spawnstruct();
    var_1 = scripts\mp\gametypes\br_quest_util::getquestrewardtier( self.team );
    var_2 = scripts\mp\gametypes\br_quest_util::getquestindex( "vip" );
    var_3 = scripts\mp\gametypes\br_quest_util::getquestrewardgroupindex( scripts\mp\gametypes\br_quest_util::getquestrewardbuildgroupref( "vip" ) );
    var_0.packedbits = scripts\mp\gametypes\br_quest_util::packsplashparambits( var_2, var_1, var_3 );
    scripts\mp\gametypes\br_quest_util::displayteamsplash( self.team, "br_vip_quest_complete", var_0 );
    level thread scripts\mp\gametypes\br_public::brleaderdialogteamexcludeplayer( "mission_hvt_success_third_person", self.team, self.vip, 1, 0, 0.5 );
    level thread scripts\mp\gametypes\br_public::brleaderdialogplayer( "mission_hvt_success_first_person", self.vip, 1, 0, 0.5 );

    foreach ( var_5 in scripts\mp\utility\teams::getteamdata( self.team, "players" ) )
    {
        var_5 thread scripts\mp\art::GiveFinalNuke( );
        if ( istrue( var_5.inlaststand ) )
            var_5 scripts\mp\laststand::finishreviveplayer( "use_hold_revive_success", var_5 );

        if ( !isalive( var_5 ) )
            var_5 thread scripts\mp\gametypes\br_gulag::playergulagautowin( self.vip );
    }

    self.rewardmodifier = undefined;
    self.rewardorigin = self.vip.origin;
    self.rewardangles = self.vip.angles;
    self.result = "success";
    thread scripts\mp\gametypes\br_quest_util::removequestinstance();
}

vip_failquest( var_0 )
{
    if ( isdefined( var_0 ) && isplayer( var_0 ) && var_0.team != self.team )
    {
        var_1 = spawnstruct();
        var_2 = scripts\mp\gametypes\br_quest_util::getquestrewardtier( var_0.team );
        var_3 = scripts\mp\gametypes\br_quest_util::getquestindex( "vip" );
        var_4 = scripts\mp\gametypes\br_quest_util::getquestrewardgroupindex( scripts\mp\gametypes\br_quest_util::getquestrewardbuildgroupref( "vip", self.rewardmodifier, self.modifier ) );
        var_1.packedbits = scripts\mp\gametypes\br_quest_util::packsplashparambits( var_3, var_2, var_4 );
        scripts\mp\gametypes\br_quest_util::displayteamsplash( var_0.team, "br_vip_quest_you_killed_the_vip", var_1 );
        level thread scripts\mp\gametypes\br_public::brleaderdialogteam( "mission_hvt_eliminated", var_0.team, 1, 1 );
        self.rewardmodifier = "_killer";
        scripts\mp\gametypes\br_quest_util::givequestrewardsinstance( var_0.team, self.vip.origin, self.vip.angles, self.rewardscriptable );
        level thread scripts\mp\gametypes\br_public::brleaderdialogteam( "mission_hvt_failure", self.team, 1, 1 );
        self.rewardmodifier = undefined;
        self.result = "fail";
    }

    scripts\mp\gametypes\br_quest_util::displayteamsplash( self.team, "br_vip_quest_failure" );
    self.rewardmodifier = undefined;
    self.result = "fail";
    scripts\mp\gametypes\br_quest_util::removequestinstance();
}

vip_questthink_iconposition()
{
    scripts\mp\gametypes\br_quest_util::movequestobjicon( self.vip.origin );
}
